#include "QtRocket/util/L10N.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <span>
#include <string>
#include <string_view>

#include "QtRocket/util/Strings.h"

namespace QtRocket::L10N
{

namespace
{

struct Normalization
{
    char32_t         codePoint;
    std::string_view replacement;
};

/// L10N.NORMALIZATION_MAP (generated by OpenRocket's L10NGenerator), in code point order.
constexpr std::array<Normalization, 291> kNormalizationMap{{
    {.codePoint = 0x00A0, .replacement = " "},   {.codePoint = 0x00AA, .replacement = "a"},
    {.codePoint = 0x00B2, .replacement = "2"},   {.codePoint = 0x00B3, .replacement = "3"},
    {.codePoint = 0x00B9, .replacement = "1"},   {.codePoint = 0x00BA, .replacement = "o"},
    {.codePoint = 0x00BC, .replacement = "1/4"}, {.codePoint = 0x00BD, .replacement = "1/2"},
    {.codePoint = 0x00BE, .replacement = "3/4"}, {.codePoint = 0x00C0, .replacement = "A"},
    {.codePoint = 0x00C1, .replacement = "A"},   {.codePoint = 0x00C2, .replacement = "A"},
    {.codePoint = 0x00C3, .replacement = "A"},   {.codePoint = 0x00C4, .replacement = "A"},
    {.codePoint = 0x00C5, .replacement = "A"},   {.codePoint = 0x00C7, .replacement = "C"},
    {.codePoint = 0x00C8, .replacement = "E"},   {.codePoint = 0x00C9, .replacement = "E"},
    {.codePoint = 0x00CA, .replacement = "E"},   {.codePoint = 0x00CB, .replacement = "E"},
    {.codePoint = 0x00CC, .replacement = "I"},   {.codePoint = 0x00CD, .replacement = "I"},
    {.codePoint = 0x00CE, .replacement = "I"},   {.codePoint = 0x00CF, .replacement = "I"},
    {.codePoint = 0x00D1, .replacement = "N"},   {.codePoint = 0x00D2, .replacement = "O"},
    {.codePoint = 0x00D3, .replacement = "O"},   {.codePoint = 0x00D4, .replacement = "O"},
    {.codePoint = 0x00D5, .replacement = "O"},   {.codePoint = 0x00D6, .replacement = "O"},
    {.codePoint = 0x00D9, .replacement = "U"},   {.codePoint = 0x00DA, .replacement = "U"},
    {.codePoint = 0x00DB, .replacement = "U"},   {.codePoint = 0x00DC, .replacement = "U"},
    {.codePoint = 0x00DD, .replacement = "Y"},   {.codePoint = 0x00E0, .replacement = "a"},
    {.codePoint = 0x00E1, .replacement = "a"},   {.codePoint = 0x00E2, .replacement = "a"},
    {.codePoint = 0x00E3, .replacement = "a"},   {.codePoint = 0x00E4, .replacement = "a"},
    {.codePoint = 0x00E5, .replacement = "a"},   {.codePoint = 0x00E7, .replacement = "c"},
    {.codePoint = 0x00E8, .replacement = "e"},   {.codePoint = 0x00E9, .replacement = "e"},
    {.codePoint = 0x00EA, .replacement = "e"},   {.codePoint = 0x00EB, .replacement = "e"},
    {.codePoint = 0x00EC, .replacement = "i"},   {.codePoint = 0x00ED, .replacement = "i"},
    {.codePoint = 0x00EE, .replacement = "i"},   {.codePoint = 0x00EF, .replacement = "i"},
    {.codePoint = 0x00F1, .replacement = "n"},   {.codePoint = 0x00F2, .replacement = "o"},
    {.codePoint = 0x00F3, .replacement = "o"},   {.codePoint = 0x00F4, .replacement = "o"},
    {.codePoint = 0x00F5, .replacement = "o"},   {.codePoint = 0x00F6, .replacement = "o"},
    {.codePoint = 0x00F9, .replacement = "u"},   {.codePoint = 0x00FA, .replacement = "u"},
    {.codePoint = 0x00FB, .replacement = "u"},   {.codePoint = 0x00FC, .replacement = "u"},
    {.codePoint = 0x00FD, .replacement = "y"},   {.codePoint = 0x00FF, .replacement = "y"},
    {.codePoint = 0x0100, .replacement = "A"},   {.codePoint = 0x0101, .replacement = "a"},
    {.codePoint = 0x0102, .replacement = "A"},   {.codePoint = 0x0103, .replacement = "a"},
    {.codePoint = 0x0104, .replacement = "A"},   {.codePoint = 0x0105, .replacement = "a"},
    {.codePoint = 0x0106, .replacement = "C"},   {.codePoint = 0x0107, .replacement = "c"},
    {.codePoint = 0x0108, .replacement = "C"},   {.codePoint = 0x0109, .replacement = "c"},
    {.codePoint = 0x010A, .replacement = "C"},   {.codePoint = 0x010B, .replacement = "c"},
    {.codePoint = 0x010C, .replacement = "C"},   {.codePoint = 0x010D, .replacement = "c"},
    {.codePoint = 0x010E, .replacement = "D"},   {.codePoint = 0x010F, .replacement = "d"},
    {.codePoint = 0x0112, .replacement = "E"},   {.codePoint = 0x0113, .replacement = "e"},
    {.codePoint = 0x0114, .replacement = "E"},   {.codePoint = 0x0115, .replacement = "e"},
    {.codePoint = 0x0116, .replacement = "E"},   {.codePoint = 0x0117, .replacement = "e"},
    {.codePoint = 0x0118, .replacement = "E"},   {.codePoint = 0x0119, .replacement = "e"},
    {.codePoint = 0x011A, .replacement = "E"},   {.codePoint = 0x011B, .replacement = "e"},
    {.codePoint = 0x011C, .replacement = "G"},   {.codePoint = 0x011D, .replacement = "g"},
    {.codePoint = 0x011E, .replacement = "G"},   {.codePoint = 0x011F, .replacement = "g"},
    {.codePoint = 0x0120, .replacement = "G"},   {.codePoint = 0x0121, .replacement = "g"},
    {.codePoint = 0x0122, .replacement = "G"},   {.codePoint = 0x0123, .replacement = "g"},
    {.codePoint = 0x0124, .replacement = "H"},   {.codePoint = 0x0125, .replacement = "h"},
    {.codePoint = 0x0128, .replacement = "I"},   {.codePoint = 0x0129, .replacement = "i"},
    {.codePoint = 0x012A, .replacement = "I"},   {.codePoint = 0x012B, .replacement = "i"},
    {.codePoint = 0x012C, .replacement = "I"},   {.codePoint = 0x012D, .replacement = "i"},
    {.codePoint = 0x012E, .replacement = "I"},   {.codePoint = 0x012F, .replacement = "i"},
    {.codePoint = 0x0130, .replacement = "I"},   {.codePoint = 0x0132, .replacement = "IJ"},
    {.codePoint = 0x0133, .replacement = "ij"},  {.codePoint = 0x0134, .replacement = "J"},
    {.codePoint = 0x0135, .replacement = "j"},   {.codePoint = 0x0136, .replacement = "K"},
    {.codePoint = 0x0137, .replacement = "k"},   {.codePoint = 0x0139, .replacement = "L"},
    {.codePoint = 0x013A, .replacement = "l"},   {.codePoint = 0x013B, .replacement = "L"},
    {.codePoint = 0x013C, .replacement = "l"},   {.codePoint = 0x013D, .replacement = "L"},
    {.codePoint = 0x013E, .replacement = "l"},   {.codePoint = 0x013F, .replacement = "L"},
    {.codePoint = 0x0140, .replacement = "l"},   {.codePoint = 0x0143, .replacement = "N"},
    {.codePoint = 0x0144, .replacement = "n"},   {.codePoint = 0x0145, .replacement = "N"},
    {.codePoint = 0x0146, .replacement = "n"},   {.codePoint = 0x0147, .replacement = "N"},
    {.codePoint = 0x0148, .replacement = "n"},   {.codePoint = 0x0149, .replacement = "n"},
    {.codePoint = 0x014C, .replacement = "O"},   {.codePoint = 0x014D, .replacement = "o"},
    {.codePoint = 0x014E, .replacement = "O"},   {.codePoint = 0x014F, .replacement = "o"},
    {.codePoint = 0x0150, .replacement = "O"},   {.codePoint = 0x0151, .replacement = "o"},
    {.codePoint = 0x0154, .replacement = "R"},   {.codePoint = 0x0155, .replacement = "r"},
    {.codePoint = 0x0156, .replacement = "R"},   {.codePoint = 0x0157, .replacement = "r"},
    {.codePoint = 0x0158, .replacement = "R"},   {.codePoint = 0x0159, .replacement = "r"},
    {.codePoint = 0x015A, .replacement = "S"},   {.codePoint = 0x015B, .replacement = "s"},
    {.codePoint = 0x015C, .replacement = "S"},   {.codePoint = 0x015D, .replacement = "s"},
    {.codePoint = 0x015E, .replacement = "S"},   {.codePoint = 0x015F, .replacement = "s"},
    {.codePoint = 0x0160, .replacement = "S"},   {.codePoint = 0x0161, .replacement = "s"},
    {.codePoint = 0x0162, .replacement = "T"},   {.codePoint = 0x0163, .replacement = "t"},
    {.codePoint = 0x0164, .replacement = "T"},   {.codePoint = 0x0165, .replacement = "t"},
    {.codePoint = 0x0168, .replacement = "U"},   {.codePoint = 0x0169, .replacement = "u"},
    {.codePoint = 0x016A, .replacement = "U"},   {.codePoint = 0x016B, .replacement = "u"},
    {.codePoint = 0x016C, .replacement = "U"},   {.codePoint = 0x016D, .replacement = "u"},
    {.codePoint = 0x016E, .replacement = "U"},   {.codePoint = 0x016F, .replacement = "u"},
    {.codePoint = 0x0170, .replacement = "U"},   {.codePoint = 0x0171, .replacement = "u"},
    {.codePoint = 0x0172, .replacement = "U"},   {.codePoint = 0x0173, .replacement = "u"},
    {.codePoint = 0x0174, .replacement = "W"},   {.codePoint = 0x0175, .replacement = "w"},
    {.codePoint = 0x0176, .replacement = "Y"},   {.codePoint = 0x0177, .replacement = "y"},
    {.codePoint = 0x0178, .replacement = "Y"},   {.codePoint = 0x0179, .replacement = "Z"},
    {.codePoint = 0x017A, .replacement = "z"},   {.codePoint = 0x017B, .replacement = "Z"},
    {.codePoint = 0x017C, .replacement = "z"},   {.codePoint = 0x017D, .replacement = "Z"},
    {.codePoint = 0x017E, .replacement = "z"},   {.codePoint = 0x017F, .replacement = "s"},
    {.codePoint = 0x01A0, .replacement = "O"},   {.codePoint = 0x01A1, .replacement = "o"},
    {.codePoint = 0x01AF, .replacement = "U"},   {.codePoint = 0x01B0, .replacement = "u"},
    {.codePoint = 0x01C4, .replacement = "DZ"},  {.codePoint = 0x01C5, .replacement = "Dz"},
    {.codePoint = 0x01C6, .replacement = "dz"},  {.codePoint = 0x01C7, .replacement = "LJ"},
    {.codePoint = 0x01C8, .replacement = "Lj"},  {.codePoint = 0x01C9, .replacement = "lj"},
    {.codePoint = 0x01CA, .replacement = "NJ"},  {.codePoint = 0x01CB, .replacement = "Nj"},
    {.codePoint = 0x01CC, .replacement = "nj"},  {.codePoint = 0x01CD, .replacement = "A"},
    {.codePoint = 0x01CE, .replacement = "a"},   {.codePoint = 0x01CF, .replacement = "I"},
    {.codePoint = 0x01D0, .replacement = "i"},   {.codePoint = 0x01D1, .replacement = "O"},
    {.codePoint = 0x01D2, .replacement = "o"},   {.codePoint = 0x01D3, .replacement = "U"},
    {.codePoint = 0x01D4, .replacement = "u"},   {.codePoint = 0x01D5, .replacement = "U"},
    {.codePoint = 0x01D6, .replacement = "u"},   {.codePoint = 0x01D7, .replacement = "U"},
    {.codePoint = 0x01D8, .replacement = "u"},   {.codePoint = 0x01D9, .replacement = "U"},
    {.codePoint = 0x01DA, .replacement = "u"},   {.codePoint = 0x01DB, .replacement = "U"},
    {.codePoint = 0x01DC, .replacement = "u"},   {.codePoint = 0x01DE, .replacement = "A"},
    {.codePoint = 0x01DF, .replacement = "a"},   {.codePoint = 0x01E0, .replacement = "A"},
    {.codePoint = 0x01E1, .replacement = "a"},   {.codePoint = 0x01E6, .replacement = "G"},
    {.codePoint = 0x01E7, .replacement = "g"},   {.codePoint = 0x01E8, .replacement = "K"},
    {.codePoint = 0x01E9, .replacement = "k"},   {.codePoint = 0x01EA, .replacement = "O"},
    {.codePoint = 0x01EB, .replacement = "o"},   {.codePoint = 0x01EC, .replacement = "O"},
    {.codePoint = 0x01ED, .replacement = "o"},   {.codePoint = 0x01F0, .replacement = "j"},
    {.codePoint = 0x01F1, .replacement = "DZ"},  {.codePoint = 0x01F2, .replacement = "Dz"},
    {.codePoint = 0x01F3, .replacement = "dz"},  {.codePoint = 0x01F4, .replacement = "G"},
    {.codePoint = 0x01F5, .replacement = "g"},   {.codePoint = 0x01F8, .replacement = "N"},
    {.codePoint = 0x01F9, .replacement = "n"},   {.codePoint = 0x01FA, .replacement = "A"},
    {.codePoint = 0x01FB, .replacement = "a"},   {.codePoint = 0x0200, .replacement = "A"},
    {.codePoint = 0x0201, .replacement = "a"},   {.codePoint = 0x0202, .replacement = "A"},
    {.codePoint = 0x0203, .replacement = "a"},   {.codePoint = 0x0204, .replacement = "E"},
    {.codePoint = 0x0205, .replacement = "e"},   {.codePoint = 0x0206, .replacement = "E"},
    {.codePoint = 0x0207, .replacement = "e"},   {.codePoint = 0x0208, .replacement = "I"},
    {.codePoint = 0x0209, .replacement = "i"},   {.codePoint = 0x020A, .replacement = "I"},
    {.codePoint = 0x020B, .replacement = "i"},   {.codePoint = 0x020C, .replacement = "O"},
    {.codePoint = 0x020D, .replacement = "o"},   {.codePoint = 0x020E, .replacement = "O"},
    {.codePoint = 0x020F, .replacement = "o"},   {.codePoint = 0x0210, .replacement = "R"},
    {.codePoint = 0x0211, .replacement = "r"},   {.codePoint = 0x0212, .replacement = "R"},
    {.codePoint = 0x0213, .replacement = "r"},   {.codePoint = 0x0214, .replacement = "U"},
    {.codePoint = 0x0215, .replacement = "u"},   {.codePoint = 0x0216, .replacement = "U"},
    {.codePoint = 0x0217, .replacement = "u"},   {.codePoint = 0x0218, .replacement = "S"},
    {.codePoint = 0x0219, .replacement = "s"},   {.codePoint = 0x021A, .replacement = "T"},
    {.codePoint = 0x021B, .replacement = "t"},   {.codePoint = 0x021E, .replacement = "H"},
    {.codePoint = 0x021F, .replacement = "h"},   {.codePoint = 0x0226, .replacement = "A"},
    {.codePoint = 0x0227, .replacement = "a"},   {.codePoint = 0x0228, .replacement = "E"},
    {.codePoint = 0x0229, .replacement = "e"},   {.codePoint = 0x022A, .replacement = "O"},
    {.codePoint = 0x022B, .replacement = "o"},   {.codePoint = 0x022C, .replacement = "O"},
    {.codePoint = 0x022D, .replacement = "o"},   {.codePoint = 0x022E, .replacement = "O"},
    {.codePoint = 0x022F, .replacement = "o"},   {.codePoint = 0x0230, .replacement = "O"},
    {.codePoint = 0x0231, .replacement = "o"},   {.codePoint = 0x0232, .replacement = "Y"},
    {.codePoint = 0x0233, .replacement = "y"},   {.codePoint = 0x200B, .replacement = " "},
    {.codePoint = 0x2044, .replacement = "/"},   {.codePoint = 0x2070, .replacement = "0"},
    {.codePoint = 0x2071, .replacement = "i"},   {.codePoint = 0x2074, .replacement = "4"},
    {.codePoint = 0x2075, .replacement = "5"},   {.codePoint = 0x2076, .replacement = "6"},
    {.codePoint = 0x2077, .replacement = "7"},   {.codePoint = 0x2078, .replacement = "8"},
    {.codePoint = 0x2079, .replacement = "9"},   {.codePoint = 0x2080, .replacement = "0"},
    {.codePoint = 0x2081, .replacement = "1"},   {.codePoint = 0x2082, .replacement = "2"},
    {.codePoint = 0x2083, .replacement = "3"},   {.codePoint = 0x2084, .replacement = "4"},
    {.codePoint = 0x2085, .replacement = "5"},   {.codePoint = 0x2086, .replacement = "6"},
    {.codePoint = 0x2087, .replacement = "7"},   {.codePoint = 0x2088, .replacement = "8"},
    {.codePoint = 0x2089, .replacement = "9"},
}};

/// The Kelvin sign, which String.toLowerCase turns into an ASCII 'k'. No other character outside
/// ASCII and the normalization map lower-cases to anything normalize() keeps.
constexpr char32_t kKelvinSign = 0x212A;

/// Stands in for a character that normalize() drops in the end but that still separates two runs
/// of whitespace until then (DEL: neither whitespace nor trimmed).
constexpr char kDropped = '\x7F';

/// Java's regex \s: [ \t\n\x0B\f\r].
[[nodiscard]] bool isRegexSpace(char c) noexcept
{
    return c == ' ' || c == '\t' || c == '\n' || c == '\x0B' || c == '\f' || c == '\r';
}

}  // namespace

std::string normalize(std::string_view text)
{
    // unicodeNormalize(text), then toLowerCase(): only ASCII survives the filter below
    std::string mapped;
    mapped.reserve(text.size());
    // Searched through a span: its iterator is a class on every standard library, whereas
    // std::array's is a raw pointer in libstdc++/libc++ and a class in MSVC's STL.
    const std::span<const Normalization> map{kNormalizationMap};
    for (const char32_t c : Strings::toCodePoints(text))
    {
        const auto found = std::ranges::lower_bound(map, c, {}, &Normalization::codePoint);
        if (found != map.end() && found->codePoint == c)
        {
            mapped += found->replacement;
        }
        else if (c < 0x80)
        {
            mapped += static_cast<char>(c);
        }
        else if (c == kKelvinSign)
        {
            mapped += 'k';
        }
        else
        {
            mapped += kDropped;
        }
    }
    mapped = Strings::toLower(mapped);

    // replaceAll("\\s+", " "), then trim()
    std::string collapsed;
    collapsed.reserve(mapped.size());
    bool inWhitespace = false;
    for (const char c : mapped)
    {
        if (isRegexSpace(c))
        {
            if (!inWhitespace)
            {
                collapsed += ' ';
            }
            inWhitespace = true;
        }
        else
        {
            collapsed += c;
            inWhitespace = false;
        }
    }

    std::string key;
    for (const char c : Strings::trim(collapsed))
    {
        if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'))
        {
            key += c;
        }
        else if (c == ' ' || c == '/')  // the fraction slash was mapped to '/' above
        {
            key += '_';
        }
    }

    // replaceAll("^_+", "") and replaceAll("_+$", "")
    const std::size_t first = key.find_first_not_of('_');
    if (first == std::string::npos)
    {
        return {};
    }
    const std::size_t last = key.find_last_not_of('_');
    return key.substr(first, last - first + 1);
}

}  // namespace QtRocket::L10N
