#pragma once

// GENERATED by probes/tier9a-extensions/gen_flight_pins.py (and then formatted with clang-format)
// from the output of ExtPins2.java, the probe of tier 9a, part E, run against OpenRocket
// 5f164fd0e: the flights of the scenarios of ExtensionFlightSupport.h as OpenRocket flies them.
// Do not edit by hand.
//
// Per scenario and time step, the lines the probe printed: the names of the extensions, the
// outcome of the run, the cant of the watched fin set in the caller's rocket before and after
// it, what the probe's listener saw of that fin set in the simulated rocket, the summary of
// the flight data, the warnings, and per branch its size, its events and five of its columns.
// A character outside printable ASCII is written as a backslash, 'u' and four hexadecimal
// digits (the symbols of two flight data types).

#include <array>
#include <span>
#include <string_view>

namespace QtRocket::Test
{

/// The lines ExtPins2 printed for one scenario at one time step.
struct ExtensionFlightPin
{
    std::string_view                  scenario;
    std::span<const std::string_view> lines;

    constexpr ExtensionFlightPin(std::string_view                  scenarioName,
                                 std::span<const std::string_view> scenarioLines)
      : scenario(scenarioName), lines(scenarioLines)
    {
    }
};

namespace ExtensionFlightDetail
{

// SCENARIO haisu-plain dt=0.01
inline constexpr std::array<std::string_view, 23> kStable0{
    "SCENARIO haisu-plain dt=0.01",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1564 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.612822351241 maxVelocity=119.27883750768981 "
    "maxAcceleration=132.0479886463001 maxMach=0.3508482812552055 timeToApogee=11.620051990285784 "
    "flightTime=43.40905478790515 groundHitVelocity=20.1888576397014 "
    "launchRodVelocity=15.752030012900233 deploymentVelocity=NaN optimumDelay=9.660051990285783",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=1564 types=71 optimumAltitude=623.612822351241 "
    "timeToOptimumAltitude=11.660051990285783 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.17600000000000013",
    "    event LAUNCHROD t=0.5640000000000004",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.000270740285987",
    "    event APOGEE t=11.660051990285783",
    "    event TUMBLE t=12.580051990285764",
    "    event GROUND_HIT t=43.40905478790515",
    "    event SIMULATION_END t=43.40905478790515",
    "    column time min=0.0 max=43.40905478790515 last=43.40905478790515 nan=0 first=0 "
    "at150=0.3000000000000002 at300=0.7195855374321913 at600=3.630051990285953 symbol=t",
    "    column altitude min=0.0 max=623.612822351241 last=0.0 nan=0 first=0 "
    "at150=0.23716029596100316 at300=5.869476835503037 at600=288.08577685574164 symbol=h",
    "    column velocity min=0.0 max=119.27883750768981 last=20.1888576397014 nan=0 first=0 "
    "at150=3.2158242077267025 at300=27.817312050826843 at600=90.56799990305949 symbol=Vt",
    "    column rollRate min=0.0 max=3.499112477846138 last=NaN nan=69 first=0 at150=0.0 "
    "at300=0.5739887464014363 at600=2.730925164421979 symbol=d\\u03A6",
};

// SCENARIO haisu-roll dt=0.01
inline constexpr std::array<std::string_view, 25> kStable1{
    "SCENARIO haisu-roll dt=0.01",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1558 cantStart=0.0 cantLast=-0.17783266610274873 cantMaxAbs=0.17783266610274873 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6119804308993 maxVelocity=119.2802840011361 "
    "maxAcceleration=132.04798743735105 maxMach=0.35084928723593933 "
    "timeToApogee=11.619999999999795 flightTime=43.40912224252188 "
    "groundHitVelocity=20.18877789960936 launchRodVelocity=15.752030012900233 "
    "deploymentVelocity=NaN optimumDelay=9.659999999999794",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=1558 types=72 optimumAltitude=623.6119804308993 "
    "timeToOptimumAltitude=11.659999999999794 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.17600000000000013",
    "    event LAUNCHROD t=0.5640000000000004",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.659999999999794",
    "    event TUMBLE t=12.579999999999774",
    "    event GROUND_HIT t=43.40912224252188",
    "    event SIMULATION_END t=43.40912224252188",
    "    column time min=0.0 max=43.40912224252188 last=43.40912224252188 nan=0 first=0 "
    "at150=0.3000000000000002 at300=0.7244233731867645 at600=3.689999999999964 symbol=t",
    "    column altitude min=0.0 max=623.6119804308993 last=0.0 nan=0 first=0 "
    "at150=0.23716029596100316 at300=6.005097432623179 at600=293.4879603054361 symbol=h",
    "    column velocity min=0.0 max=119.2802840011361 last=20.18877789960936 nan=0 first=0 "
    "at150=3.2158242077267025 at300=28.249911486030154 at600=89.66518351897466 symbol=Vt",
    "    column rollRate min=-0.03975219921996995 max=1.2062356379261134 last=NaN nan=69 first=0 "
    "at150=0.0 at300=0.5650053767529161 at600=0.0040896079252640445 symbol=d\\u03A6",
    "    column finCant min=-0.17783266610274873 max=0.0 last=-0.17783266610274873 nan=249 "
    "first=249 at150=NaN at300=-0.015214682138902974 at600=-0.1734828013306399 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-roll-airstart dt=0.01
inline constexpr std::array<std::string_view, 27> kStable2{
    "SCENARIO haisu-roll-airstart dt=0.01",
    "  extensions=Roll Control|Air-start (100 m, 50 m/s)",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1657 cantStart=0.0 cantLast=-0.17924588627873814 cantMaxAbs=0.21936481178861883 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=1072.5461730979384 maxVelocity=160.98610308377974 "
    "maxAcceleration=127.63781372044748 maxMach=0.47451848499136257 "
    "timeToApogee=13.505997920347527 flightTime=66.68065717473351 "
    "groundHitVelocity=20.188776475022937 launchRodVelocity=49.61961360283116 "
    "deploymentVelocity=NaN optimumDelay=11.545997920347526",
    "  warning HIGH No recovery device defined in the simulation.",
    "  warning LOW Listeners modified the flight simulation",
    "  branch 0 rows=1657 types=72 optimumAltitude=1072.5461730979384 "
    "timeToOptimumAltitude=13.545997920347526 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.002",
    "    event LAUNCHROD t=0.05200000000000003",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=13.545997920347526",
    "    event TUMBLE t=14.475997920347506",
    "    event GROUND_HIT t=66.68065717473351",
    "    event SIMULATION_END t=66.68065717473351",
    "    column time min=0.0 max=66.68065717473351 last=66.68065717473351 nan=0 first=0 "
    "at150=0.9900172585644784 at300=2.0299999999999994 at600=5.025997920347707 symbol=t",
    "    column altitude min=0.0 max=1072.5461730979384 last=0.0 nan=0 first=0 "
    "at150=165.51056137793634 at300=316.76109574749773 at600=691.5859540176158 symbol=h",
    "    column velocity min=0.037635857286513606 max=160.98610308377974 last=20.188776475022937 "
    "nan=0 first=0 at150=104.99766851881907 at300=157.99205705622293 at600=97.52495839819247 "
    "symbol=Vt",
    "    column rollRate min=-1.3355269544751855 max=1.8339049325097014 last=NaN nan=112 first=0 "
    "at150=1.5884693515168609 at300=-0.3663997707521611 at600=0.004636037924952205 symbol=d\\u03A6",
    "    column finCant min=-0.21936481178861883 max=-0.0017453292519943214 "
    "last=-0.17924588627873814 nan=100 first=100 at150=-0.08900877966396775 "
    "at300=-0.18037875240111523 at600=-0.1730201956327238 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-airstart-250-20 dt=0.01
inline constexpr std::array<std::string_view, 25> kStable3{
    "SCENARIO haisu-airstart-250-20 dt=0.01",
    "  extensions=Air-start (250 m, 20 m/s)",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1514 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=1021.2859198353633 maxVelocity=136.40607784751964 "
    "maxAcceleration=130.657639161422 maxMach=0.4025450141297087 timeToApogee=12.516257009617279 "
    "flightTime=63.26523841511242 groundHitVelocity=20.188858818551974 "
    "launchRodVelocity=19.776505985908063 deploymentVelocity=NaN optimumDelay=10.556257009617278",
    "  warning HIGH No recovery device defined in the simulation.",
    "  warning LOW Listeners modified the flight simulation",
    "  branch 0 rows=1514 types=71 optimumAltitude=1021.2859198353633 "
    "timeToOptimumAltitude=12.556257009617278 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.002",
    "    event LAUNCHROD t=0.12800000000000009",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=12.556257009617278",
    "    event TUMBLE t=13.476257009617258",
    "    event GROUND_HIT t=63.26523841511242",
    "    event SIMULATION_END t=63.26523841511242",
    "    column time min=0.0 max=63.26523841511242 last=63.26523841511242 nan=0 first=0 "
    "at150=0.9609688374973553 at300=2.4062570096174936 at600=5.40625700961743 symbol=t",
    "    column altitude min=0.0 max=1021.2859198353633 last=0.0 nan=0 first=0 "
    "at150=284.2614075924907 at300=459.4439368963172 at600=760.515826393394 symbol=h",
    "    column velocity min=0.04495837181989266 max=136.40607784751964 last=20.188858818551974 "
    "nan=0 first=0 at150=72.88447803981134 at300=126.4560727565429 at600=77.54117908923644 "
    "symbol=Vt",
    "    column rollRate min=0.0 max=3.926479090474582 last=NaN nan=107 first=0 "
    "at150=2.103838546918496 at300=3.6892667141769375 at600=2.359735101769996 symbol=d\\u03A6",
};

// SCENARIO haisu-roll-custom dt=0.01
inline constexpr std::array<std::string_view, 25> kStable4{
    "SCENARIO haisu-roll-custom dt=0.01",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1567 cantStart=0.0 cantLast=0.05 cantMaxAbs=0.05 cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6126843360535 maxVelocity=119.28018930526278 "
    "maxAcceleration=132.04798848265594 maxMach=0.3508511172588966 timeToApogee=11.62155356124266 "
    "flightTime=43.41022076381623 groundHitVelocity=20.18885202691307 "
    "launchRodVelocity=15.752030010370063 deploymentVelocity=NaN optimumDelay=9.661553561242659",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=1567 types=72 optimumAltitude=623.6126843360535 "
    "timeToOptimumAltitude=11.661553561242659 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.17600000000000013",
    "    event LAUNCHROD t=0.5640000000000004",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.661553561242659",
    "    event TUMBLE t=12.57155356124264",
    "    event GROUND_HIT t=43.41022076381623",
    "    event SIMULATION_END t=43.41022076381623",
    "    column time min=0.0 max=43.41022076381623 last=43.41022076381623 nan=0 first=0 "
    "at150=0.3000000000000002 at300=0.692103957657845 at600=3.59155356124283 symbol=t",
    "    column altitude min=0.0 max=623.6126843360535 last=0.0 nan=0 first=0 "
    "at150=0.23716029596092242 at300=5.138126411655768 at600=284.5878234373228 symbol=h",
    "    column velocity min=0.0 max=119.28018930526278 last=20.18885202691307 nan=0 first=0 "
    "at150=3.21582420772109 at300=25.426237319903603 at600=91.1512449107989 symbol=Vt",
    "    column rollRate min=0.0 max=2.4799006009196165 last=NaN nan=69 first=0 at150=0.0 "
    "at300=0.5904038361757769 at600=1.955150482704651 symbol=d\\u03A6",
    "    column finCant min=-0.05 max=0.05 last=0.05 nan=124 first=124 at150=0.015400000000000002 "
    "at300=0.04444416127393741 at600=-0.05 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-roll-nojitter dt=0.01
inline constexpr std::array<std::string_view, 26> kStable5{
    "SCENARIO haisu-roll-nojitter dt=0.01",
    "  extensions=Roll Control",
    "  jitterReplacements=5956",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1558 cantStart=0.0 cantLast=-0.17783225097523997 cantMaxAbs=0.17783225097523997 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6119804738923 maxVelocity=119.28028400254355 "
    "maxAcceleration=132.04798743735012 maxMach=0.3508492872400802 timeToApogee=11.619999999999795 "
    "flightTime=43.409121652868194 groundHitVelocity=20.1887778998587 "
    "launchRodVelocity=15.752030012900233 deploymentVelocity=NaN optimumDelay=9.659999999999794",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=1558 types=72 optimumAltitude=623.6119804738923 "
    "timeToOptimumAltitude=11.659999999999794 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.17600000000000013",
    "    event LAUNCHROD t=0.5640000000000004",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.659999999999794",
    "    event TUMBLE t=12.579999999999774",
    "    event GROUND_HIT t=43.409121652868194",
    "    event SIMULATION_END t=43.409121652868194",
    "    column time min=0.0 max=43.409121652868194 last=43.409121652868194 nan=0 first=0 "
    "at150=0.3000000000000002 at300=0.7244233731867645 at600=3.689999999999964 symbol=t",
    "    column altitude min=0.0 max=623.6119804738923 last=0.0 nan=0 first=0 "
    "at150=0.23716029596100316 at300=6.005097432623179 at600=293.487960309927 symbol=h",
    "    column velocity min=0.0 max=119.28028400254355 last=20.1887778998587 nan=0 first=0 "
    "at150=3.2158242077267025 at300=28.249911486030154 at600=89.66518352223174 symbol=Vt",
    "    column rollRate min=-0.03975219922106886 max=1.2062356379261288 last=NaN nan=69 first=0 "
    "at150=0.0 at300=0.5650053767529161 at600=0.004089607924234072 symbol=d\\u03A6",
    "    column finCant min=-0.17783225097523997 max=0.0 last=-0.17783225097523997 nan=249 "
    "first=249 at150=NaN at300=-0.015214682138902955 at600=-0.17348280133048097 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-plain-nojitter dt=0.01
inline constexpr std::array<std::string_view, 24> kStable6{
    "SCENARIO haisu-plain-nojitter dt=0.01",
    "  extensions=",
    "  jitterReplacements=5980",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1564 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6128223778694 maxVelocity=119.27883750869643 "
    "maxAcceleration=132.04798864629964 maxMach=0.3508482812581695 timeToApogee=11.620051990285745 "
    "flightTime=43.40905363892521 groundHitVelocity=20.188857639861943 "
    "launchRodVelocity=15.752030012900233 deploymentVelocity=NaN optimumDelay=9.660051990285744",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=1564 types=71 optimumAltitude=623.6128223778694 "
    "timeToOptimumAltitude=11.660051990285744 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.17600000000000013",
    "    event LAUNCHROD t=0.5640000000000004",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0002707402859485",
    "    event APOGEE t=11.660051990285744",
    "    event TUMBLE t=12.580051990285725",
    "    event GROUND_HIT t=43.40905363892521",
    "    event SIMULATION_END t=43.40905363892521",
    "    column time min=0.0 max=43.40905363892521 last=43.40905363892521 nan=0 first=0 "
    "at150=0.3000000000000002 at300=0.7195855374321916 at600=3.6300519902859145 symbol=t",
    "    column altitude min=0.0 max=623.6128223778694 last=0.0 nan=0 first=0 "
    "at150=0.23716029596100316 at300=5.869476835503037 at600=288.08577685891413 symbol=h",
    "    column velocity min=0.0 max=119.27883750869643 last=20.188857639861943 nan=0 first=0 "
    "at150=3.2158242077267025 at300=27.817312050826843 at600=90.56799990532782 symbol=Vt",
    "    column rollRate min=0.0 max=3.4991124778724227 last=NaN nan=69 first=0 at150=0.0 "
    "at300=0.5739887464014365 at600=2.7309251644851606 symbol=d\\u03A6",
};

// SCENARIO haisu-roll-missing dt=0.01
inline constexpr std::array<std::string_view, 7> kStable7{
    "SCENARIO haisu-roll-missing dt=0.01",
    "  extensions=Roll Control",
    "  result=error:A fin set with name 'NOPE' was not found",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=0 cantStart=NaN cantLast=NaN cantMaxAbs=0.0 cantEnd=NaN ends=0",
    "  summary maxAltitude=NaN maxVelocity=NaN maxAcceleration=NaN maxMach=NaN timeToApogee=NaN "
    "flightTime=NaN groundHitVelocity=NaN launchRodVelocity=NaN deploymentVelocity=NaN "
    "optimumDelay=NaN",
    "  warning HIGH No recovery device defined in the simulation.",
};

// SCENARIO alpha-plain dt=0.01
inline constexpr std::array<std::string_view, 21> kStable8{
    "SCENARIO alpha-plain dt=0.01",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.02 cantAfter=0.02",
    "  spy steps=1787 cantStart=0.02 cantLast=0.02 cantMaxAbs=0.02 cantEnd=0.02 ends=1",
    "  summary maxAltitude=273.5389965417856 maxVelocity=102.92169339089519 "
    "maxAcceleration=271.11724783599675 maxMach=0.3029091152567987 timeToApogee=5.463862807945391 "
    "flightTime=89.32561493093137 groundHitVelocity=3.248399842472286 "
    "launchRodVelocity=18.707017127791758 deploymentVelocity=8.773067359535919 "
    "optimumDelay=3.870781249999989",
    "  branch 0 rows=1787 types=71 optimumAltitude=276.27594341205764 "
    "timeToOptimumAltitude=5.970781249999989 name=Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.054000000000000034",
    "    event LAUNCHROD t=0.17400000000000013",
    "    event BURNOUT t=2.1",
    "    event EJECTION_CHARGE t=5.1",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=5.101",
    "    event APOGEE t=5.463862807945391",
    "    event GROUND_HIT t=89.32561493093137",
    "    event SIMULATION_END t=89.32561493093137",
    "    column time min=0.0 max=89.32561493093137 last=89.32561493093137 nan=0 first=0 "
    "at150=0.20550000000000015 at300=0.29152740773273395 at600=1.161290800239844 symbol=t",
    "    column altitude min=0.0 max=273.5389965417856 last=0.0 nan=0 first=0 "
    "at150=1.7316803522157942 at300=4.908493773858576 at600=71.70744549359767 symbol=h",
    "    column velocity min=0.0 max=102.92169339089519 last=3.248399842472286 nan=0 first=0 "
    "at150=26.723181705191074 at300=45.896650003639415 at600=93.87505127529701 symbol=Vt",
    "    column rollRate min=0.0 max=21.536298329407664 last=NaN nan=512 first=0 "
    "at150=3.5980294473687975 at300=9.28529971544527 at600=19.723223254561752 symbol=d\\u03A6",
};

// SCENARIO alpha-roll dt=0.01
inline constexpr std::array<std::string_view, 23> kStable9{
    "SCENARIO alpha-roll dt=0.01",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.02 cantAfter=0.02",
    "  spy steps=2410 cantStart=0.02 cantLast=-7.928405324847822E-6 cantMaxAbs=0.02 cantEnd=0.02 "
    "ends=1",
    "  summary maxAltitude=273.5439302873224 maxVelocity=102.92999406860258 "
    "maxAcceleration=271.11724783599675 maxMach=0.3029349351394599 timeToApogee=5.463867314224449 "
    "flightTime=89.32763265171124 groundHitVelocity=3.2483798399662094 "
    "launchRodVelocity=18.707017127791758 deploymentVelocity=8.773774370934277 "
    "optimumDelay=3.870781249999989",
    "  branch 0 rows=2410 types=72 optimumAltitude=276.27594341205764 "
    "timeToOptimumAltitude=5.970781249999989 name=Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.054000000000000034",
    "    event LAUNCHROD t=0.17400000000000013",
    "    event BURNOUT t=2.1",
    "    event EJECTION_CHARGE t=5.1",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=5.101",
    "    event APOGEE t=5.463867314224449",
    "    event GROUND_HIT t=89.32763265171124",
    "    event SIMULATION_END t=89.32763265171124",
    "    column time min=0.0 max=89.32763265171124 last=89.32763265171124 nan=0 first=0 "
    "at150=0.20550000000000015 at300=0.29152740773273395 at600=0.7036235608763926 symbol=t",
    "    column altitude min=0.0 max=273.5439302873224 last=0.0 nan=0 first=0 "
    "at150=1.7316803522157942 at300=4.908493773858576 at600=31.85057726864863 symbol=h",
    "    column velocity min=0.0 max=102.92999406860258 last=3.2483798399662094 nan=0 first=0 "
    "at150=26.723181705191074 at300=45.896650003639415 at600=78.23318747721984 symbol=Vt",
    "    column rollRate min=-3.025136940813158 max=14.088226881862854 last=NaN nan=512 first=0 "
    "at150=3.5980294473687975 at300=9.28529971544527 at600=-0.016640931658252443 symbol=d\\u03A6",
    "    column finCant min=-0.00541087219083443 max=2.187015491863807E-4 "
    "last=-7.928405324847822E-6 nan=437 first=437 at150=NaN at300=NaN at600=1.4982833706134917E-4 "
    "symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO beta-plain-boostercant dt=0.01
inline constexpr std::array<std::string_view, 38> kStable10{
    "SCENARIO beta-plain-boostercant dt=0.01",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=2651 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1504279748544 maxVelocity=166.58431486983878 "
    "maxAcceleration=211.09337266597282 maxMach=0.4899555227705794 timeToApogee=7.3763496841166525 "
    "flightTime=169.2831637819861 groundHitVelocity=3.2916745832388963 "
    "launchRodVelocity=11.921156802936135 deploymentVelocity=9.207930301923149 "
    "optimumDelay=3.9107812499999888",
    "  branch 0 rows=2250 types=71 optimumAltitude=542.1831964993822 "
    "timeToOptimumAltitude=7.910781249999989 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09600000000000007",
    "    event LAUNCHROD t=0.2780000000000002",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.0",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001",
    "    event APOGEE t=7.3763496841166525",
    "    event GROUND_HIT t=169.2831637819861",
    "    event SIMULATION_END t=169.2831637819861",
    "    column time min=0.0 max=169.2831637819861 last=169.2831637819861 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5741420615347355 at600=1.1554066638745133 symbol=t",
    "    column altitude min=0.0 max=539.1504279748544 last=0.0 nan=0 first=0 "
    "at150=1.187698458500192 at300=10.15681060613055 at600=75.49715191217976 symbol=h",
    "    column velocity min=0.0 max=166.58431486983878 last=3.2916745832388963 nan=0 first=0 "
    "at150=13.360603769809604 at300=54.45335804797172 at600=161.70276642417463 symbol=Vt",
    "    column rollRate min=0.0 max=16.437315950160183 last=NaN nan=963 first=0 "
    "at150=0.3835327595498491 at300=5.615935273268898 at600=16.0409168972243 symbol=d\\u03A6",
    "  branch 1 rows=1143 types=71 optimumAltitude=231.33655958783893 "
    "timeToOptimumAltitude=3.4560680521815397 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.192675312443567",
    "    event APOGEE t=3.4560680521815397",
    "    event GROUND_HIT t=26.815187882637694",
    "    event SIMULATION_END t=26.815187882637694",
    "    column time min=0.0 max=26.815187882637694 last=26.815187882637694 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5741420615347355 at600=1.1554066638745133 symbol=t",
    "    column altitude min=0.0 max=231.33655958783893 last=0.0 nan=0 first=0 "
    "at150=1.187698458500192 at300=10.15681060613055 at600=75.49715191217976 symbol=h",
    "    column velocity min=0.0 max=166.58431486983878 last=10.151269807898908 nan=0 first=0 "
    "at150=13.360603769809604 at300=54.45335804797172 at600=161.70276642417463 symbol=Vt",
    "    column rollRate min=0.0 max=22.225284872226386 last=NaN nan=103 first=0 "
    "at150=0.3835327595498491 at300=5.615935273268898 at600=16.0409168972243 symbol=d\\u03A6",
};

// SCENARIO beta-roll-sustainer dt=0.01
inline constexpr std::array<std::string_view, 42> kStable11{
    "SCENARIO beta-roll-sustainer dt=0.01",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=5068 cantStart=0.0 cantLast=-0.2617993877991494 cantMaxAbs=0.2617993877991494 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1521187321193 maxVelocity=166.5835495430933 "
    "maxAcceleration=211.0874168132875 maxMach=0.48995505551779456 timeToApogee=7.3766439223631055 "
    "flightTime=169.28395854594547 groundHitVelocity=3.2916745832062024 "
    "launchRodVelocity=11.921156802936135 deploymentVelocity=9.204517064731608 "
    "optimumDelay=3.9107812499999888",
    "  branch 0 rows=4684 types=72 optimumAltitude=542.1831965157189 "
    "timeToOptimumAltitude=7.910781249999989 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09600000000000007",
    "    event LAUNCHROD t=0.2780000000000002",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.000340462870352",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001340462870353",
    "    event APOGEE t=7.3766439223631055",
    "    event GROUND_HIT t=169.28395854594547",
    "    event SIMULATION_END t=169.28395854594547",
    "    column time min=0.0 max=169.28395854594547 last=169.28395854594547 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5593956091988331 at600=0.8230144309750237 symbol=t",
    "    column altitude min=0.0 max=539.1521187321193 last=0.0 nan=0 first=0 "
    "at150=1.187698458500192 at300=9.373858030392 at600=29.863750223636327 symbol=h",
    "    column velocity min=0.0 max=166.5835495430933 last=3.2916745832062024 nan=0 first=0 "
    "at150=13.360603769809604 at300=51.74328599142284 at600=104.98132078830821 symbol=Vt",
    "    column rollRate min=-19.74425328033713 max=14.693382453739764 last=NaN nan=963 first=0 "
    "at150=0.3835327595498491 at300=3.092316416114248 at600=-0.2865466076021403 symbol=d\\u03A6",
    "    column finCant min=-0.029865758463486203 max=0.015449760906628878 "
    "last=-1.2120407826312044E-6 nan=259 first=259 at150=NaN at300=-0.010527057184955998 "
    "at600=-0.02109144858942323 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
    "  branch 1 rows=1743 types=72 optimumAltitude=233.29946533453906 "
    "timeToOptimumAltitude=3.5671071682721864 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.1492969383910414",
    "    event APOGEE t=3.5671071682721864",
    "    event GROUND_HIT t=27.085215816583705",
    "    event SIMULATION_END t=27.085215816583705",
    "    column time min=0.0 max=27.085215816583705 last=27.085215816583705 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5593956091988331 at600=0.8230144309750237 symbol=t",
    "    column altitude min=0.0 max=233.29946533453906 last=0.0 nan=0 first=0 "
    "at150=1.187698458500192 at300=9.373858030392 at600=29.863750223636327 symbol=h",
    "    column velocity min=0.0 max=166.5835495430933 last=10.15126981944781 nan=0 first=0 "
    "at150=13.360603769809604 at300=51.74328599142284 at600=104.98132078830821 symbol=Vt",
    "    column rollRate min=-3.489540674966128 max=22.065326212779695 last=NaN nan=116 first=0 "
    "at150=0.3835327595498491 at300=3.092316416114248 at600=-0.2865466076021403 symbol=d\\u03A6",
    "    column finCant min=-0.2617993877991494 max=-3.291711261527146E-4 last=-0.2617993877991494 "
    "nan=259 first=259 at150=NaN at300=-0.010527057184955998 at600=-0.02109144858942323 "
    "symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO beta-plain-sustainercant dt=0.01
inline constexpr std::array<std::string_view, 38> kStable12{
    "SCENARIO beta-plain-sustainercant dt=0.01",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=3246 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1448003377078 maxVelocity=166.58431486983747 "
    "maxAcceleration=211.09337266596907 maxMach=0.4899555227705739 timeToApogee=7.3763444064640495 "
    "flightTime=169.2805240566696 groundHitVelocity=3.2916943227666238 "
    "launchRodVelocity=11.921156802936133 deploymentVelocity=9.207405523968466 "
    "optimumDelay=3.9107812499999888",
    "  branch 0 rows=2901 types=71 optimumAltitude=542.1771595573969 "
    "timeToOptimumAltitude=7.910781249999989 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09600000000000007",
    "    event LAUNCHROD t=0.2780000000000002",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.0",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001",
    "    event APOGEE t=7.3763444064640495",
    "    event GROUND_HIT t=169.2805240566696",
    "    event SIMULATION_END t=169.2805240566696",
    "    column time min=0.0 max=169.2805240566696 last=169.2805240566696 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5741420615347357 at600=1.1554066638745428 symbol=t",
    "    column altitude min=0.0 max=539.1448003377078 last=0.0 nan=0 first=0 "
    "at150=1.1876984585001915 at300=10.156810606130545 at600=75.4971519121845 symbol=h",
    "    column velocity min=0.0 max=166.58431486983747 last=3.2916943227666238 nan=0 first=0 "
    "at150=13.360603769809602 at300=54.453358047971705 at600=161.7027664241763 symbol=Vt",
    "    column rollRate min=0.0 max=28.52714900486186 last=NaN nan=963 first=0 "
    "at150=0.3835327595498491 at300=5.615935273268893 at600=16.040916897224378 symbol=d\\u03A6",
    "  branch 1 rows=1087 types=71 optimumAltitude=231.00979345619882 "
    "timeToOptimumAltitude=3.46743088447675 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.1739063405601065",
    "    event APOGEE t=3.46743088447675",
    "    event GROUND_HIT t=26.79015028757339",
    "    event SIMULATION_END t=26.79015028757339",
    "    column time min=0.0 max=26.79015028757339 last=26.79015028757339 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5741420615347357 at600=1.1554066638745428 symbol=t",
    "    column altitude min=0.0 max=231.00979345619882 last=0.0 nan=0 first=0 "
    "at150=1.1876984585001915 at300=10.156810606130545 at600=75.4971519121845 symbol=h",
    "    column velocity min=0.0 max=166.58431486983747 last=10.15134210118694 nan=0 first=0 "
    "at150=13.360603769809602 at300=54.453358047971705 at600=161.7027664241763 symbol=Vt",
    "    column rollRate min=0.0 max=16.437315950157586 last=NaN nan=106 first=0 "
    "at150=0.3835327595498491 at300=5.615935273268893 at600=16.040916897224378 symbol=d\\u03A6",
};

// SCENARIO beta-roll-booster dt=0.01
inline constexpr std::array<std::string_view, 42> kStable13{
    "SCENARIO beta-roll-booster dt=0.01",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=3938 cantStart=0.0 cantLast=0.2617993877991494 cantMaxAbs=0.2617993877991494 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1432282325122 maxVelocity=166.58356280406284 "
    "maxAcceleration=211.08741681329536 maxMach=0.4899550120907969 timeToApogee=7.376384038916199 "
    "flightTime=169.28009828837503 groundHitVelocity=3.291694322803939 "
    "launchRodVelocity=11.921156802936133 deploymentVelocity=9.206903108067719 "
    "optimumDelay=3.9107812499999888",
    "  branch 0 rows=3523 types=72 optimumAltitude=542.1771595573965 "
    "timeToOptimumAltitude=7.910781249999989 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09600000000000007",
    "    event LAUNCHROD t=0.2780000000000002",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.000046467414843",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001046467414843",
    "    event APOGEE t=7.376384038916199",
    "    event GROUND_HIT t=169.28009828837503",
    "    event SIMULATION_END t=169.28009828837503",
    "    column time min=0.0 max=169.28009828837503 last=169.28009828837503 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5593956091988334 at600=0.823014430972789 symbol=t",
    "    column altitude min=0.0 max=539.1432282325122 last=0.0 nan=0 first=0 "
    "at150=1.1876984585001915 at300=9.373858030392013 at600=29.86375022340175 symbol=h",
    "    column velocity min=0.0 max=166.58356280406284 last=3.291694322803939 nan=0 first=0 "
    "at150=13.360603769809602 at300=51.74328599142289 at600=104.98132078783692 symbol=Vt",
    "    column rollRate min=-3.489540674966134 max=28.52708580368429 last=NaN nan=963 first=0 "
    "at150=0.3835327595498491 at300=3.092316416114243 at600=-0.2865466075007237 symbol=d\\u03A6",
    "    column finCant min=-0.2617993877991494 max=-3.2917112615270494E-4 "
    "last=-0.2617993877991494 nan=259 first=259 at150=NaN at300=-0.010527057184956008 "
    "at600=-0.021091448588614774 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
    "  branch 1 rows=1774 types=72 optimumAltitude=232.26097827030773 "
    "timeToOptimumAltitude=3.5197762460555775 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.1690556197780295",
    "    event APOGEE t=3.5197762460555775",
    "    event GROUND_HIT t=27.004454264500946",
    "    event SIMULATION_END t=27.004454264500946",
    "    column time min=0.0 max=27.004454264500946 last=27.004454264500946 nan=0 first=0 "
    "at150=0.2928172266237593 at300=0.5593956091988334 at600=0.823014430972789 symbol=t",
    "    column altitude min=0.0 max=232.26097827030773 last=0.0 nan=0 first=0 "
    "at150=1.1876984585001915 at300=9.373858030392013 at600=29.86375022340175 symbol=h",
    "    column velocity min=0.0 max=166.58356280406284 last=10.12696995810431 nan=0 first=0 "
    "at150=13.360603769809602 at300=51.74328599142289 at600=104.98132078783692 symbol=Vt",
    "    column rollRate min=-29.877662243630787 max=4.292239350708315 last=NaN nan=108 first=0 "
    "at150=0.3835327595498491 at300=3.092316416114243 at600=-0.2865466075007237 symbol=d\\u03A6",
    "    column finCant min=-0.029865758463486214 max=0.2617993877991494 last=0.2617993877991494 "
    "nan=259 first=259 at150=NaN at300=-0.010527057184956008 at600=-0.021091448588614774 "
    "symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-plain dt=0.05
inline constexpr std::array<std::string_view, 23> kDefault0{
    "SCENARIO haisu-plain dt=0.05",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=443 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6106969818493 maxVelocity=119.26775742594975 "
    "maxAcceleration=132.04797950443802 maxMach=0.3508073147724727 timeToApogee=11.592012608909583 "
    "flightTime=43.401635921479674 groundHitVelocity=20.188859219844066 "
    "launchRodVelocity=16.15177859702644 deploymentVelocity=NaN optimumDelay=9.642012608909583",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=443 types=71 optimumAltitude=623.6106969818493 "
    "timeToOptimumAltitude=11.642012608909583 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.18000000000000002",
    "    event LAUNCHROD t=0.5700000000000003",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.642012608909583",
    "    event TUMBLE t=12.642012608909598",
    "    event GROUND_HIT t=43.401635921479674",
    "    event SIMULATION_END t=43.401635921479674",
    "    column time min=0.0 max=43.401635921479674 last=43.401635921479674 nan=0 first=0 "
    "at150=1.5502156374200593 at300=8.892012608909544 at600=none symbol=t",
    "    column altitude min=0.0 max=623.6106969818493 last=0.0 nan=0 first=0 "
    "at150=66.23355362931567 at300=586.9388822054573 at600=none symbol=h",
    "    column velocity min=0.0 max=119.26775742594975 last=20.188859219844066 nan=0 first=0 "
    "at150=110.29771105742104 at300=27.122718120190342 at600=none symbol=Vt",
    "    column rollRate min=0.0 max=3.4979071426153916 last=NaN nan=68 first=0 "
    "at150=3.2358357971176206 at300=0.8626628151921996 at600=none symbol=d\\u03A6",
};

// SCENARIO haisu-roll dt=0.05
inline constexpr std::array<std::string_view, 25> kDefault1{
    "SCENARIO haisu-roll dt=0.05",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=431 cantStart=0.0 cantLast=-0.17783189138123462 cantMaxAbs=0.17783189138123462 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6125477404939 maxVelocity=119.28073652141711 "
    "maxAcceleration=132.04797832008825 maxMach=0.3508514972630304 timeToApogee=11.608571307860823 "
    "flightTime=43.40576885922882 groundHitVelocity=20.188778091387427 "
    "launchRodVelocity=16.15177859702644 deploymentVelocity=NaN optimumDelay=9.658571307860823",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=431 types=72 optimumAltitude=623.6125477404939 "
    "timeToOptimumAltitude=11.658571307860823 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.18000000000000002",
    "    event LAUNCHROD t=0.5700000000000003",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.658571307860823",
    "    event TUMBLE t=12.608571307860837",
    "    event GROUND_HIT t=43.40576885922882",
    "    event SIMULATION_END t=43.40576885922882",
    "    column time min=0.0 max=43.40576885922882 last=43.40576885922882 nan=0 first=0 at150=2.0 "
    "at300=9.458571307860792 at600=none symbol=t",
    "    column altitude min=0.0 max=623.6125477404939 last=0.0 nan=0 first=0 "
    "at150=118.83547654313513 at300=600.6684077993573 at600=none symbol=h",
    "    column velocity min=0.0 max=119.28073652141711 last=20.188778091387427 nan=0 first=0 "
    "at150=118.1804422039979 at300=21.362078868667417 at600=none symbol=Vt",
    "    column rollRate min=-0.049441648385483955 max=1.2621064713993848 last=NaN nan=68 first=0 "
    "at150=0.006658412351382729 at300=6.471373010479052E-4 at600=none symbol=d\\u03A6",
    "    column finCant min=-0.17783189138123462 max=0.0 last=-0.17783189138123462 nan=49 first=49 "
    "at150=-0.17156030467821037 at300=-0.17566876992390051 at600=none symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-roll-airstart dt=0.05
inline constexpr std::array<std::string_view, 27> kDefault2{
    "SCENARIO haisu-roll-airstart dt=0.05",
    "  extensions=Roll Control|Air-start (100 m, 50 m/s)",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=605 cantStart=0.0 cantLast=-0.17921763702963653 cantMaxAbs=0.21884402593109029 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=1072.7525229211385 maxVelocity=161.01173641544392 "
    "maxAcceleration=127.63420019000668 maxMach=0.47459317122945527 "
    "timeToApogee=13.525799312761315 flightTime=66.68490878796467 "
    "groundHitVelocity=20.188777611213148 launchRodVelocity=49.637685859410546 "
    "deploymentVelocity=NaN optimumDelay=11.525799312761315",
    "  warning HIGH No recovery device defined in the simulation.",
    "  warning LOW Listeners modified the flight simulation",
    "  branch 0 rows=605 types=72 optimumAltitude=1072.7525229211385 "
    "timeToOptimumAltitude=13.525799312761315 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.0049999999999999975",
    "    event LAUNCHROD t=0.055189991995073934",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=13.525799312761315",
    "    event TUMBLE t=14.525799312761329",
    "    event GROUND_HIT t=66.68490878796467",
    "    event SIMULATION_END t=66.68490878796467",
    "    column time min=0.0 max=66.68490878796467 last=66.68490878796467 nan=0 first=0 "
    "at150=1.5403852571246233 at300=4.825799312761248 at600=64.85810282858213 symbol=t",
    "    column altitude min=0.0 max=1072.7525229211385 last=0.0 nan=0 first=0 "
    "at150=238.87880524063894 at300=671.8547444344957 at600=36.912803732149584 symbol=h",
    "    column velocity min=0.14707451123897422 max=161.01173641544392 last=20.188777611213148 "
    "nan=0 first=0 at150=153.97978136911345 at300=100.73383588593134 at600=20.22366812941715 "
    "symbol=Vt",
    "    column rollRate min=-1.327999273357647 max=1.8540717303398528 last=NaN nan=111 first=0 "
    "at150=-0.34992847622826145 at300=0.00493289342917438 at600=NaN symbol=d\\u03A6",
    "    column finCant min=-0.21884402593109029 max=-0.004195490723267946 "
    "last=-0.17921763702963653 nan=53 first=53 at150=-0.18610717954234118 "
    "at300=-0.1728883849074747 at600=-0.179133477711559 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-airstart-250-20 dt=0.05
inline constexpr std::array<std::string_view, 25> kDefault3{
    "SCENARIO haisu-airstart-250-20 dt=0.05",
    "  extensions=Air-start (250 m, 20 m/s)",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=470 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=1021.8128384188075 maxVelocity=136.4532984634544 "
    "maxAcceleration=130.65150135448542 maxMach=0.4026764264192655 timeToApogee=12.530757566223258 "
    "flightTime=63.28635833406356 groundHitVelocity=20.188858137165976 "
    "launchRodVelocity=19.863092427998065 deploymentVelocity=NaN optimumDelay=10.530757566223258",
    "  warning HIGH No recovery device defined in the simulation.",
    "  warning LOW Listeners modified the flight simulation",
    "  branch 0 rows=470 types=71 optimumAltitude=1021.8128384188075 "
    "timeToOptimumAltitude=12.530757566223258 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.01",
    "    event LAUNCHROD t=0.12999999999999998",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=12.530757566223258",
    "    event TUMBLE t=13.530757566223272",
    "    event GROUND_HIT t=63.28635833406356",
    "    event SIMULATION_END t=63.28635833406356",
    "    column time min=0.0 max=63.28635833406356 last=63.28635833406356 nan=0 first=0 "
    "at150=2.830757566223212 at300=10.330757566223227 at600=none symbol=t",
    "    column altitude min=0.0 max=1021.8128384188075 last=0.0 nan=0 first=0 "
    "at150=511.5351366173755 at300=998.3268648227837 at600=none symbol=h",
    "    column velocity min=0.15852825658655825 max=136.4532984634544 last=20.188858137165976 "
    "nan=0 first=0 at150=118.24147651833762 at300=21.60958547306528 at600=none symbol=Vt",
    "    column rollRate min=0.0 max=3.924538524606525 last=NaN nan=106 first=0 "
    "at150=3.466238152889834 at300=0.6996761661199664 at600=none symbol=d\\u03A6",
};

// SCENARIO haisu-roll-custom dt=0.05
inline constexpr std::array<std::string_view, 25> kDefault4{
    "SCENARIO haisu-roll-custom dt=0.05",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=433 cantStart=0.0 cantLast=0.05 cantMaxAbs=0.05 cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6111285170871 maxVelocity=119.28043527302391 "
    "maxAcceleration=132.04797932879268 maxMach=0.35084975234638843 "
    "timeToApogee=11.639431018369285 flightTime=43.40199638011114 "
    "groundHitVelocity=20.18885285810517 launchRodVelocity=16.15177859419369 "
    "deploymentVelocity=NaN optimumDelay=9.639431018369285",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=433 types=72 optimumAltitude=623.6111285170871 "
    "timeToOptimumAltitude=11.639431018369285 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.18000000000000002",
    "    event LAUNCHROD t=0.5700000000000003",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.639431018369285",
    "    event TUMBLE t=12.639431018369299",
    "    event GROUND_HIT t=43.40199638011114",
    "    event SIMULATION_END t=43.40199638011114",
    "    column time min=0.0 max=43.40199638011114 last=43.40199638011114 nan=0 first=0 "
    "at150=1.923712654420497 at300=9.389431018369253 at600=none symbol=t",
    "    column altitude min=0.0 max=623.6111285170871 last=0.0 nan=0 first=0 "
    "at150=109.77648364340759 at300=599.1678673882832 at600=none symbol=h",
    "    column velocity min=0.0 max=119.28043527302391 last=20.18885285810517 nan=0 first=0 "
    "at150=119.15490585317556 at300=22.060087308258495 at600=none symbol=Vt",
    "    column rollRate min=0.0 max=2.4943968480425913 last=NaN nan=68 first=0 "
    "at150=2.48859337283724 at300=0.509271879004859 at600=none symbol=d\\u03A6",
    "    column finCant min=-0.05 max=0.05 last=0.05 nan=24 first=24 at150=-0.05 at300=-0.05 "
    "at600=none symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-roll-nojitter dt=0.05
inline constexpr std::array<std::string_view, 26> kDefault5{
    "SCENARIO haisu-roll-nojitter dt=0.05",
    "  extensions=Roll Control",
    "  jitterReplacements=1452",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=431 cantStart=0.0 cantLast=-0.17783341982090037 cantMaxAbs=0.17783341982090037 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6125480417772 maxVelocity=119.28073652232817 "
    "maxAcceleration=132.0479783200876 maxMach=0.3508514972657184 timeToApogee=11.608571307798238 "
    "flightTime=43.405768963223025 groundHitVelocity=20.188778089618182 "
    "launchRodVelocity=16.15177859702644 deploymentVelocity=NaN optimumDelay=9.658571307798239",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=431 types=72 optimumAltitude=623.6125480417772 "
    "timeToOptimumAltitude=11.658571307798239 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.18000000000000002",
    "    event LAUNCHROD t=0.5700000000000003",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.658571307798239",
    "    event TUMBLE t=12.608571307798252",
    "    event GROUND_HIT t=43.405768963223025",
    "    event SIMULATION_END t=43.405768963223025",
    "    column time min=0.0 max=43.405768963223025 last=43.405768963223025 nan=0 first=0 "
    "at150=2.0 at300=9.458571307798207 at600=none symbol=t",
    "    column altitude min=0.0 max=623.6125480417772 last=0.0 nan=0 first=0 "
    "at150=118.83547654365937 at300=600.6684080206306 at600=none symbol=h",
    "    column velocity min=0.0 max=119.28073652232817 last=20.188778089618182 nan=0 first=0 "
    "at150=118.18044220725339 at300=21.36207890505965 at600=none symbol=Vt",
    "    column rollRate min=-0.04944164837221005 max=1.2621064713901837 last=NaN nan=68 first=0 "
    "at150=0.006658412529460901 at300=6.471373073060874E-4 at600=none symbol=d\\u03A6",
    "    column finCant min=-0.17783341982090037 max=0.0 last=-0.17783341982090037 nan=49 first=49 "
    "at150=-0.17156030468159866 at300=-0.17566876992349803 at600=none symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO haisu-plain-nojitter dt=0.05
inline constexpr std::array<std::string_view, 24> kDefault6{
    "SCENARIO haisu-plain-nojitter dt=0.05",
    "  extensions=",
    "  jitterReplacements=1500",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=443 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=623.6106972558215 maxVelocity=119.26775742838987 "
    "maxAcceleration=132.04797950443708 maxMach=0.35080731477955673 "
    "timeToApogee=11.592012609215658 flightTime=43.4016310545281 "
    "groundHitVelocity=20.188859220557823 launchRodVelocity=16.15177859702644 "
    "deploymentVelocity=NaN optimumDelay=9.642012609215659",
    "  warning HIGH No recovery device defined in the simulation.",
    "  branch 0 rows=443 types=71 optimumAltitude=623.6106972558215 "
    "timeToOptimumAltitude=11.642012609215659 name=Stage1",
    "    event SIM_WARN t=0.0",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.18000000000000002",
    "    event LAUNCHROD t=0.5700000000000003",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event APOGEE t=11.642012609215659",
    "    event TUMBLE t=12.642012609215673",
    "    event GROUND_HIT t=43.4016310545281",
    "    event SIMULATION_END t=43.4016310545281",
    "    column time min=0.0 max=43.4016310545281 last=43.4016310545281 nan=0 first=0 "
    "at150=1.5502156374054579 at300=8.89201260921562 at600=none symbol=t",
    "    column altitude min=0.0 max=623.6106972558215 last=0.0 nan=0 first=0 "
    "at150=66.23355362799718 at300=586.9388824035591 at600=none symbol=h",
    "    column velocity min=0.0 max=119.26775742838987 last=20.188859220557823 nan=0 first=0 "
    "at150=110.29771105777907 at300=27.122718146101242 at600=none symbol=Vt",
    "    column rollRate min=0.0 max=3.4979071425317265 last=NaN nan=68 first=0 "
    "at150=3.2358357971236873 at300=0.8626628159668426 at600=none symbol=d\\u03A6",
};

// SCENARIO haisu-roll-missing dt=0.05
inline constexpr std::array<std::string_view, 7> kDefault7{
    "SCENARIO haisu-roll-missing dt=0.05",
    "  extensions=Roll Control",
    "  result=error:A fin set with name 'NOPE' was not found",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=0 cantStart=NaN cantLast=NaN cantMaxAbs=0.0 cantEnd=NaN ends=0",
    "  summary maxAltitude=NaN maxVelocity=NaN maxAcceleration=NaN maxMach=NaN timeToApogee=NaN "
    "flightTime=NaN groundHitVelocity=NaN launchRodVelocity=NaN deploymentVelocity=NaN "
    "optimumDelay=NaN",
    "  warning HIGH No recovery device defined in the simulation.",
};

// SCENARIO alpha-plain dt=0.05
inline constexpr std::array<std::string_view, 21> kDefault8{
    "SCENARIO alpha-plain dt=0.05",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.02 cantAfter=0.02",
    "  spy steps=1412 cantStart=0.02 cantLast=0.02 cantMaxAbs=0.02 cantEnd=0.02 ends=1",
    "  summary maxAltitude=273.5518322596265 maxVelocity=102.9217521128351 "
    "maxAcceleration=271.1165041203389 maxMach=0.30290929246142434 timeToApogee=5.465217524781116 "
    "flightTime=89.33087033705708 groundHitVelocity=3.2483998419489604 "
    "launchRodVelocity=18.871876316401984 deploymentVelocity=8.773075553128507 "
    "optimumDelay=3.8715447656222266",
    "  branch 0 rows=1412 types=71 optimumAltitude=276.27723557162574 "
    "timeToOptimumAltitude=5.971544765622227 name=Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.060000000000000005",
    "    event LAUNCHROD t=0.17470265509774352",
    "    event BURNOUT t=2.1",
    "    event EJECTION_CHARGE t=5.1",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=5.101",
    "    event APOGEE t=5.465217524781116",
    "    event GROUND_HIT t=89.33087033705708",
    "    event SIMULATION_END t=89.33087033705708",
    "    column time min=0.0 max=89.33087033705708 last=89.33087033705708 nan=0 first=0 "
    "at150=0.5025054380756176 at300=1.0777651101518113 at600=2.6411258213063142 symbol=t",
    "    column altitude min=0.0 max=273.5518322596265 last=0.0 nan=0 first=0 "
    "at150=17.216745010104272 at300=63.948420265153715 at600=205.61427502250876 symbol=h",
    "    column velocity min=0.0 max=102.9217521128351 last=3.2483998419489604 nan=0 first=0 "
    "at150=66.74885391687043 at300=91.88681866828173 at600=57.663630483837856 symbol=Vt",
    "    column rollRate min=0.0 max=21.535528307336033 last=NaN nan=512 first=0 "
    "at150=14.10179136614668 at300=19.3207408242586 at600=12.4217192331285 symbol=d\\u03A6",
};

// SCENARIO alpha-roll dt=0.05
inline constexpr std::array<std::string_view, 23> kDefault9{
    "SCENARIO alpha-roll dt=0.05",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.02 cantAfter=0.02",
    "  spy steps=1629 cantStart=0.02 cantLast=1.2529480164467436E-4 cantMaxAbs=0.02 cantEnd=0.02 "
    "ends=1",
    "  summary maxAltitude=273.5569397108099 maxVelocity=102.93028951055808 "
    "maxAcceleration=271.1165041203389 maxMach=0.302935812425859 timeToApogee=5.465222385765122 "
    "flightTime=89.33294122334101 groundHitVelocity=3.2483798394216996 "
    "launchRodVelocity=18.871876316401984 deploymentVelocity=8.773796082049078 "
    "optimumDelay=3.8715447655973194",
    "  branch 0 rows=1629 types=72 optimumAltitude=276.2772355714119 "
    "timeToOptimumAltitude=5.9715447655973195 name=Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.060000000000000005",
    "    event LAUNCHROD t=0.17470265509774352",
    "    event BURNOUT t=2.1",
    "    event EJECTION_CHARGE t=5.1",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=5.101",
    "    event APOGEE t=5.465222385765122",
    "    event GROUND_HIT t=89.33294122334101",
    "    event SIMULATION_END t=89.33294122334101",
    "    column time min=0.0 max=89.33294122334101 last=89.33294122334101 nan=0 first=0 "
    "at150=0.5025000000000002 at300=0.8908085492156116 at600=1.6526745782668428 symbol=t",
    "    column altitude min=0.0 max=273.5569397108099 last=0.0 nan=0 first=0 "
    "at150=17.21638203064218 at300=47.27531476079516 at600=119.81558626831348 symbol=h",
    "    column velocity min=0.0 max=102.93028951055808 last=3.2483798394216996 nan=0 first=0 "
    "at150=66.74850190096666 at300=86.15747327948723 at600=100.8205734442061 symbol=Vt",
    "    column rollRate min=-2.8800072410261017 max=14.06694620447989 last=NaN nan=512 first=0 "
    "at150=10.427806498888044 at300=-0.012435917573944459 at600=-0.0799064992513817 "
    "symbol=d\\u03A6",
    "    column finCant min=-0.005235987755982878 max=5.329080673260017E-4 "
    "last=1.2529480164467436E-4 nan=148 first=148 at150=-0.0013089969389957193 "
    "at300=-1.888149779290666E-4 at600=4.991949726765776E-5 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO beta-plain-boostercant dt=0.05
inline constexpr std::array<std::string_view, 38> kDefault10{
    "SCENARIO beta-plain-boostercant dt=0.05",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=1861 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1594069379893 maxVelocity=166.5846473819054 "
    "maxAcceleration=211.09238589786804 maxMach=0.4899586424217739 timeToApogee=7.377628873541495 "
    "flightTime=169.28710109078787 groundHitVelocity=3.291674582999037 "
    "launchRodVelocity=11.987244976696376 deploymentVelocity=9.207695067048569 "
    "optimumDelay=3.9231445312499975",
    "  branch 0 rows=1682 types=71 optimumAltitude=542.1792117742194 "
    "timeToOptimumAltitude=7.9231445312499975 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09999999999999999",
    "    event LAUNCHROD t=0.2786925815285967",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.0",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001",
    "    event APOGEE t=7.377628873541495",
    "    event GROUND_HIT t=169.28710109078787",
    "    event SIMULATION_END t=169.28710109078787",
    "    column time min=0.0 max=169.28710109078787 last=169.28710109078787 nan=0 first=0 "
    "at150=0.5836925815285952 at300=0.9586925815285872 at600=3.208241022480983 symbol=t",
    "    column altitude min=0.0 max=539.1594069379893 last=0.0 nan=0 first=0 "
    "at150=10.685663109318119 at300=46.03220774374974 at600=333.42292607272935 symbol=h",
    "    column velocity min=0.0 max=166.5846473819054 last=3.291674582999037 nan=0 first=0 "
    "at150=56.234262649714104 at300=133.13272339084418 at600=140.33971291146676 symbol=Vt",
    "    column rollRate min=0.0 max=16.44165874835417 last=NaN nan=963 first=0 "
    "at150=5.8082912248596745 at300=13.546327034693176 at600=0.09866980656703117 symbol=d\\u03A6",
    "  branch 1 rows=706 types=71 optimumAltitude=231.626862325231 "
    "timeToOptimumAltitude=3.47030558431045 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.188749999999996",
    "    event APOGEE t=3.47030558431045",
    "    event GROUND_HIT t=26.85448700846874",
    "    event SIMULATION_END t=26.85448700846874",
    "    column time min=0.0 max=26.85448700846874 last=26.85448700846874 nan=0 first=0 "
    "at150=0.5836925815285952 at300=0.9586925815285872 at600=2.1837499999999963 symbol=t",
    "    column altitude min=0.0 max=231.626862325231 last=0.0 nan=0 first=0 "
    "at150=10.685663109318119 at300=46.03220774374974 at600=216.77962248698844 symbol=h",
    "    column velocity min=0.0 max=166.5846473819054 last=10.151269798247196 nan=0 first=0 "
    "at150=56.234262649714104 at300=133.13272339084418 at600=50.941850709701 symbol=Vt",
    "    column rollRate min=0.0 max=22.22413413504802 last=NaN nan=104 first=0 "
    "at150=5.8082912248596745 at300=13.546327034693176 at600=0.09822030500407841 symbol=d\\u03A6",
};

// SCENARIO beta-roll-sustainer dt=0.05
inline constexpr std::array<std::string_view, 42> kDefault11{
    "SCENARIO beta-roll-sustainer dt=0.05",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=2952 cantStart=0.0 cantLast=-0.2617993877991494 cantMaxAbs=0.2617993877991494 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1697222133349 maxVelocity=166.58343701213363 "
    "maxAcceleration=211.0909044913037 maxMach=0.48995524307182486 timeToApogee=7.378441247231065 "
    "flightTime=169.29096718556744 groundHitVelocity=3.2916745826749185 "
    "launchRodVelocity=11.987244976696376 deploymentVelocity=9.198073571677908 "
    "optimumDelay=3.9231445312499975",
    "  branch 0 rows=2781 types=72 optimumAltitude=542.1669184752378 "
    "timeToOptimumAltitude=7.9231445312499975 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09999999999999999",
    "    event LAUNCHROD t=0.2786925815285967",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.000942675731208",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001942675731208",
    "    event APOGEE t=7.378441247231065",
    "    event GROUND_HIT t=169.29096718556744",
    "    event SIMULATION_END t=169.29096718556744",
    "    column time min=0.0 max=169.29096718556744 last=169.29096718556744 nan=0 first=0 "
    "at150=0.5896316955122092 at300=0.985825176927934 at600=1.7550655033625477 symbol=t",
    "    column altitude min=0.0 max=539.1697222133349 last=0.0 nan=0 first=0 "
    "at150=11.02295739055206 at300=49.71814018530861 at600=170.64223489275665 symbol=h",
    "    column velocity min=0.0 max=166.58343701213363 last=3.2916745826749185 nan=0 first=0 "
    "at150=57.35103938130862 at300=138.55655901751928 at600=139.47216943552223 symbol=Vt",
    "    column rollRate min=-20.161024476505872 max=15.183188324061284 last=NaN nan=963 first=0 "
    "at150=1.8010274258072476 at300=0.036419742431497024 at600=0.037756173430571145 "
    "symbol=d\\u03A6",
    "    column finCant min=-0.029834503594558824 max=0.01597858805209316 "
    "last=0.0016098145418467257 nan=116 first=116 at150=-0.016308201891603074 "
    "at300=-0.01978271126079802 at600=-0.019808014348219983 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
    "  branch 1 rows=864 types=72 optimumAltitude=232.19400546653833 "
    "timeToOptimumAltitude=3.5345877462568187 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.143749999999997",
    "    event APOGEE t=3.5345877462568187",
    "    event GROUND_HIT t=26.953557496077288",
    "    event SIMULATION_END t=26.953557496077288",
    "    column time min=0.0 max=26.953557496077288 last=26.953557496077288 nan=0 first=0 "
    "at150=0.5896316955122092 at300=0.985825176927934 at600=1.7550655033625477 symbol=t",
    "    column altitude min=0.0 max=232.19400546653833 last=0.0 nan=0 first=0 "
    "at150=11.02295739055206 at300=49.71814018530861 at600=170.64223489275665 symbol=h",
    "    column velocity min=0.0 max=166.58343701213363 last=10.151269809428326 nan=0 first=0 "
    "at150=57.35103938130862 at300=138.55655901751928 at600=139.47216943552223 symbol=Vt",
    "    column rollRate min=-3.4637337957520664 max=22.06588566463172 last=NaN nan=114 first=0 "
    "at150=1.8010274258072476 at300=0.036419742431497024 at600=0.037756173430571145 "
    "symbol=d\\u03A6",
    "    column finCant min=-0.2617993877991494 max=-4.363323129985828E-4 last=-0.2617993877991494 "
    "nan=116 first=116 at150=-0.016308201891603074 at300=-0.01978271126079802 "
    "at600=-0.019808014348219983 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

// SCENARIO beta-plain-sustainercant dt=0.05
inline constexpr std::array<std::string_view, 38> kDefault12{
    "SCENARIO beta-plain-sustainercant dt=0.05",
    "  extensions=",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=2718 cantStart=0.0 cantLast=0.0 cantMaxAbs=0.0 cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1575166896301 maxVelocity=166.58464738190327 "
    "maxAcceleration=211.09238589787267 maxMach=0.4899586424217671 timeToApogee=7.377626857111225 "
    "flightTime=169.28557102218338 groundHitVelocity=3.2916943223786137 "
    "launchRodVelocity=11.987244976696372 deploymentVelocity=9.207407640598833 "
    "optimumDelay=3.8952852261710778",
    "  branch 0 rows=2550 types=71 optimumAltitude=542.1763463777307 "
    "timeToOptimumAltitude=7.895285226171078 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09999999999999999",
    "    event LAUNCHROD t=0.2786925815285967",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.0",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001",
    "    event APOGEE t=7.377626857111225",
    "    event GROUND_HIT t=169.28557102218338",
    "    event SIMULATION_END t=169.28557102218338",
    "    column time min=0.0 max=169.28557102218338 last=169.28557102218338 nan=0 first=0 "
    "at150=0.5836925815285952 at300=0.9586925815285872 at600=2.185683324184402 symbol=t",
    "    column altitude min=0.0 max=539.1575166896301 last=0.0 nan=0 first=0 "
    "at150=10.685663109318117 at300=46.032207743749574 at600=220.4763279500498 symbol=h",
    "    column velocity min=0.0 max=166.58464738190327 last=3.2916943223786137 nan=0 first=0 "
    "at150=56.2342626497141 at300=133.13272339084364 at600=95.53227803089052 symbol=Vt",
    "    column rollRate min=0.0 max=28.520525686192876 last=NaN nan=963 first=0 "
    "at150=5.808291224859671 at300=13.546327034693125 at600=20.1374831755065 symbol=d\\u03A6",
    "  branch 1 rows=698 types=71 optimumAltitude=231.5388561022669 "
    "timeToOptimumAltitude=3.533552817420789 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.1490849118239996",
    "    event APOGEE t=3.533552817420789",
    "    event GROUND_HIT t=26.885372216822923",
    "    event SIMULATION_END t=26.885372216822923",
    "    column time min=0.0 max=26.885372216822923 last=26.885372216822923 nan=0 first=0 "
    "at150=0.5836925815285952 at300=0.9586925815285872 at600=2.201325376156994 symbol=t",
    "    column altitude min=0.0 max=231.5388561022669 last=0.0 nan=0 first=0 "
    "at150=10.685663109318117 at300=46.032207743749574 at600=216.81405603611032 symbol=h",
    "    column velocity min=0.0 max=166.58464738190327 last=10.151342096466534 nan=0 first=0 "
    "at150=56.2342626497141 at300=133.13272339084364 at600=42.40900267190434 symbol=Vt",
    "    column rollRate min=-0.043565618373833104 max=16.441658748357952 last=NaN nan=110 first=0 "
    "at150=5.808291224859671 at300=13.546327034693125 at600=NaN symbol=d\\u03A6",
};

// SCENARIO beta-roll-booster dt=0.05
inline constexpr std::array<std::string_view, 42> kDefault13{
    "SCENARIO beta-roll-booster dt=0.05",
    "  extensions=Roll Control",
    "  result=ok",
    "  caller cantBefore=0.0 cantAfter=0.0",
    "  spy steps=2895 cantStart=0.0 cantLast=0.03580576834361675 cantMaxAbs=0.2617993877991494 "
    "cantEnd=0.0 ends=1",
    "  summary maxAltitude=539.1555765445366 maxVelocity=166.58362333918794 "
    "maxAcceleration=211.09090449128996 maxMach=0.48995446042777885 "
    "timeToApogee=7.3776267560151805 flightTime=169.2850082688803 "
    "groundHitVelocity=3.2916943225988824 launchRodVelocity=11.987244976696372 "
    "deploymentVelocity=9.207402848707916 optimumDelay=3.8952852261711435",
    "  branch 0 rows=2718 types=72 optimumAltitude=542.1763463777312 "
    "timeToOptimumAltitude=7.8952852261711435 name=Sustainer Stage",
    "    event LAUNCH t=0.0",
    "    event IGNITION t=0.0",
    "    event LIFTOFF t=0.09999999999999999",
    "    event LAUNCHROD t=0.2786925815285967",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event IGNITION t=2.0",
    "    event BURNOUT t=4.0",
    "    event EJECTION_CHARGE t=7.0",
    "    event RECOVERY_DEVICE_DEPLOYMENT t=7.001",
    "    event APOGEE t=7.378626756015181",
    "    event GROUND_HIT t=169.2850082688803",
    "    event SIMULATION_END t=169.2850082688803",
    "    column time min=0.0 max=169.2850082688803 last=169.2850082688803 nan=0 first=0 "
    "at150=0.5896316955122095 at300=0.9858251769279255 at600=1.7457682032310058 symbol=t",
    "    column altitude min=0.0 max=539.1555765445366 last=0.0 nan=0 first=0 "
    "at150=11.022957390552074 at300=49.71814018530781 at600=169.34122923627987 symbol=h",
    "    column velocity min=0.0 max=166.58362333918794 last=3.2916943225988824 nan=0 first=0 "
    "at150=57.35103938130866 at300=138.55655901752544 at600=140.3933879921792 symbol=Vt",
    "    column rollRate min=-3.463733795752088 max=28.516725186963033 last=NaN nan=964 first=0 "
    "at150=1.8010274258072305 at300=0.036423648058928206 at600=-0.04071305713611248 "
    "symbol=d\\u03A6",
    "    column finCant min=-0.2617993877991494 max=-4.363323129985828E-4 last=-0.2617993877991494 "
    "nan=116 first=116 at150=-0.016308201891603133 at300=-0.01978271095383763 "
    "at600=-0.0202244826366734 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
    "  branch 1 rows=876 types=72 optimumAltitude=233.41099575102862 "
    "timeToOptimumAltitude=3.5633278108329822 name=Booster Stage",
    "    event IGNITION t=0.0",
    "    event BURNOUT t=2.0",
    "    event EJECTION_CHARGE t=2.0",
    "    event STAGE_SEPARATION t=2.0",
    "    event TUMBLE t=2.147499999999997",
    "    event APOGEE t=3.5633278108329822",
    "    event GROUND_HIT t=27.123427855968032",
    "    event SIMULATION_END t=27.123427855968032",
    "    column time min=0.0 max=27.123427855968032 last=27.123427855968032 nan=0 first=0 "
    "at150=0.5896316955122095 at300=0.9858251769279255 at600=1.7457682032310058 symbol=t",
    "    column altitude min=0.0 max=233.41099575102862 last=0.0 nan=0 first=0 "
    "at150=11.022957390552074 at300=49.71814018530781 at600=169.34122923627987 symbol=h",
    "    column velocity min=0.0 max=166.58362333918794 last=10.150679797025768 nan=0 first=0 "
    "at150=57.35103938130866 at300=138.55655901752544 at600=140.3933879921792 symbol=Vt",
    "    column rollRate min=-122.3581823590203 max=4.270169229033705 last=NaN nan=118 first=0 "
    "at150=1.8010274258072305 at300=0.036423648058928206 at600=-0.04071305713611248 "
    "symbol=d\\u03A6",
    "    column finCant min=-0.029834503594558883 max=0.2617993877991494 last=0.03580576834361675 "
    "nan=116 first=116 at150=-0.016308201891603133 at300=-0.01978271095383763 "
    "at600=-0.0202244826366734 symbol=\\u03B1fc",
    "    finCantRows nanAtOrAfterStart=0 valueBeforeStart=1",
};

}  // namespace ExtensionFlightDetail

/// Every scenario of ExtPins2 at a time step of 0.01 s, in its order.
inline constexpr std::array<ExtensionFlightPin, 14> kExtensionFlightStablePins{{
    {"haisu-plain", ExtensionFlightDetail::kStable0},
    {"haisu-roll", ExtensionFlightDetail::kStable1},
    {"haisu-roll-airstart", ExtensionFlightDetail::kStable2},
    {"haisu-airstart-250-20", ExtensionFlightDetail::kStable3},
    {"haisu-roll-custom", ExtensionFlightDetail::kStable4},
    {"haisu-roll-nojitter", ExtensionFlightDetail::kStable5},
    {"haisu-plain-nojitter", ExtensionFlightDetail::kStable6},
    {"haisu-roll-missing", ExtensionFlightDetail::kStable7},
    {"alpha-plain", ExtensionFlightDetail::kStable8},
    {"alpha-roll", ExtensionFlightDetail::kStable9},
    {"beta-plain-boostercant", ExtensionFlightDetail::kStable10},
    {"beta-roll-sustainer", ExtensionFlightDetail::kStable11},
    {"beta-plain-sustainercant", ExtensionFlightDetail::kStable12},
    {"beta-roll-booster", ExtensionFlightDetail::kStable13},
}};

/// Every scenario of ExtPins2 at a time step of 0.05 s, in its order.
inline constexpr std::array<ExtensionFlightPin, 14> kExtensionFlightDefaultPins{{
    {"haisu-plain", ExtensionFlightDetail::kDefault0},
    {"haisu-roll", ExtensionFlightDetail::kDefault1},
    {"haisu-roll-airstart", ExtensionFlightDetail::kDefault2},
    {"haisu-airstart-250-20", ExtensionFlightDetail::kDefault3},
    {"haisu-roll-custom", ExtensionFlightDetail::kDefault4},
    {"haisu-roll-nojitter", ExtensionFlightDetail::kDefault5},
    {"haisu-plain-nojitter", ExtensionFlightDetail::kDefault6},
    {"haisu-roll-missing", ExtensionFlightDetail::kDefault7},
    {"alpha-plain", ExtensionFlightDetail::kDefault8},
    {"alpha-roll", ExtensionFlightDetail::kDefault9},
    {"beta-plain-boostercant", ExtensionFlightDetail::kDefault10},
    {"beta-roll-sustainer", ExtensionFlightDetail::kDefault11},
    {"beta-plain-sustainercant", ExtensionFlightDetail::kDefault12},
    {"beta-roll-booster", ExtensionFlightDetail::kDefault13},
}};
}  // namespace QtRocket::Test
