#include "QtRocket/file/openrocket/AnglePositionSetter.h"

#include <array>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/EllipticalFinSet.h"
#include "QtRocket/rocket/FreeformFinSet.h"
#include "QtRocket/rocket/LaunchLug.h"
#include "QtRocket/rocket/ParallelStage.h"
#include "QtRocket/rocket/PodSet.h"
#include "QtRocket/rocket/RailButton.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "QtRocket/rocket/TrapezoidFinSet.h"
#include "QtRocket/rocket/TubeFinSet.h"
#include "QtRocket/rocket/position/AngleMethod.h"
#include "file/openrocket/SetterTestSupport.h"

// What <angleoffset> does to a component of each class that has the element, as OpenRocket's
// AnglePositionSetter does it. kJava holds OpenRocket's answers (the probe SpecialSetterProbe of
// tier 9b, part R2; see SetterTestSupport.h): the method and the angle in radians
// (getAngleMethod, getAngleOffset) after the elements of a row, and the warnings. The last rows
// apply the setter by hand to a component it is not for, which no file does.
//
// The angles are products of the file's number and Java's degree constant, and what the
// components make of them are sums, differences and whole multiples of pi: the same on every
// platform, so the rows compare exactly.

namespace
{

using QtRocket::AnglePositionSetter;
using QtRocket::ComponentKind;
using QtRocket::EllipticalFinSet;
using QtRocket::FreeformFinSet;
using QtRocket::LaunchLug;
using QtRocket::ParallelStage;
using QtRocket::PodSet;
using QtRocket::RailButton;
using QtRocket::RocketComponent;
using QtRocket::TrapezoidFinSet;
using QtRocket::TubeFinSet;
using QtRocket::Test::ApplicationSetterFixture;
using QtRocket::Test::applyByHand;
using QtRocket::Test::as;
using QtRocket::Test::asText;
using QtRocket::Test::checkSetterScripts;
using QtRocket::Test::listInOrder;
using QtRocket::Test::num;
using QtRocket::Test::SetterScript;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_r2_tests.py of the probe: the readers
[[nodiscard]] std::string readPodSet(ApplicationSetterFixture& /*fixture*/,
                                     const RocketComponent& c)
{
    return listInOrder(
        {asText(angleMethodName(as<PodSet>(c).getAngleMethod())), num(c.getAngleOffset())});
}

[[nodiscard]] std::string readParallelStage(ApplicationSetterFixture& /*fixture*/,
                                            const RocketComponent& c)
{
    return listInOrder(
        {asText(angleMethodName(as<ParallelStage>(c).getAngleMethod())), num(c.getAngleOffset())});
}

[[nodiscard]] std::string readLaunchLug(ApplicationSetterFixture& /*fixture*/,
                                        const RocketComponent& c)
{
    return listInOrder(
        {asText(angleMethodName(as<LaunchLug>(c).getAngleMethod())), num(c.getAngleOffset())});
}

[[nodiscard]] std::string readRailButton(ApplicationSetterFixture& /*fixture*/,
                                         const RocketComponent& c)
{
    return listInOrder(
        {asText(angleMethodName(as<RailButton>(c).getAngleMethod())), num(c.getAngleOffset())});
}

[[nodiscard]] std::string readTrapezoidFinSet(ApplicationSetterFixture& /*fixture*/,
                                              const RocketComponent& c)
{
    return listInOrder({asText(angleMethodName(as<TrapezoidFinSet>(c).getAngleMethod())),
                        num(c.getAngleOffset())});
}

[[nodiscard]] std::string readEllipticalFinSet(ApplicationSetterFixture& /*fixture*/,
                                               const RocketComponent& c)
{
    return listInOrder({asText(angleMethodName(as<EllipticalFinSet>(c).getAngleMethod())),
                        num(c.getAngleOffset())});
}

[[nodiscard]] std::string readFreeformFinSet(ApplicationSetterFixture& /*fixture*/,
                                             const RocketComponent& c)
{
    return listInOrder(
        {asText(angleMethodName(as<FreeformFinSet>(c).getAngleMethod())), num(c.getAngleOffset())});
}

[[nodiscard]] std::string readTubeFinSet(ApplicationSetterFixture& /*fixture*/,
                                         const RocketComponent& c)
{
    return listInOrder(
        {asText(angleMethodName(as<TubeFinSet>(c).getAngleMethod())), num(c.getAngleOffset())});
}

[[nodiscard]] std::string readName(ApplicationSetterFixture& /*fixture*/, const RocketComponent& c)
{
    return c.getName();
}

// ---- generated: OpenRocket's answers, one row per case of the probe
// clang-format off
constexpr auto kJava = std::to_array<SetterScript>({
    {.id = "x276", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.5235987755982988"},
    {.id = "x277", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x278", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readPodSet, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x279", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readPodSet, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x280", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .text = "60"}}}, .read = &readPodSet, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x281", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=bogus", .text = "-90"}}}, .read = &readPodSet, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x282", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method= fixed ", .text = "15"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.2617993877991494"},
    {.id = "x283", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=FIXED", .text = "20"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.3490658503988659"},
    {.id = "x284", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "type=fixed", .text = "25"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.4363323129985824"},
    {.id = "x285", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.PodSet"},
    {.id = "x286", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=  (degrees)  class: info.openrocket.core.rocketcomponent.PodSet"},
    {.id = "x290", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = " 22.5 "}}}, .read = &readPodSet, .expected = "RELATIVE, 0.39269908169872414"},
    {.id = "x291", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "180"}}}, .read = &readPodSet, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x292", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "-180"}}}, .read = &readPodSet, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x293", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "360"}}}, .read = &readPodSet, .expected = "RELATIVE, 6.283185307179586"},
    {.id = "x294", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "720"}}}, .read = &readPodSet, .expected = "RELATIVE, 12.566370614359172"},
    {.id = "x295", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "-720"}}}, .read = &readPodSet, .expected = "RELATIVE, -12.566370614359172"},
    {.id = "x296", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "270"}}}, .read = &readPodSet, .expected = "RELATIVE, 4.71238898038469"},
    {.id = "x297", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "1e18"}}}, .read = &readPodSet, .expected = "RELATIVE, 1.7453292519943296E16"},
    {.id = "x298", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "0"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.0"},
    {.id = "x299", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "-0.0"}}}, .read = &readPodSet, .expected = "RELATIVE, -0.0"},
    {.id = "x300", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "1e-1d"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.0017453292519943296"},
    {.id = "x301", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "PodSet:angleoffset", .attributes = "method=mirrorxy", .text = "40"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.6981317007977318"},
    {.id = "x302", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.5235987755982988", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.PodSet"},
    {.id = "x303", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readParallelStage, .expected = "FIXED, 0.5235987755982988"},
    {.id = "x304", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x305", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readParallelStage, .expected = "MIRROR_XY, 1.5707963267948966"},
    {.id = "x306", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readParallelStage, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x307", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .text = "60"}}}, .read = &readParallelStage, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x308", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=bogus", .text = "-90"}}}, .read = &readParallelStage, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x309", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method= fixed ", .text = "15"}}}, .read = &readParallelStage, .expected = "FIXED, 0.2617993877991494"},
    {.id = "x310", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=FIXED", .text = "20"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.3490658503988659"},
    {.id = "x311", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "type=fixed", .text = "25"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.4363323129985824"},
    {.id = "x312", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.ParallelStage"},
    {.id = "x313", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=  (degrees)  class: info.openrocket.core.rocketcomponent.ParallelStage"},
    {.id = "x317", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = " 22.5 "}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.39269908169872414"},
    {.id = "x318", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "180"}}}, .read = &readParallelStage, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x319", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "-180"}}}, .read = &readParallelStage, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x320", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "360"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0"},
    {.id = "x321", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "720"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0"},
    {.id = "x322", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "-720"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0"},
    {.id = "x323", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "270"}}}, .read = &readParallelStage, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x324", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "1e18"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0"},
    {.id = "x325", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "0"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0"},
    {.id = "x326", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "-0.0"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0"},
    {.id = "x327", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "1e-1d"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0017453292519943296"},
    {.id = "x328", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "ParallelStage:angleoffset", .attributes = "method=mirrorxy", .text = "40"}}}, .read = &readParallelStage, .expected = "MIRROR_XY, 0.6981317007977318"},
    {.id = "x329", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readParallelStage, .expected = "FIXED, 0.5235987755982988", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.ParallelStage"},
    {.id = "x330", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.5235987755982988"},
    {.id = "x331", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x332", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x333", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x334", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .text = "60"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x335", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=bogus", .text = "-90"}}}, .read = &readLaunchLug, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x336", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method= fixed ", .text = "15"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.2617993877991494"},
    {.id = "x337", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=FIXED", .text = "20"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.3490658503988659"},
    {.id = "x338", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "type=fixed", .text = "25"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.4363323129985824"},
    {.id = "x339", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.LaunchLug"},
    {.id = "x340", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=  (degrees)  class: info.openrocket.core.rocketcomponent.LaunchLug"},
    {.id = "x344", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = " 22.5 "}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.39269908169872414"},
    {.id = "x345", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "180"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x346", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "-180"}}}, .read = &readLaunchLug, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x347", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "360"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x348", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "720"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x349", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "-720"}}}, .read = &readLaunchLug, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x350", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "270"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x351", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "1e18"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x352", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "0"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.0"},
    {.id = "x353", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "-0.0"}}}, .read = &readLaunchLug, .expected = "RELATIVE, -0.0"},
    {.id = "x354", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "1e-1d"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.0017453292519943296"},
    {.id = "x355", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "LaunchLug:angleoffset", .attributes = "method=mirrorxy", .text = "40"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.6981317007977318"},
    {.id = "x356", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 0.5235987755982988", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.LaunchLug"},
    {.id = "x357", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.5235987755982988"},
    {.id = "x358", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x359", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readRailButton, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x360", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readRailButton, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x361", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .text = "60"}}}, .read = &readRailButton, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x362", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=bogus", .text = "-90"}}}, .read = &readRailButton, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x363", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method= fixed ", .text = "15"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.2617993877991494"},
    {.id = "x364", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=FIXED", .text = "20"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.3490658503988659"},
    {.id = "x365", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "type=fixed", .text = "25"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.4363323129985824"},
    {.id = "x366", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.RailButton"},
    {.id = "x367", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=  (degrees)  class: info.openrocket.core.rocketcomponent.RailButton"},
    {.id = "x371", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = " 22.5 "}}}, .read = &readRailButton, .expected = "RELATIVE, 0.39269908169872414"},
    {.id = "x372", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "180"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x373", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "-180"}}}, .read = &readRailButton, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x374", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "360"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x375", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "720"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x376", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "-720"}}}, .read = &readRailButton, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x377", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "270"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x378", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "1e18"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x379", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "0"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.0"},
    {.id = "x380", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "-0.0"}}}, .read = &readRailButton, .expected = "RELATIVE, -0.0"},
    {.id = "x381", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "1e-1d"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.0017453292519943296"},
    {.id = "x382", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "RailButton:angleoffset", .attributes = "method=mirrorxy", .text = "40"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.6981317007977318"},
    {.id = "x383", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readRailButton, .expected = "RELATIVE, 0.5235987755982988", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.RailButton"},
    {.id = "x384", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readTrapezoidFinSet, .expected = "FIXED, 0.5235987755982988"},
    {.id = "x385", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x386", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readTrapezoidFinSet, .expected = "MIRROR_XY, 1.5707963267948966"},
    {.id = "x387", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x388", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .text = "60"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x389", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=bogus", .text = "-90"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x390", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method= fixed ", .text = "15"}}}, .read = &readTrapezoidFinSet, .expected = "FIXED, 0.2617993877991494"},
    {.id = "x391", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=FIXED", .text = "20"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.3490658503988659"},
    {.id = "x392", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "type=fixed", .text = "25"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.4363323129985824"},
    {.id = "x393", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    {.id = "x394", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=  (degrees)  class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    {.id = "x398", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = " 22.5 "}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.39269908169872414"},
    {.id = "x399", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "180"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x400", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "-180"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x401", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "360"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x402", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "720"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x403", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "-720"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x404", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "270"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x405", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "1e18"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x406", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "0"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x407", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "-0.0"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x408", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "1e-1d"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0017453292519943296"},
    {.id = "x409", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "FinSet:angleoffset", .attributes = "method=mirrorxy", .text = "40"}}}, .read = &readTrapezoidFinSet, .expected = "MIRROR_XY, 0.6981317007977318"},
    {.id = "x410", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readTrapezoidFinSet, .expected = "FIXED, 0.5235987755982988", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    {.id = "x411", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readEllipticalFinSet, .expected = "FIXED, 0.5235987755982988"},
    {.id = "x412", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readEllipticalFinSet, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x413", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readEllipticalFinSet, .expected = "MIRROR_XY, 1.5707963267948966"},
    {.id = "x414", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readEllipticalFinSet, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x415", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .text = "60"}}}, .read = &readEllipticalFinSet, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x438", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readFreeformFinSet, .expected = "FIXED, 0.5235987755982988"},
    {.id = "x439", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readFreeformFinSet, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x440", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readFreeformFinSet, .expected = "MIRROR_XY, 1.5707963267948966"},
    {.id = "x441", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readFreeformFinSet, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x442", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .text = "60"}}}, .read = &readFreeformFinSet, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x465", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.5235987755982988"},
    {.id = "x466", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "45"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.7853981633974483"},
    {.id = "x467", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=mirrorxy", .text = "90"}}}, .read = &readTubeFinSet, .expected = "MIRROR_XY, 1.5707963267948966"},
    {.id = "x468", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=mirror_xy", .text = "90"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 1.5707963267948966"},
    {.id = "x469", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .text = "60"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 1.0471975511965976"},
    {.id = "x470", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=bogus", .text = "-90"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x471", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method= fixed ", .text = "15"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.2617993877991494"},
    {.id = "x472", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=FIXED", .text = "20"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.3490658503988659"},
    {.id = "x473", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "type=fixed", .text = "25"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.4363323129985824"},
    {.id = "x474", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.0", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    {.id = "x475", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.0", .warnings = "Warning: invalid angle position. value=  (degrees)  class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    {.id = "x479", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = " 22.5 "}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.39269908169872414"},
    {.id = "x480", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "180"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 3.141592653589793"},
    {.id = "x481", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "-180"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, -3.141592653589793"},
    {.id = "x482", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "360"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x483", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "720"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x484", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "-720"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x485", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "270"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, -1.5707963267948966"},
    {.id = "x486", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "1e18"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x487", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "0"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x488", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "-0.0"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.0"},
    {.id = "x489", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "1e-1d"}}}, .read = &readTubeFinSet, .expected = "RELATIVE, 0.0017453292519943296"},
    {.id = "x490", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "TubeFinSet:angleoffset", .attributes = "method=mirrorxy", .text = "40"}}}, .read = &readTubeFinSet, .expected = "MIRROR_XY, 0.6981317007977318"},
    {.id = "x491", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=fixed", .text = "30"}, {.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "xx"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.5235987755982988", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    {.id = "x622", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readName, .expected = "Bulkhead", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AnglePositionSetter is not valid for class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x623", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "xx"}}}, .read = &readName, .expected = "Bulkhead", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x624", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readName, .expected = "Body Tube", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AnglePositionSetter is not valid for class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x625", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "xx"}}}, .read = &readName, .expected = "Body Tube", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x626", .kind = ComponentKind::ROCKET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "30"}}}, .read = &readName, .expected = "Rocket", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AnglePositionSetter is not valid for class: info.openrocket.core.rocketcomponent.Rocket"},
    {.id = "x627", .kind = ComponentKind::ROCKET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=fixed", .text = "xx"}}}, .read = &readName, .expected = "Rocket", .warnings = "Warning: invalid angle position. value=xx  (degrees)  class: info.openrocket.core.rocketcomponent.Rocket"},
});

// What QtRocket answers otherwise than OpenRocket, on purpose: the row has QtRocket's
// answer, the comment above it the reason and OpenRocket's answer.
constexpr auto kOwn = std::to_array<SetterScript>({
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x287", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "NaN"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=NaN  (degrees)  class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, Infinity
    {.id = "x288", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "Infinity"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, -Infinity
    {.id = "x289", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:angleoffset", .attributes = "method=relative", .text = "-Infinity"}}}, .read = &readPodSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=-Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x314", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "NaN"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=NaN  (degrees)  class: info.openrocket.core.rocketcomponent.ParallelStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x315", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "Infinity"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.ParallelStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x316", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:angleoffset", .attributes = "method=relative", .text = "-Infinity"}}}, .read = &readParallelStage, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=-Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.ParallelStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x341", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "NaN"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=NaN  (degrees)  class: info.openrocket.core.rocketcomponent.LaunchLug"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, 3.141592653589793
    {.id = "x342", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "Infinity"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.LaunchLug"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, -3.141592653589793
    {.id = "x343", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "LaunchLug:angleoffset", .attributes = "method=relative", .text = "-Infinity"}}}, .read = &readLaunchLug, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=-Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.LaunchLug"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x368", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "NaN"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=NaN  (degrees)  class: info.openrocket.core.rocketcomponent.RailButton"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, 3.141592653589793
    {.id = "x369", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "Infinity"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.RailButton"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, -3.141592653589793
    {.id = "x370", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RailButton:angleoffset", .attributes = "method=relative", .text = "-Infinity"}}}, .read = &readRailButton, .expected = "RELATIVE, 3.141592653589793", .warnings = "Warning: invalid angle position. value=-Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.RailButton"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x395", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "NaN"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=NaN  (degrees)  class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x396", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "Infinity"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x397", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:angleoffset", .attributes = "method=relative", .text = "-Infinity"}}}, .read = &readTrapezoidFinSet, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid angle position. value=-Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x476", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "NaN"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.0", .warnings = "Warning: invalid angle position. value=NaN  (degrees)  class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x477", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "Infinity"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.0", .warnings = "Warning: invalid angle position. value=Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: RELATIVE, NaN
    {.id = "x478", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:angleoffset", .attributes = "method=relative", .text = "-Infinity"}}}, .read = &readTubeFinSet, .expected = "FIXED, 0.0", .warnings = "Warning: invalid angle position. value=-Infinity  (degrees)  class: info.openrocket.core.rocketcomponent.TubeFinSet"},
});
// clang-format on
// ---- end of the generated part

TEST(AnglePositionSetter, DoesWithEveryElementWhatOpenRocketDoes)
{
    EXPECT_EQ(checkSetterScripts(kJava), Texts{});
}

// OpenRocket stores a NaN, and an infinity as each class makes of it.
TEST(AnglePositionSetter, AnAngleThatIsNotFiniteIsNotApplied)
{
    EXPECT_EQ(checkSetterScripts(kOwn), Texts{});
}

// The cases x303, x306 and x305 of the probe, through a setter of the test's own.
TEST(AnglePositionSetter, SetsTheMethodAndThenTheAngleInRadians)
{
    const AnglePositionSetter setter;
    EXPECT_EQ(applyByHand(setter, ComponentKind::PARALLEL_STAGE, "method=fixed", "30",
                          &readParallelStage),
              "FIXED, 0.5235987755982988");
    // What the saver writes for MIRROR_XY names no method: RELATIVE.
    EXPECT_EQ(applyByHand(setter, ComponentKind::PARALLEL_STAGE, "method=mirror_xy", "90",
                          &readParallelStage),
              "RELATIVE, 1.5707963267948966");
    EXPECT_EQ(applyByHand(setter, ComponentKind::PARALLEL_STAGE, "method=mirrorxy", "90",
                          &readParallelStage),
              "MIRROR_XY, 1.5707963267948966");
}

}  // namespace
