#include "QtRocket/file/openrocket/AxialPositionSetter.h"

#include <array>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/logging/WarningSet.h"
#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/PodSet.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "QtRocket/rocket/position/AxialMethod.h"
#include "QtRocket/util/BugError.h"
#include "QtRocket/util/Error.h"
#include "file/openrocket/SetterTestSupport.h"

// What <axialoffset> and <position> do to a component of each class, as OpenRocket's
// AxialPositionSetter does it. kJava holds OpenRocket's answers (the probe SpecialSetterProbe of
// tier 9b, part R2; see SetterTestSupport.h): a row applies the elements of its steps, in order
// and through the entries of the setter table, to a new component in the tree the probe makes
// (a rocket, a stage, a body tube 0.2 m long), and compares the method, the offset and the
// position (getAxialMethod, getAxialOffset, getPosition.x) and the warnings.

namespace
{

using QtRocket::AxialPositionSetter;
using QtRocket::BugError;
using QtRocket::ComponentKind;
using QtRocket::PodSet;
using QtRocket::Result;
using QtRocket::RocketComponent;
using QtRocket::WarningSet;
using QtRocket::Test::ApplicationSetterFixture;
using QtRocket::Test::applyByHand;
using QtRocket::Test::asText;
using QtRocket::Test::attributesOf;
using QtRocket::Test::checkSetterScripts;
using QtRocket::Test::listInOrder;
using QtRocket::Test::num;
using QtRocket::Test::SetterScript;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_r2_tests.py of the probe: the readers
[[nodiscard]] std::string readAxial(ApplicationSetterFixture& /*fixture*/, const RocketComponent& c)
{
    return listInOrder({asText(axialMethodName(c.getAxialMethod())), num(c.getAxialOffset()),
                        num(c.getPosition().x)});
}

// ---- generated: OpenRocket's answers, one row per case of the probe
// clang-format off
constexpr auto kJava = std::to_array<SetterScript>({
    {.id = "x000", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1"},
    {.id = "x001", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.01"}}}, .read = &readAxial, .expected = "MIDDLE, 0.01, 0.109"},
    {.id = "x002", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=bottom", .text = "-0.02"}}}, .read = &readAxial, .expected = "BOTTOM, -0.02, 0.17800000000000002"},
    {.id = "x003", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "0.05"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.05, 0.05"},
    {.id = "x004", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x005", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "type=top", .text = "0.1"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1"},
    {.id = "x006", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:position", .attributes = "type=bottom", .text = "-0.01"}}}, .read = &readAxial, .expected = "BOTTOM, -0.01, 0.188"},
    {.id = "x007", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:position", .attributes = "method=middle", .text = "0.02"}}}, .read = &readAxial, .expected = "MIDDLE, 0.02, 0.11900000000000001"},
    {.id = "x008", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top|type=bottom", .text = "0.03"}}}, .read = &readAxial, .expected = "TOP, 0.03, 0.03"},
    {.id = "x009", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=bogus|type=middle", .text = "0.03"}}}, .read = &readAxial, .expected = "MIDDLE, 0.03, 0.129"},
    {.id = "x010", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=|type=middle", .text = "0.03"}}}, .read = &readAxial, .expected = "MIDDLE, 0.03, 0.129"},
    {.id = "x011", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .text = "0.03"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x012", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=bogus", .text = "0.03"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x013", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "type=bogus", .text = "0.03"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x014", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method= top ", .text = "0.03"}}}, .read = &readAxial, .expected = "TOP, 0.03, 0.03"},
    {.id = "x015", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=TOP", .text = "0.03"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x016", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=Top", .text = "0.03"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x017", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "relativeto=top", .text = "0.03"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x018", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = " 0.04 "}}}, .read = &readAxial, .expected = "TOP, 0.04, 0.04"},
    {.id = "x019", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "abc"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x020", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = " x y "}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value= x y     class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x021", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x022", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = " "}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=     class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x026", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "1e-1d"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1"},
    {.id = "x027", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0x1p-3"}}}, .read = &readAxial, .expected = "TOP, 0.125, 0.125"},
    {.id = "x029", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0,5"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=0,5    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x030", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "+0.05"}}}, .read = &readAxial, .expected = "TOP, 0.05, 0.05"},
    {.id = "x031", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "-0.0"}}}, .read = &readAxial, .expected = "TOP, -0.0, 0.0"},
    {.id = "x032", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0"}}}, .read = &readAxial, .expected = "TOP, 0.0, 0.0"},
    {.id = "x033", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "1e-7"}}}, .read = &readAxial, .expected = "TOP, 1.0E-7, 0.0"},
    {.id = "x034", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "-1e-7"}}}, .read = &readAxial, .expected = "TOP, -1.0E-7, 0.0"},
    {.id = "x035", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "1e-6"}}}, .read = &readAxial, .expected = "TOP, 1.0E-6, 1.0E-6"},
    {.id = "x036", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "auto 0.1"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=auto 0.1    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x041", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "abc"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x042", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "abc"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x043", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x044", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:position", .attributes = "type=top", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x045", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "abc"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x046", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:axialoffset", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x047", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x048", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.NoseCone"},
    {.id = "x049", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:position", .attributes = "type=top", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.NoseCone"},
    {.id = "x050", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "abc"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.NoseCone"},
    {.id = "x051", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:axialoffset", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x052", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.NoseCone"},
    {.id = "x053", .kind = ComponentKind::TRANSITION, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.Transition"},
    {.id = "x054", .kind = ComponentKind::TRANSITION, .steps = {{{.key = "RocketComponent:position", .attributes = "type=top", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.Transition"},
    {.id = "x055", .kind = ComponentKind::TRANSITION, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "abc"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.Transition"},
    {.id = "x056", .kind = ComponentKind::TRANSITION, .steps = {{{.key = "RocketComponent:axialoffset", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Invalid parameter encountered, ignoring."},
    {.id = "x057", .kind = ComponentKind::TRANSITION, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.2", .warnings = "Warning: info.openrocket.core.file.openrocket.importt.AxialPositionSetter is not valid for class: info.openrocket.core.rocketcomponent.Transition"},
    {.id = "x058", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.0, 0.0"},
    {.id = "x059", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.01"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.0, 0.0"},
    {.id = "x060", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=bottom", .text = "0.01"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.0, 0.0"},
    {.id = "x061", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "0.05"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.0, 0.0"},
    {.id = "x062", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.1"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.0, 0.0"},
    {.id = "x065", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x066", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.01"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x067", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=bottom", .text = "0.01"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x068", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "0.05"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x069", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.1"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x072", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1"},
    {.id = "x073", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.01"}}}, .read = &readAxial, .expected = "MIDDLE, 0.009999999999999995, 0.11"},
    {.id = "x074", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=bottom", .text = "0.01"}}}, .read = &readAxial, .expected = "BOTTOM, 0.010000000000000009, 0.21000000000000002"},
    {.id = "x075", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "0.05"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.05, 0.05"},
    {.id = "x076", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.1"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1"},
    {.id = "x079", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1"},
    {.id = "x080", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.01"}}}, .read = &readAxial, .expected = "MIDDLE, 0.009999999999999995, 0.11"},
    {.id = "x081", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=bottom", .text = "0.01"}}}, .read = &readAxial, .expected = "BOTTOM, 0.010000000000000009, 0.21000000000000002"},
    {.id = "x082", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "0.05"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.05, 0.05"},
    {.id = "x083", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.1"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1"},
    {.id = "x086", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x087", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.07700000000000001"},
    {.id = "x088", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x089", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x090", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x091", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.07700000000000001"},
    {.id = "x092", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x093", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x094", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x095", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.07700000000000001"},
    {.id = "x096", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x097", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x098", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x099", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.052000000000000005"},
    {.id = "x100", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x101", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x102", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x103", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.08700000000000001"},
    {.id = "x104", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x105", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x106", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x107", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.10200000000000001"},
    {.id = "x108", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x109", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x110", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x111", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.067"},
    {.id = "x112", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x113", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x114", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x115", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.07200000000000001"},
    {.id = "x116", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x117", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x118", .kind = ComponentKind::ENGINE_BLOCK, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x119", .kind = ComponentKind::ENGINE_BLOCK, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.0995"},
    {.id = "x120", .kind = ComponentKind::ENGINE_BLOCK, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x121", .kind = ComponentKind::ENGINE_BLOCK, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x122", .kind = ComponentKind::CENTERING_RING, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x123", .kind = ComponentKind::CENTERING_RING, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.101"},
    {.id = "x124", .kind = ComponentKind::CENTERING_RING, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x125", .kind = ComponentKind::CENTERING_RING, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x126", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x127", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.101"},
    {.id = "x128", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x129", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0"},
    {.id = "x130", .kind = ComponentKind::MASS_COMPONENT, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x131", .kind = ComponentKind::MASS_COMPONENT, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.08950000000000001"},
    {.id = "x132", .kind = ComponentKind::MASS_COMPONENT, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x133", .kind = ComponentKind::MASS_COMPONENT, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x134", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x135", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.08950000000000001"},
    {.id = "x136", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x137", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x138", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x139", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.08950000000000001"},
    {.id = "x140", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x141", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x142", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.01"}}}, .read = &readAxial, .expected = "TOP, 0.01, 0.01"},
    {.id = "x143", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0.002"}}}, .read = &readAxial, .expected = "MIDDLE, 0.002, 0.08950000000000001"},
    {.id = "x144", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RocketComponent:position", .attributes = "type=absolute", .text = "0.07"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.07, 0.07"},
    {.id = "x145", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "0.03"}}}, .read = &readAxial, .expected = "AFTER, 0.03, 0.23"},
    {.id = "x146", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}, {.key = "RocketComponent:axialoffset", .attributes = "method=bottom", .text = "-0.01"}}}, .read = &readAxial, .expected = "BOTTOM, -0.01, 0.188"},
    {.id = "x147", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.1"}, {.key = "RocketComponent:position", .attributes = "type=top", .text = "abc"}}}, .read = &readAxial, .expected = "TOP, 0.1, 0.1", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x148", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "0.1"}, {.key = "RocketComponent:axialoffset", .attributes = "method=middle", .text = "0"}}}, .read = &readAxial, .expected = "MIDDLE, 0.0, 0.099"},
    {.id = "x149", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "TrapezoidFinSet:rootchord", .text = "0.1"}, {.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "0.02"}, {.key = "RocketComponent:axialoffset", .attributes = "method=bottom", .text = "0"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.1"},
});

// What QtRocket answers otherwise than OpenRocket, on purpose: the row has QtRocket's
// answer, the comment above it the reason and OpenRocket's answer.
constexpr auto kOwn = std::to_array<SetterScript>({
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, 0.198, 0.198 THROWN BugException
    {.id = "x023", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, Infinity, Infinity
    {.id = "x024", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "Infinity"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, -Infinity, -Infinity
    {.id = "x025", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "-Infinity"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=-Infinity    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, Infinity, Infinity
    {.id = "x028", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "1e999"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=1e999    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: ABSOLUTE, 0.198, 0.198 THROWN BugException
    {.id = "x037", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "NaN"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: AFTER, 0.0, 0.0
    {.id = "x038", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "NaN"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: ABSOLUTE, Infinity, Infinity
    {.id = "x039", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=absolute", .text = "Infinity"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: AFTER, 0.0, 0.0
    {.id = "x040", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=after", .text = "Infinity"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.198", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    // decision L3: what is not finite is not applied
    // OpenRocket: ABSOLUTE, 0.0, 0.0
    {.id = "x063", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.0, 0.0", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.Rocket"},
    // decision L3: what is not finite is not applied
    // OpenRocket: ABSOLUTE, 0.0, 0.0
    {.id = "x064", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "Infinity"}}}, .read = &readAxial, .expected = "ABSOLUTE, 0.0, 0.0", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.Rocket"},
    // decision L3: what is not finite is not applied
    // OpenRocket: AFTER, 0.0, 0.0
    {.id = "x070", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.AxialStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: AFTER, 0.0, 0.0
    {.id = "x071", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "Infinity"}}}, .read = &readAxial, .expected = "AFTER, 0.0, 0.0", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.AxialStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, 0.2, 0.2 THROWN BugException
    {.id = "x077", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.2", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, Infinity, Infinity
    {.id = "x078", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "Infinity"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.2", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, 0.2, 0.2 THROWN BugException
    {.id = "x084", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "NaN"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.2", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.ParallelStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: TOP, Infinity, Infinity
    {.id = "x085", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:axialoffset", .attributes = "method=top", .text = "Infinity"}}}, .read = &readAxial, .expected = "BOTTOM, 0.0, 0.2", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.ParallelStage"},
});
// clang-format on
// ---- end of the generated part

TEST(AxialPositionSetter, DoesWithEveryElementWhatOpenRocketDoes)
{
    EXPECT_EQ(checkSetterScripts(kJava), Texts{});
}

// OpenRocket sets the method and then dies of a NaN (a BugException) or stores an infinity.
TEST(AxialPositionSetter, AnOffsetThatIsNotFiniteIsNotApplied)
{
    EXPECT_EQ(checkSetterScripts(kOwn), Texts{});
}

// The cases x000, x005 and x011 of the probe, through a setter of the test's own.
TEST(AxialPositionSetter, SetsTheMethodAndThenTheOffset)
{
    const AxialPositionSetter setter;
    // The other way round the bulkhead would sit 0.1 m from the bottom of the tube, at 0.298.
    EXPECT_EQ(applyByHand(setter, ComponentKind::BULKHEAD, "method=top", "0.1", &readAxial),
              "TOP, 0.1, 0.1");
    EXPECT_EQ(applyByHand(setter, ComponentKind::BULKHEAD, "type=top", "0.1", &readAxial),
              "TOP, 0.1, 0.1");
    EXPECT_EQ(applyByHand(setter, ComponentKind::BULKHEAD, "", "0.03", &readAxial),
              "BOTTOM, 0.0, 0.198 [Invalid parameter encountered, ignoring.]");
}

/// What the setter does with a pod set that is in no tree: "set", or the message of the
/// BugError.
[[nodiscard]] std::string positionAPodSetOutsideATree()
{
    ApplicationSetterFixture  fixture;
    PodSet                    pod;
    WarningSet                warnings;
    const AxialPositionSetter setter;
    try
    {
        const Result<void> result =
            setter.set(pod, "0.1", attributesOf("method=top"), warnings, fixture.context());
        return result.has_value() ? "set" : "failed";
    }
    catch (const BugError& error)
    {
        return error.what();
    }
}

// A loader attaches a component to its parent before it sets anything (ComponentHandler), so no
// file brings this about; OpenRocket has a BugException here as well.
TEST(AxialPositionSetter, AnAssemblyOutsideATreeCannotBePositioned)
{
    EXPECT_NE(positionAPodSetOutsideATree().find("requires a parent before any positioning"),
              std::string::npos);
}

}  // namespace
