#include "QtRocket/file/openrocket/ClusterConfigurationSetter.h"

#include <algorithm>
#include <array>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/rocket/ClusterConfiguration.h"
#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/InnerTube.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "file/openrocket/SetterTestSupport.h"

// What <clusterconfiguration> does to an inner tube, as OpenRocket's ClusterConfigurationSetter
// does it. kJava holds OpenRocket's answers (the probe SpecialSetterProbe of tier 9b, part R2;
// see SetterTestSupport.h): the XML name of the layout and the number of tubes
// (getClusterConfiguration.getXMLName, getInstanceCount) after the elements of a row, and the
// warnings. The last rows apply the setter by hand to a component that cannot be clustered,
// which no file does.

namespace
{

using QtRocket::ClusterConfigurationSetter;
using QtRocket::ComponentKind;
using QtRocket::InnerTube;
using QtRocket::RocketComponent;
using QtRocket::Test::ApplicationSetterFixture;
using QtRocket::Test::applyByHand;
using QtRocket::Test::as;
using QtRocket::Test::asText;
using QtRocket::Test::checkSetterScripts;
using QtRocket::Test::count;
using QtRocket::Test::listInOrder;
using QtRocket::Test::SetterScript;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_r2_tests.py of the probe: the readers
[[nodiscard]] std::string readInnerTube(ApplicationSetterFixture& /*fixture*/,
                                        const RocketComponent& c)
{
    return listInOrder({asText(as<InnerTube>(c).getClusterConfiguration().getXmlName()),
                        count(c.getInstanceCount())});
}

[[nodiscard]] std::string readName(ApplicationSetterFixture& /*fixture*/, const RocketComponent& c)
{
    return c.getName();
}

// ---- generated: OpenRocket's answers, one row per case of the probe
// clang-format off
constexpr auto kJava = std::to_array<SetterScript>({
    {.id = "x591", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "single"}}}, .read = &readInnerTube, .expected = "single, 1"},
    {.id = "x592", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "double"}}}, .read = &readInnerTube, .expected = "double, 2"},
    {.id = "x593", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-row"}}}, .read = &readInnerTube, .expected = "3-row, 3"},
    {.id = "x594", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "4-row"}}}, .read = &readInnerTube, .expected = "4-row, 4"},
    {.id = "x595", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-ring"}}}, .read = &readInnerTube, .expected = "3-ring, 3"},
    {.id = "x596", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "4-ring"}}}, .read = &readInnerTube, .expected = "4-ring, 4"},
    {.id = "x597", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "5-ring"}}}, .read = &readInnerTube, .expected = "5-ring, 5"},
    {.id = "x598", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "6-ring"}}}, .read = &readInnerTube, .expected = "6-ring, 6"},
    {.id = "x599", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-star"}}}, .read = &readInnerTube, .expected = "3-star, 4"},
    {.id = "x600", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "4-star"}}}, .read = &readInnerTube, .expected = "4-star, 5"},
    {.id = "x601", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "5-star"}}}, .read = &readInnerTube, .expected = "5-star, 6"},
    {.id = "x602", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "6-star"}}}, .read = &readInnerTube, .expected = "6-star, 7"},
    {.id = "x603", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "9-grid"}}}, .read = &readInnerTube, .expected = "9-grid, 9"},
    {.id = "x604", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "9-star"}}}, .read = &readInnerTube, .expected = "9-star, 9"},
    {.id = "x605", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "bogus"}}}, .read = &readInnerTube, .expected = "single, 1", .warnings = "Illegal cluster configuration specified."},
    {.id = "x606", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = " 3-ring "}}}, .read = &readInnerTube, .expected = "single, 1", .warnings = "Illegal cluster configuration specified."},
    {.id = "x607", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-RING"}}}, .read = &readInnerTube, .expected = "single, 1", .warnings = "Illegal cluster configuration specified."},
    {.id = "x608", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration"}}}, .read = &readInnerTube, .expected = "single, 1", .warnings = "Illegal cluster configuration specified."},
    {.id = "x609", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-ring\n"}}}, .read = &readInnerTube, .expected = "single, 1", .warnings = "Illegal cluster configuration specified."},
    {.id = "x610", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "SINGLE"}}}, .read = &readInnerTube, .expected = "single, 1", .warnings = "Illegal cluster configuration specified."},
    {.id = "x611", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "7-ring"}}}, .read = &readInnerTube, .expected = "single, 1", .warnings = "Illegal cluster configuration specified."},
    {.id = "x612", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "4-ring"}, {.key = "InnerTube:clusterconfiguration", .text = "bogus"}}}, .read = &readInnerTube, .expected = "4-ring, 4", .warnings = "Illegal cluster configuration specified."},
    {.id = "x613", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "4-ring"}, {.key = "InnerTube:clusterconfiguration", .text = "double"}}}, .read = &readInnerTube, .expected = "double, 2"},
    {.id = "x628", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-ring"}}}, .read = &readName, .expected = "Body Tube", .warnings = "Illegal component defined as cluster."},
    {.id = "x629", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "bogus"}}}, .read = &readName, .expected = "Body Tube", .warnings = "Illegal component defined as cluster."},
    {.id = "x630", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-ring"}}}, .read = &readName, .expected = "Bulkhead", .warnings = "Illegal component defined as cluster."},
    {.id = "x631", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "bogus"}}}, .read = &readName, .expected = "Bulkhead", .warnings = "Illegal component defined as cluster."},
    {.id = "x632", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "3-ring"}}}, .read = &readName, .expected = "Tube Coupler", .warnings = "Illegal component defined as cluster."},
    {.id = "x633", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "InnerTube:clusterconfiguration", .text = "bogus"}}}, .read = &readName, .expected = "Tube Coupler", .warnings = "Illegal component defined as cluster."},
});
// clang-format on
// ---- end of the generated part

TEST(ClusterConfigurationSetter, DoesWithEveryElementWhatOpenRocketDoes)
{
    EXPECT_EQ(checkSetterScripts(kJava), Texts{});
}

/// The XML names of OpenRocket's layouts that no row of kJava sets.
[[nodiscard]] Texts layoutsWithoutARow()
{
    Texts missing;
    for (const QtRocket::ClusterConfiguration& layout :
         QtRocket::ClusterConfiguration::configurations())
    {
        const bool hasRow = std::ranges::any_of(kJava, [&layout](const SetterScript& row) {
            return row.steps.front().text == layout.getXmlName() && row.warnings.empty();
        });
        if (!hasRow)
        {
            missing.emplace_back(layout.getXmlName());
        }
    }
    return missing;
}

TEST(ClusterConfigurationSetter, EveryLayoutHasARow)
{
    EXPECT_EQ(layoutsWithoutARow(), Texts{});
}

// The cases x597 and x606 of the probe, through a setter of the test's own.
TEST(ClusterConfigurationSetter, TakesTheTextAsItIs)
{
    const ClusterConfigurationSetter setter;
    EXPECT_EQ(applyByHand(setter, ComponentKind::INNER_TUBE, "", "5-ring", &readInnerTube),
              "5-ring, 5");
    EXPECT_EQ(applyByHand(setter, ComponentKind::INNER_TUBE, "", " 3-ring ", &readInnerTube),
              "single, 1 [Illegal cluster configuration specified.]");
}

}  // namespace
