#include "QtRocket/file/openrocket/ComponentPresetSetter.h"

#include <array>
#include <format>
#include <memory>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/file/openrocket/DocumentConfig.h"
#include "QtRocket/file/openrocket/Setter.h"
#include "QtRocket/logging/WarningSet.h"
#include "QtRocket/material/Material.h"
#include "QtRocket/material/MaterialGroup.h"
#include "QtRocket/material/MaterialStorage.h"
#include "QtRocket/motor/Manufacturer.h"
#include "QtRocket/rocket/BodyTube.h"
#include "QtRocket/rocket/Bulkhead.h"
#include "QtRocket/rocket/CenteringRing.h"
#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/EllipticalFinSet.h"
#include "QtRocket/rocket/EngineBlock.h"
#include "QtRocket/rocket/FreeformFinSet.h"
#include "QtRocket/rocket/InnerTube.h"
#include "QtRocket/rocket/LaunchLug.h"
#include "QtRocket/rocket/NoseCone.h"
#include "QtRocket/rocket/Parachute.h"
#include "QtRocket/rocket/RailButton.h"
#include "QtRocket/rocket/RecoveryDevice.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "QtRocket/rocket/ShockCord.h"
#include "QtRocket/rocket/Streamer.h"
#include "QtRocket/rocket/Transition.h"
#include "QtRocket/rocket/TransitionShape.h"
#include "QtRocket/rocket/TrapezoidFinSet.h"
#include "QtRocket/rocket/TubeCoupler.h"
#include "QtRocket/rocket/TubeFinSet.h"
#include "QtRocket/rocket/preset/ComponentPreset.h"
#include "QtRocket/rocket/preset/ComponentPresetDatabase.h"
#include "QtRocket/rocket/preset/ComponentPresetFactory.h"
#include "QtRocket/rocket/preset/ComponentPresetType.h"
#include "QtRocket/rocket/preset/TypedPropertyMap.h"
#include "QtRocket/util/BugError.h"
#include "QtRocket/util/Strings.h"
#include "file/openrocket/SetterTestSupport.h"
#include "rocket/preset/ExamplePresets.h"

// What <preset> does to a component, as OpenRocket's ComponentPresetSetter does it. kJava holds
// OpenRocket's answers (the probe SpecialSetterProbe of tier 9b, part R2, run with OpenRocket's
// preset files; see SetterTestSupport.h). A row applies its elements through the entries of the
// setter table to a new component in a document whose application has the six presets of the
// example designs (ExamplePresets.h), and compares the part number and the digest of the
// component's preset ("null, null" without one), its name, the values the preset sets, the
// materials the document holds afterwards and the warnings.
//
// The rows with `.bracket = true` have RocketComponent::setIgnorePresetClearing(true) in force,
// as the handler of a component's parameters has for all the elements of a component; the same
// rows without it show what the elements behind <preset> do to the link otherwise.

namespace
{

using QtRocket::BodyTube;
using QtRocket::BugError;
using QtRocket::Bulkhead;
using QtRocket::CenteringRing;
using QtRocket::ComponentKind;
using QtRocket::ComponentPreset;
using QtRocket::ComponentPresetDatabase;
using QtRocket::ComponentPresetFactory;
using QtRocket::ComponentPresetSetter;
using QtRocket::ComponentPresetType;
using QtRocket::componentPresetTypeName;
using QtRocket::DocumentConfig;
using QtRocket::EllipticalFinSet;
using QtRocket::EngineBlock;
using QtRocket::FreeformFinSet;
using QtRocket::InnerTube;
using QtRocket::LaunchLug;
using QtRocket::Manufacturer;
using QtRocket::Material;
using QtRocket::MaterialGroup;
using QtRocket::MaterialStorage;
using QtRocket::NoseCone;
using QtRocket::Parachute;
using QtRocket::RailButton;
using QtRocket::RocketComponent;
using QtRocket::Setter;
using QtRocket::ShockCord;
using QtRocket::Streamer;
using QtRocket::Transition;
using QtRocket::transitionShapeName;
using QtRocket::TrapezoidFinSet;
using QtRocket::TubeCoupler;
using QtRocket::TubeFinSet;
using QtRocket::TypedPropertyMap;
using QtRocket::WarningSet;
using QtRocket::Test::ApplicationSetterFixture;
using QtRocket::Test::as;
using QtRocket::Test::asText;
using QtRocket::Test::attributesOf;
using QtRocket::Test::checkSetterScripts;
using QtRocket::Test::count;
using QtRocket::Test::documentMaterialsOf;
using QtRocket::Test::ExamplePresetReference;
using QtRocket::Test::flag;
using QtRocket::Test::kExamplePresetReferences;
using QtRocket::Test::listInOrder;
using QtRocket::Test::num;
using QtRocket::Test::presetDigestOf;
using QtRocket::Test::presetPartNoOf;
using QtRocket::Test::setterOfKey;
using QtRocket::Test::SetterScript;
using QtRocket::Test::withWarnings;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_r2_tests.py of the probe: the readers
[[nodiscard]] std::string readBodyTube(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder(
        {presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
         num(as<BodyTube>(c).getOuterRadius()), flag(as<BodyTube>(c).isOuterRadiusAutomatic()),
         num(as<BodyTube>(c).getThickness()), as<BodyTube>(c).getMaterial().toStorableString(),
         flag(as<BodyTube>(c).getMaterial().isUserDefined()),
         flag(as<BodyTube>(c).getMaterial().isDocumentMaterial()),
         documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readParachute(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder(
        {presetPartNoOf(c), presetDigestOf(c), c.getName(), num(as<Parachute>(c).getDiameter()),
         count(as<Parachute>(c).getLineCount()), num(as<Parachute>(c).getLineLength()),
         flag(as<Parachute>(c).isLineLengthAutomatic()), num(as<Parachute>(c).getCD()),
         flag(as<Parachute>(c).isCDAutomatic()), num(as<Parachute>(c).getRadius()),
         flag(as<Parachute>(c).isRadiusAutomatic()), num(c.getLength()), num(c.getOverrideMass()),
         flag(c.isMassOverridden()), as<Parachute>(c).getMaterial().toStorableString(),
         as<Parachute>(c).getLineMaterial().toStorableString(),
         documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readNoseCone(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c),
                        presetDigestOf(c),
                        c.getName(),
                        num(c.getLength()),
                        num(as<NoseCone>(c).getAftRadius()),
                        flag(as<NoseCone>(c).isAftRadiusAutomatic()),
                        num(as<NoseCone>(c).getAftShoulderLength()),
                        num(as<NoseCone>(c).getAftShoulderRadius()),
                        num(as<NoseCone>(c).getThickness()),
                        flag(as<NoseCone>(c).isFilled()),
                        num(as<NoseCone>(c).getForeShoulderThickness()),
                        num(as<NoseCone>(c).getAftShoulderThickness()),
                        asText(transitionShapeName(as<NoseCone>(c).getShapeType())),
                        flag(as<NoseCone>(c).isClipped()),
                        num(as<NoseCone>(c).getShapeParameter()),
                        flag(c.isMassOverridden()),
                        as<NoseCone>(c).getMaterial().toStorableString(),
                        flag(as<NoseCone>(c).getMaterial().isUserDefined()),
                        flag(as<NoseCone>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTransition(ApplicationSetterFixture& fixture,
                                         const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(),
                        as<Transition>(c).getMaterial().toStorableString(),
                        flag(as<Transition>(c).getMaterial().isUserDefined()),
                        flag(as<Transition>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTubeCoupler(ApplicationSetterFixture& fixture,
                                          const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<TubeCoupler>(c).getOuterRadius()),
                        flag(as<TubeCoupler>(c).isOuterRadiusAutomatic()),
                        num(as<TubeCoupler>(c).getThickness()),
                        as<TubeCoupler>(c).getMaterial().toStorableString(),
                        flag(as<TubeCoupler>(c).getMaterial().isUserDefined()),
                        flag(as<TubeCoupler>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readInnerTube(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<InnerTube>(c).getOuterRadius()),
                        num(as<InnerTube>(c).getThickness()),
                        as<InnerTube>(c).getMaterial().toStorableString(),
                        flag(as<InnerTube>(c).getMaterial().isUserDefined()),
                        flag(as<InnerTube>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readEngineBlock(ApplicationSetterFixture& fixture,
                                          const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<EngineBlock>(c).getOuterRadius()),
                        num(as<EngineBlock>(c).getThickness()),
                        as<EngineBlock>(c).getMaterial().toStorableString(),
                        flag(as<EngineBlock>(c).getMaterial().isUserDefined()),
                        flag(as<EngineBlock>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readCenteringRing(ApplicationSetterFixture& fixture,
                                            const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<CenteringRing>(c).getOuterRadius()),
                        num(as<CenteringRing>(c).getInnerRadius()),
                        as<CenteringRing>(c).getMaterial().toStorableString(),
                        flag(as<CenteringRing>(c).getMaterial().isUserDefined()),
                        flag(as<CenteringRing>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readBulkhead(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<Bulkhead>(c).getOuterRadius()),
                        as<Bulkhead>(c).getMaterial().toStorableString(),
                        flag(as<Bulkhead>(c).getMaterial().isUserDefined()),
                        flag(as<Bulkhead>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readLaunchLug(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<LaunchLug>(c).getOuterRadius()),
                        num(as<LaunchLug>(c).getThickness()),
                        as<LaunchLug>(c).getMaterial().toStorableString(),
                        flag(as<LaunchLug>(c).getMaterial().isUserDefined()),
                        flag(as<LaunchLug>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readRailButton(ApplicationSetterFixture& fixture,
                                         const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(),
                        num(as<RailButton>(c).getOuterDiameter()),
                        num(as<RailButton>(c).getInnerDiameter()), flag(c.isMassOverridden()),
                        flag(c.isCDOverridden()),
                        as<RailButton>(c).getMaterial().toStorableString(),
                        flag(as<RailButton>(c).getMaterial().isUserDefined()),
                        flag(as<RailButton>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTubeFinSet(ApplicationSetterFixture& fixture,
                                         const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<TubeFinSet>(c).getOuterRadius()),
                        num(as<TubeFinSet>(c).getThickness()),
                        as<TubeFinSet>(c).getMaterial().toStorableString(),
                        flag(as<TubeFinSet>(c).getMaterial().isUserDefined()),
                        flag(as<TubeFinSet>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTrapezoidFinSet(ApplicationSetterFixture& fixture,
                                              const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        as<TrapezoidFinSet>(c).getMaterial().toStorableString(),
                        flag(as<TrapezoidFinSet>(c).getMaterial().isUserDefined()),
                        flag(as<TrapezoidFinSet>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readEllipticalFinSet(ApplicationSetterFixture& fixture,
                                               const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        as<EllipticalFinSet>(c).getMaterial().toStorableString(),
                        flag(as<EllipticalFinSet>(c).getMaterial().isUserDefined()),
                        flag(as<EllipticalFinSet>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readFreeformFinSet(ApplicationSetterFixture& fixture,
                                             const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        as<FreeformFinSet>(c).getMaterial().toStorableString(),
                        flag(as<FreeformFinSet>(c).getMaterial().isUserDefined()),
                        flag(as<FreeformFinSet>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readPresetAndLength(ApplicationSetterFixture& /*fixture*/,
                                              const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength())});
}

[[nodiscard]] std::string readShockCord(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        as<ShockCord>(c).getMaterial().toStorableString(),
                        flag(as<ShockCord>(c).getMaterial().isUserDefined()),
                        flag(as<ShockCord>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readStreamer(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<Streamer>(c).getStripLength()), num(as<Streamer>(c).getStripWidth()),
                        as<Streamer>(c).getMaterial().toStorableString(),
                        flag(as<Streamer>(c).getMaterial().isUserDefined()),
                        flag(as<Streamer>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readStreamerB(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(),
                        as<Streamer>(c).getMaterial().toStorableString(),
                        flag(as<Streamer>(c).getMaterial().isUserDefined()),
                        flag(as<Streamer>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readStreamerC(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(), num(c.getLength()),
                        num(as<Streamer>(c).getStripLength()), num(as<Streamer>(c).getStripWidth()),
                        num(as<Streamer>(c).getCD()), flag(as<Streamer>(c).isCDAutomatic()),
                        as<Streamer>(c).getMaterial().toStorableString(),
                        flag(as<Streamer>(c).getMaterial().isUserDefined()),
                        flag(as<Streamer>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readCenteringRingB(ApplicationSetterFixture& fixture,
                                             const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(),
                        as<CenteringRing>(c).getMaterial().toStorableString(),
                        flag(as<CenteringRing>(c).getMaterial().isUserDefined()),
                        flag(as<CenteringRing>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readShockCordB(ApplicationSetterFixture& fixture,
                                         const RocketComponent&    c)
{
    return listInOrder({presetPartNoOf(c), presetDigestOf(c), c.getName(),
                        as<ShockCord>(c).getMaterial().toStorableString(),
                        flag(as<ShockCord>(c).getMaterial().isUserDefined()),
                        flag(as<ShockCord>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

// ---- generated: OpenRocket's answers, one row per case of the probe
// clang-format off
constexpr auto kJava = std::to_array<SetterScript>({
    {.id = "p000", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p001", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd8"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes BT-50FE, 30359"},
    {.id = "p002", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Invalid ComponentPreset for component Mine, no digest specified. | No matching ComponentPreset for component Mine found matching Estes BT-50FE, 30359"},
    {.id = "p003", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other", .warnings = "Invalid ComponentPreset for component Mine, no type specified."},
    {.id = "p004", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Invalid ComponentPreset for component Mine, no manufacturer specified.  Ignored"},
    {.id = "p005", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Invalid ComponentPreset for component Mine, no partno specified.  Ignored"},
    {.id = "p006", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Nobody Rockets|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Nobody Rockets BT-50FE, 30359"},
    {.id = "p007", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p008", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "manufacturer=Estes|partno=BT-50FE, 30359"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Invalid ComponentPreset for component Mine, no digest specified. | Invalid ComponentPreset for component Mine, no type specified. | No matching ComponentPreset for component Mine found matching Estes BT-50FE, 30359"},
    {.id = "p009", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=ESTES|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p010", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Invalid ComponentPreset for component Mine, no manufacturer specified.  Ignored"},
    {.id = "p011", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=bogus|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p012", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes BT-50FE"},
    {.id = "p013", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=bt-50fe, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes bt-50fe, 30359"},
    {.id = "p014", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=E9C3E97D32E96762F65E051D74CB9FD7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes BT-50FE, 30359"},
    {.id = "p015", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest="}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes BT-50FE, 30359"},
    {.id = "p016", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching  BT-50FE, 30359"},
    {.id = "p017", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes "},
    {.id = "p018", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer= Estes |partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p019", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest= e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes BT-50FE, 30359"},
    {.id = "p020", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p021", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes Industries|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "null, null, Mine, 0.2, 0.025, true, 0.002, BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "No matching ComponentPreset for component Mine found matching Estes Industries BT-50FE, 30359"},
    {.id = "p022", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7|extra=1"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p023", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Body Tube, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p024", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7", .text = "some text"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Body Tube, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p025", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Body Tube, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p026", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50, 30352|digest=a59dec8e4034a2fee5955dbf4ff07f1c"}}}, .read = &readBodyTube, .expected = "BT-50, 30352, a59dec8e4034a2fee5955dbf4ff07f1c, Body Tube, 0.4572, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p027", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=x"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Body Tube, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other", .warnings = "No matching ComponentPreset for component Body Tube found matching Estes BT-50FE, 30359"},
    {.id = "p028", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readParachute, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Parachute, 0.254, 6, 0.254, false, 0.8, true, 0.0125, false, 0.025, 0.0016936825758791197, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p029", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readParachute, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, 0.254, 6, 0.254, false, 0.8, true, 0.0125, false, 0.025, 0.0016936825758791197, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p030", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-8, 2260|digest=9a96b8806749e790db29bacfbc70eb1e"}}}, .read = &readParachute, .expected = "PK-8, 2260, 9a96b8806749e790db29bacfbc70eb1e, Mine, 0.2032, 6, 0.2032, false, 0.8, true, 0.0125, false, 0.025, 0.0011644240485626364, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p031", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262"}}}, .read = &readParachute, .expected = "null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.025, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, ", .warnings = "Invalid ComponentPreset for component Mine, no digest specified. | No matching ComponentPreset for component Mine found matching Estes PK-10, 2262"},
    {.id = "p032", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readParachute, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, 0.254, 6, 0.254, false, 0.8, true, 0.0125, false, 0.025, 0.0016936825758791197, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p033", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "MassObject:packedradius", .text = "auto 0.01"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readParachute, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Parachute, 0.254, 6, 0.254, false, 0.8, true, 0.023, true, 0.004725897920604916, 0.0016936825758791197, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p034", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "MassObject:packedradius", .text = "auto 0.01"}, {.key = "RocketComponent:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readParachute, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Parachute, 0.254, 6, 0.254, false, 0.8, true, 0.023, true, 0.004725897920604916, 0.0016936825758791197, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p035", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}}}, .read = &readNoseCone, .expected = "PNC-50YR, 72604, 18363dec5642206a109389ef48efcb32, Mine, 0.104775, 0.012395199999999999, false, 0.019049999999999997, 0.012065, 0.0015748, false, 0.0015748, 0.0015748, OGIVE, false, 1.0, false, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom, true, true, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom"},
    {.id = "p036", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-20, 072606|digest=6f564a198c80de3af437608827fa1bc1"}}}, .read = &readNoseCone, .expected = "PNC-20, 072606, 6f564a198c80de3af437608827fa1bc1, Mine, 0.06731, 0.0093472, false, 0.0127, 0.009016999999999999, 0.0015748, false, 0.0015748, 0.0015748, OGIVE, false, 1.0, false, BULK|Polystyrene, cast, bulk|682.4826031822124|0.0|Custom, true, true, BULK|Polystyrene, cast, bulk|682.4826031822124|0.0|Custom"},
    {.id = "p037", .kind = ComponentKind::NOSE_CONE, .inFront = true, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}}}, .read = &readNoseCone, .expected = "PNC-50YR, 72604, 18363dec5642206a109389ef48efcb32, Mine, 0.104775, 0.012395199999999999, false, 0.019049999999999997, 0.012065, 0.0015748, false, 0.0015748, -1.002, OGIVE, false, 1.0, false, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom, true, true, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom"},
    {.id = "p038", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "NoseCone:isflipped", .text = "true"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}}}, .read = &readNoseCone, .expected = "PNC-50YR, 72604, 18363dec5642206a109389ef48efcb32, Nose Cone, 0.104775, 0.0, false, 0.0, 0.0, 0.0015748, false, 0.0015748, 0.0, OGIVE, false, 1.0, false, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom, true, true, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom"},
    {.id = "p039", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readNoseCone, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.025, false, 0.0, 0.0, 3.3019999999999924E-4, false, 3.3019999999999924E-4, 3.3019999999999924E-4, OGIVE, false, 1.0, false, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p040", .kind = ComponentKind::TRANSITION, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readTransition, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p041", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readTubeCoupler, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p042", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readInnerTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p043", .kind = ComponentKind::ENGINE_BLOCK, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readEngineBlock, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p044", .kind = ComponentKind::CENTERING_RING, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readCenteringRing, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, 0.012065, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p045", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBulkhead, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p046", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readLaunchLug, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p047", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readRailButton, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.024790399999999997, 0.02413, false, false, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p048", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readTubeFinSet, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, 0.012395199999999999, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p049", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readTrapezoidFinSet, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p050", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readEllipticalFinSet, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p051", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readFreeformFinSet, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.05, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p052", .kind = ComponentKind::MASS_COMPONENT, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readPresetAndLength, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651"},
    {.id = "p053", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readShockCord, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.1651, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, false, false, "},
    {.id = "p058", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readStreamerC, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, 0.05, 0.5, 0.05, 0.04711428571428572, true, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, true, true, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p059", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readBodyTube, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, 0.2, 0.025, true, 0.002, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, true, true, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p060", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}}}, .read = &readBodyTube, .expected = "PNC-50YR, 72604, 18363dec5642206a109389ef48efcb32, Mine, 0.104775, 0.025, true, 0.0015748, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom, true, true, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom"},
    {.id = "p061", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readNoseCone, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, 0.15000000000000002, 0.025, false, 0.0, 0.0, 0.002, false, 0.0, 0.0, OGIVE, false, 1.0, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, true, true, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p062", .kind = ComponentKind::CENTERING_RING, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readCenteringRingB, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, true, true, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p063", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}}}, .read = &readShockCordB, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, false, false, "},
    {.id = "p064", .kind = ComponentKind::ROCKET, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readPresetAndLength, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.2"},
    {.id = "p065", .kind = ComponentKind::AXIAL_STAGE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readPresetAndLength, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.2"},
    {.id = "p066", .kind = ComponentKind::POD_SET, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readPresetAndLength, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.0"},
    {.id = "p067", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readPresetAndLength, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Mine, 0.0"},
    {.id = "p070", .kind = ComponentKind::BODY_TUBE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "ExternalComponent:finish", .text = "unfinished"}, {.key = "ExternalComponent:material", .attributes = "type=bulk|density=894.4|group=Custom", .text = "Paper, spiral kraft glassine, Estes avg, bulk"}, {.key = "BodyComponent:length", .text = "0.15239999999999998"}, {.key = "SymmetricComponent:thickness", .text = "3.3019999999999924E-4"}, {.key = "BodyTube:radius", .text = "0.012395199999999999"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.15239999999999998, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other; BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom"},
    {.id = "p071", .kind = ComponentKind::BODY_TUBE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "ExternalComponent:finish", .text = "unfinished"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p072", .kind = ComponentKind::BODY_TUBE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "ExternalComponent:material", .attributes = "type=bulk|density=894.4|group=Custom", .text = "Paper, spiral kraft glassine, Estes avg, bulk"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other; BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom"},
    {.id = "p073", .kind = ComponentKind::BODY_TUBE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "BodyComponent:length", .text = "0.15239999999999998"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.15239999999999998, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p074", .kind = ComponentKind::BODY_TUBE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "SymmetricComponent:thickness", .text = "3.3019999999999924E-4"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p075", .kind = ComponentKind::BODY_TUBE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "BodyTube:radius", .text = "0.012395199999999999"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p076", .kind = ComponentKind::BODY_TUBE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "RocketComponent:comment", .text = "c"}, {.key = "RocketComponent:color", .attributes = "red=1|green=2|blue=3"}, {.key = "RocketComponent:overridemass", .text = "0.1"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p077", .kind = ComponentKind::PARACHUTE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}, {.key = "Parachute:diameter", .text = "0.3"}}}, .read = &readParachute, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, 0.3, 6, 0.254, false, 0.8, true, 0.0125, false, 0.025, 0.0021640371155856033, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p078", .kind = ComponentKind::PARACHUTE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}, {.key = "RecoveryDevice:material", .attributes = "type=surface|density=0.067", .text = "Ripstop nylon"}}}, .read = &readParachute, .expected = "PK-10, 2262, b595c8a31baaf325291d5c957f3940f8, Mine, 0.254, 6, 0.254, false, 0.8, true, 0.0125, false, 0.025, 0.0038978601099532353, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p079", .kind = ComponentKind::NOSE_CONE, .bracket = true, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}, {.key = "BodyComponent:length", .text = "0.1"}}}, .read = &readNoseCone, .expected = "PNC-50YR, 72604, 18363dec5642206a109389ef48efcb32, Mine, 0.1, 0.012395199999999999, false, 0.019049999999999997, 0.012065, 0.0015748, false, 0.0015748, 0.0015748, OGIVE, false, 1.0, false, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom, true, true, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom"},
    {.id = "p080", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "ExternalComponent:finish", .text = "unfinished"}, {.key = "ExternalComponent:material", .attributes = "type=bulk|density=894.4|group=Custom", .text = "Paper, spiral kraft glassine, Estes avg, bulk"}, {.key = "BodyComponent:length", .text = "0.15239999999999998"}, {.key = "SymmetricComponent:thickness", .text = "3.3019999999999924E-4"}, {.key = "BodyTube:radius", .text = "0.012395199999999999"}}}, .read = &readBodyTube, .expected = "null, null, Paper Body Tube -- DO NOT PRINT, 0.15239999999999998, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other; BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom"},
    {.id = "p081", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "ExternalComponent:finish", .text = "unfinished"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p082", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "ExternalComponent:material", .attributes = "type=bulk|density=894.4|group=Custom", .text = "Paper, spiral kraft glassine, Estes avg, bulk"}}}, .read = &readBodyTube, .expected = "null, null, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other; BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom"},
    {.id = "p083", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "BodyComponent:length", .text = "0.15239999999999998"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.15239999999999998, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p084", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "SymmetricComponent:thickness", .text = "3.3019999999999924E-4"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p085", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "BodyTube:radius", .text = "0.012395199999999999"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p086", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "RocketComponent:name", .text = "Paper Body Tube -- DO NOT PRINT"}, {.key = "RocketComponent:id", .text = "402aead9-e43c-4d53-9367-03011b9c3776"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}, {.key = "RocketComponent:comment", .text = "c"}, {.key = "RocketComponent:color", .attributes = "red=1|green=2|blue=3"}, {.key = "RocketComponent:overridemass", .text = "0.1"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
    {.id = "p087", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}, {.key = "Parachute:diameter", .text = "0.3"}}}, .read = &readParachute, .expected = "null, null, Mine, 0.3, 6, 0.254, false, 0.8, true, 0.0125, false, 0.025, 0.0021640371155856033, false, SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p088", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=PARACHUTE|manufacturer=Estes|partno=PK-10, 2262|digest=b595c8a31baaf325291d5c957f3940f8"}, {.key = "RecoveryDevice:material", .attributes = "type=surface|density=0.067", .text = "Ripstop nylon"}}}, .read = &readParachute, .expected = "null, null, Mine, 0.254, 6, 0.254, false, 0.8, true, 0.0125, false, 0.025, 0.0038978601099532353, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Carpet Thread|3.3E-4|0.0|Other, LINE|Carpet Thread|3.3E-4|0.0|Other; SURFACE|Polyethylene film, HDPE, 1.0 mil, bare|0.0235|0.0|Other"},
    {.id = "p089", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}, {.key = "BodyComponent:length", .text = "0.1"}}}, .read = &readNoseCone, .expected = "null, null, Mine, 0.1, 0.012395199999999999, false, 0.019049999999999997, 0.012065, 0.0015748, false, 0.0015748, 0.0015748, OGIVE, false, 1.0, false, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom, true, true, BULK|Polystyrene, cast, bulk|756.2852368449444|0.0|Custom"},
    {.id = "p090", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=894.4|group=Custom", .text = "Paper, spiral kraft glassine, Estes avg, bulk"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readBodyTube, .expected = "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Body Tube, 0.1651, 0.012395199999999999, false, 3.3019999999999924E-4, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other, true, true, BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom; BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other"},
});

// What QtRocket answers otherwise than OpenRocket, on purpose: the row has QtRocket's
// answer, the comment above it the reason and OpenRocket's answer.
constexpr auto kOwn = std::to_array<SetterScript>({
    // decision L4: OpenRocket dies here, the preset is not loaded
    // OpenRocket: null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.1651, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics,  THROWN ClassCastException
    {.id = "p054", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readParachute, .expected = "null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.025, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, ", .warnings = "Invalid parameter encountered, ignoring."},
    // decision L4: OpenRocket dies here, the preset is not loaded
    // OpenRocket: null, null, Mine, 0.1651, 0.5, 0.05, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, false, false,  THROWN ClassCastException
    {.id = "p055", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readStreamer, .expected = "null, null, Mine, 0.025, 0.5, 0.05, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, false, false, ", .warnings = "Invalid parameter encountered, ignoring."},
    // decision L4: OpenRocket dies here, the preset is not loaded
    // OpenRocket: null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.104775, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics,  THROWN ClassCastException
    {.id = "p056", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}}}, .read = &readParachute, .expected = "null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.025, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, ", .warnings = "Invalid parameter encountered, ignoring."},
    // decision L4: OpenRocket dies here, the preset is not loaded
    // OpenRocket: null, null, Mine, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, false, false,  THROWN ClassCastException
    {.id = "p057", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "RocketComponent:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}}}, .read = &readStreamerB, .expected = "null, null, Mine, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, false, false, ", .warnings = "Invalid parameter encountered, ignoring."},
    // decision L4: OpenRocket dies here, the preset is not loaded
    // OpenRocket: null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.1651, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics,  THROWN ClassCastException
    {.id = "p068", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|digest=e9c3e97d32e96762f65e051d74cb9fd7"}}}, .read = &readParachute, .expected = "null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.025, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, ", .warnings = "Invalid parameter encountered, ignoring."},
    // decision L4: OpenRocket dies here, the preset is not loaded
    // OpenRocket: null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.104775, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics,  THROWN ClassCastException
    {.id = "p069", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RocketComponent:name", .text = "Mine"}, {.key = "Parachute:preset", .attributes = "type=NOSE_CONE|manufacturer=Estes|partno=PNC-50YR, 72604|digest=18363dec5642206a109389ef48efcb32"}}}, .read = &readParachute, .expected = "null, null, Mine, 0.3, 6, 0.44999999999999996, true, 0.8, true, 0.0125, false, 0.025, 0.009595950925286614, false, SURFACE|Ripstop nylon|0.067|0.0|Fabrics, LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, ", .warnings = "Invalid parameter encountered, ignoring."},
});
// clang-format on
// ---- end of the generated part

TEST(ComponentPresetSetter, DoesWithEveryElementWhatOpenRocketDoes)
{
    EXPECT_EQ(checkSetterScripts(kJava), Texts{});
}

// OpenRocket dies of a ClassCastException, the preset's length already set.
TEST(ComponentPresetSetter, ARecoveryDeviceIsNotGivenAPresetWhoseMaterialIsNoSurfaceMaterial)
{
    EXPECT_EQ(checkSetterScripts(kOwn), Texts{});
}

/// What OpenRocket holds after the case @p id of kJava; empty when kJava has no such case.
[[nodiscard]] std::string_view openRocketsAnswerTo(std::string_view id)
{
    for (const SetterScript& script : kJava)
    {
        if (script.id == id)
        {
            return script.expected;
        }
    }
    return {};
}

// For part R3 (ComponentParameterHandler): the rows of kJava that say what its bracket is for.
// They are the body tube of "3D printable nose cone and fins" with its elements in the file's
// order: <name>, <id>, <preset>, then <finish>, <material>, <length>, <thickness>, <radius>.
TEST(ComponentPresetSetter, TheElementsBehindAPresetTakeItsLinkAwayUnlessPresetClearingIsIgnored)
{
    // With RocketComponent::setIgnorePresetClearing(true): the file's values, and the preset.
    EXPECT_TRUE(openRocketsAnswerTo("p070").starts_with(
        "BT-50FE, 30359, e9c3e97d32e96762f65e051d74cb9fd7, Paper Body Tube -- DO NOT PRINT, "
        "0.15239999999999998, "));
    // Without: the same values, and no preset.
    EXPECT_TRUE(openRocketsAnswerTo("p080").starts_with(
        "null, null, Paper Body Tube -- DO NOT PRINT, 0.15239999999999998, "));
    // It is the <material> that does it here (its group is not the preset's)...
    EXPECT_TRUE(openRocketsAnswerTo("p072").starts_with("BT-50FE, 30359, "));
    EXPECT_TRUE(openRocketsAnswerTo("p082").starts_with("null, null, "));
    // ... a parachute's <diameter> and a nose cone's <length> do it as well.
    EXPECT_TRUE(openRocketsAnswerTo("p077").starts_with("PK-10, 2262, "));
    EXPECT_TRUE(openRocketsAnswerTo("p087").starts_with("null, null, "));
    EXPECT_TRUE(openRocketsAnswerTo("p079").starts_with("PNC-50YR, 72604, "));
    EXPECT_TRUE(openRocketsAnswerTo("p089").starts_with("null, null, "));
    // The preset's material reaches the document before the file's, and a save writes the two
    // in that order (the last value of a row: the document's materials).
    EXPECT_TRUE(openRocketsAnswerTo("p070").ends_with(
        "BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Other; "
        "BULK|Paper, spiral kraft glassine, Estes avg, bulk|894.4|0.0|Custom"));
}

/// The <preset> element of the body tube of "3D printable nose cone and fins".
constexpr std::string_view kBodyTubePreset =
    "type=BODY_TUBE|manufacturer=Estes|partno=BT-50FE, 30359|"
    "digest=e9c3e97d32e96762f65e051d74cb9fd7";

/// Applies the entry @p key of the setter table to @p component; false when the table has no
/// such setter or the setter fails.
[[nodiscard]] bool applyKey(ApplicationSetterFixture& fixture, RocketComponent& component,
                            std::string_view key, std::string_view attributes,
                            std::string_view text, WarningSet& warnings)
{
    const Setter* const setter = setterOfKey(key);
    return setter != nullptr &&
           setter->set(component, text, attributesOf(attributes), warnings, fixture.context())
               .has_value();
}

/// What the body tube's <preset> gives a body tube when the context has the preset database
/// @p database: the part number of the tube's preset, then the warnings in brackets.
[[nodiscard]] std::string loadWithDatabase(const ComponentPresetDatabase* database)
{
    ApplicationSetterFixture fixture;
    fixture.context().setComponentPresetDatabase(database);
    RocketComponent& tube = fixture.make(ComponentKind::BODY_TUBE);
    WarningSet       warnings;
    if (!applyKey(fixture, tube, "RocketComponent:preset", kBodyTubePreset, "", warnings))
    {
        return "no setter, or it failed";
    }
    return withWarnings(presetPartNoOf(tube), warnings);
}

// The product until it reads preset files (Milestone 3): OpenRocket with an empty preset
// database gives the same warning (the scouts' examples-no-presets.out).
TEST(ComponentPresetSetter, WithoutAPresetDatabaseOrWithAnEmptyOneNoPresetIsFound)
{
    const ComponentPresetDatabase empty;
    EXPECT_EQ(loadWithDatabase(nullptr),
              "null [No matching ComponentPreset for component Body Tube found matching Estes "
              "BT-50FE, 30359]");
    EXPECT_EQ(loadWithDatabase(&empty),
              "null [No matching ComponentPreset for component Body Tube found matching Estes "
              "BT-50FE, 30359]");
}

/// The part number of the preset a body tube keeps when the database it came from is gone.
[[nodiscard]] std::string partNoAfterTheDatabaseIsGone()
{
    ApplicationSetterFixture fixture;
    RocketComponent&         tube = fixture.make(ComponentKind::BODY_TUBE);
    WarningSet               warnings;
    {
        const ComponentPresetDatabase database = QtRocket::Test::makeExamplePresetDatabase();
        fixture.context().setComponentPresetDatabase(&database);
        if (!applyKey(fixture, tube, "RocketComponent:preset", kBodyTubePreset, "", warnings))
        {
            return "no setter, or it failed";
        }
        fixture.context().setComponentPresetDatabase(nullptr);
    }
    return withWarnings(presetPartNoOf(tube), warnings);
}

// The context's database is only read while a file loads: the component co-owns its preset.
TEST(ComponentPresetSetter, TheComponentSharesThePresetWithTheDatabase)
{
    EXPECT_EQ(partNoAfterTheDatabaseIsGone(), "BT-50FE, 30359");
}

/// What <preset> does in a rocket that is frozen: the part number of the tube's preset and
/// whether the rocket is still frozen, then the warnings in brackets.
[[nodiscard]] std::string loadIntoAFrozenRocket()
{
    ApplicationSetterFixture fixture;
    RocketComponent&         tube = fixture.make(ComponentKind::BODY_TUBE);
    WarningSet               warnings;
    fixture.rocket().freeze();
    const bool applied =
        applyKey(fixture, tube, "RocketComponent:preset", kBodyTubePreset, "", warnings);
    std::string told = listInOrder({presetPartNoOf(tube), flag(fixture.rocket().isFrozen())});
    fixture.rocket().thaw();
    return applied ? withWarnings(std::move(told), warnings) : "no setter, or it failed";
}

// No loader freezes the rocket (its events are on while a file loads). RocketComponent::
// loadPreset() has a BugError for a frozen rocket, which the setter must not run into.
TEST(ComponentPresetSetter, AFrozenRocketLoadsNoPreset)
{
    EXPECT_EQ(loadIntoAFrozenRocket(), "null, true [Invalid parameter encountered, ignoring.]");
}

/// The kind of component that takes a preset of @p type in the example designs.
[[nodiscard]] ComponentKind kindOf(ComponentPresetType type)
{
    switch (type)
    {
        case ComponentPresetType::PARACHUTE:
            return ComponentKind::PARACHUTE;
        case ComponentPresetType::NOSE_CONE:
            return ComponentKind::NOSE_CONE;
        default:
            return ComponentKind::BODY_TUBE;
    }
}

/// What the <preset> element @p reference of an example design gives a new component of its
/// kind, through the entry the walk for that kind finds: "<class of the entry> <digest of the
/// component's preset>", then the warnings in brackets.
[[nodiscard]] std::string loadExamplePreset(const ExamplePresetReference& reference)
{
    ApplicationSetterFixture           fixture;
    const ComponentKind                kind      = kindOf(reference.type);
    RocketComponent&                   component = fixture.make(kind);
    const DocumentConfig::SetterLookup lookup    = DocumentConfig::findSetter(kind, "preset");
    WarningSet                         warnings;
    const std::string                  attributes = std::format(
        "type={}|manufacturer={}|partno={}|digest={}", componentPresetTypeName(reference.type),
        reference.manufacturer, reference.partNo, reference.digest);
    if (lookup.setter == nullptr ||
        !lookup.setter->set(component, "", attributesOf(attributes), warnings, fixture.context())
             .has_value())
    {
        return "no setter, or it failed";
    }
    return withWarnings(std::format("{} {}", lookup.owner, presetDigestOf(component)), warnings);
}

/// loadExamplePreset() of every <preset> element of the example designs.
[[nodiscard]] Texts loadEveryExamplePreset()
{
    Texts loaded;
    for (const ExamplePresetReference& reference : kExamplePresetReferences)
    {
        loaded.push_back(loadExamplePreset(reference));
    }
    return loaded;
}

// The six <preset> elements of the 16 example designs, each through the entry the handler of a
// component's parameters will find for it: a parachute's own entry hides RocketComponent's.
TEST(ComponentPresetSetter, FindsEveryPresetOfTheExampleDesigns)
{
    EXPECT_EQ(loadEveryExamplePreset(),
              (Texts{"RocketComponent e9c3e97d32e96762f65e051d74cb9fd7",
                     "Parachute b595c8a31baaf325291d5c957f3940f8",
                     "Parachute 9a96b8806749e790db29bacfbc70eb1e",
                     "RocketComponent 18363dec5642206a109389ef48efcb32",
                     "RocketComponent a59dec8e4034a2fee5955dbf4ff07f1c",
                     "RocketComponent 6f564a198c80de3af437608827fa1bc1"}));
}

/// A parachute preset with a packed length and diameter, which none of the presets of the
/// example designs has: the preset the probe makes for its cases k000 to k004 (--packed), from
/// the same property values.
[[nodiscard]] std::shared_ptr<const ComponentPreset> makePackedPreset()
{
    TypedPropertyMap props;
    props.put(ComponentPreset::kLegacy, false);
    props.put(ComponentPreset::kManufacturer, Manufacturer::getManufacturer("Estes"));
    props.put(ComponentPreset::kPartNo, "PK-PACKED");
    props.put(ComponentPreset::kDescription, "Parachute with packed dimensions");
    props.put(
        ComponentPreset::kMaterial,
        Material::newMaterial(Material::Type::SURFACE, "Polyethylene film, HDPE, 1.0 mil, bare",
                              0.0235, MaterialGroup::OTHER, true, true));
    props.put(ComponentPreset::kType, ComponentPresetType::PARACHUTE);
    props.put(ComponentPreset::kDiameter, 0.3);
    props.put(ComponentPreset::kLineCount, 8);
    props.put(ComponentPreset::kLineLength, 0.35);
    props.put(ComponentPreset::kSides, 8);
    props.put(ComponentPreset::kLineMaterial,
              Material::newMaterial(Material::Type::LINE, "Carpet Thread", 3.3E-4,
                                    MaterialGroup::OTHER, true, true));
    props.put(ComponentPreset::kPackedLength, 0.04);
    props.put(ComponentPreset::kPackedDiameter, 0.02);
    const MaterialStorage materials;
    return std::make_shared<const ComponentPreset>(
        ComponentPresetFactory::create(props, materials).value());
}

/// What a parachute holds after <preset> of the packed preset through the entry @p key, behind
/// <packedradius> with @p radiusBefore when that is not empty: the part number of its preset,
/// its name, diameter, line count and line length, its packed radius, whether that is automatic
/// and its packed length; then the warnings in brackets.
[[nodiscard]] std::string loadThePackedPreset(std::string_view key, std::string_view radiusBefore)
{
    ApplicationSetterFixture                     fixture;
    const std::shared_ptr<const ComponentPreset> preset = makePackedPreset();
    fixture.presets().add(preset);
    RocketComponent&  chute = fixture.make(ComponentKind::PARACHUTE);
    WarningSet        warnings;
    const std::string attributes = std::format(
        "type=PARACHUTE|manufacturer=Estes|partno=PK-PACKED|digest={}", preset->getDigest());
    const bool radiusSet =
        radiusBefore.empty() ||
        applyKey(fixture, chute, "MassObject:packedradius", "", radiusBefore, warnings);
    if (!radiusSet || !applyKey(fixture, chute, key, attributes, "", warnings))
    {
        return "no setter, or it failed";
    }
    const auto& parachute = as<Parachute>(chute);
    // The packed radius before the packed length: asking for an automatic radius sets the length.
    return withWarnings(listInOrder({presetPartNoOf(chute), chute.getName(),
                                     num(parachute.getDiameter()), count(parachute.getLineCount()),
                                     num(parachute.getLineLength()), num(parachute.getRadius()),
                                     flag(parachute.isRadiusAutomatic()), num(chute.getLength())}),
                        warnings);
}

// The cases k000 to k004 of the probe. A parachute's entry loads its preset with Java's extra
// parameter `false`: the packed radius is the preset's and not automatic. Through the entry of
// RocketComponent, which no file reaches for a parachute, the preset makes it automatic.
TEST(ComponentPresetSetter, AParachutesEntryKeepsThePackedRadiusOfThePreset)
{
    EXPECT_EQ(makePackedPreset()->getDigest(), "1ea55ef70a493c644ee8b00ede13b1dc");
    EXPECT_EQ(loadThePackedPreset("Parachute:preset", ""),
              "PK-PACKED, Parachute, 0.3, 8, 0.35, 0.01, false, 0.04");
    EXPECT_EQ(loadThePackedPreset("RocketComponent:preset", ""),
              "PK-PACKED, Parachute, 0.3, 8, 0.35, 0.023, true, 0.007561436672967866");
    EXPECT_EQ(loadThePackedPreset("Parachute:preset", "auto 0.01"),
              "PK-PACKED, Parachute, 0.3, 8, 0.35, 0.01, false, 0.04");
    EXPECT_EQ(loadThePackedPreset("RocketComponent:preset", "auto 0.01"),
              "PK-PACKED, Parachute, 0.3, 8, 0.35, 0.023, true, 0.007561436672967866");
    EXPECT_EQ(loadThePackedPreset("Parachute:preset", "0.01"),
              "PK-PACKED, Parachute, 0.3, 8, 0.35, 0.01, false, 0.04");
}

/// A body tube preset whose material is the bulk material @p materialName of @p density: the
/// presets of the probe ShortMaterialProbe (tier 9b, the fixer of the rocket side), from the
/// same property values.
[[nodiscard]] std::shared_ptr<const ComponentPreset> makeTubePreset(std::string_view partNo,
                                                                    std::string_view materialName,
                                                                    double           density)
{
    TypedPropertyMap props;
    props.put(ComponentPreset::kLegacy, false);
    props.put(ComponentPreset::kManufacturer, Manufacturer::getManufacturer("Estes"));
    props.put(ComponentPreset::kPartNo, std::string(partNo));
    props.put(ComponentPreset::kDescription, std::format("Body tube {}", partNo));
    props.put(ComponentPreset::kType, ComponentPresetType::BODY_TUBE);
    props.put(ComponentPreset::kLength, 0.2);
    props.put(ComponentPreset::kOuterDiameter, 0.03);
    props.put(ComponentPreset::kInnerDiameter, 0.028);
    props.put(ComponentPreset::kMaterial,
              Material::newMaterial(Material::Type::BULK, std::string(materialName), density,
                                    MaterialGroup::OTHER, true, true));
    const MaterialStorage materials;
    return std::make_shared<const ComponentPreset>(
        ComponentPresetFactory::create(props, materials).value());
}

/// The digest of the preset makeTubePreset() makes and the length of its material's text as
/// Java counts it (Material.toString().length()).
[[nodiscard]] std::string tubePresetFacts(std::string_view partNo, std::string_view materialName,
                                          double density)
{
    const std::shared_ptr<const ComponentPreset> preset =
        makeTubePreset(partNo, materialName, density);
    return std::format(
        "{} {}", preset->getDigest(),
        QtRocket::Strings::javaLength(preset->get(ComponentPreset::kMaterial).toString()));
}

/// What a recovery device of @p kind holds after <preset> of the body tube preset
/// makeTubePreset() makes through the entry @p key: the part number of its preset, its name,
/// its length and its material; then the warnings in brackets.
[[nodiscard]] std::string loadATubePresetIntoADevice(std::string_view key, ComponentKind kind,
                                                     std::string_view partNo,
                                                     std::string_view materialName, double density)
{
    ApplicationSetterFixture                     fixture;
    const std::shared_ptr<const ComponentPreset> preset =
        makeTubePreset(partNo, materialName, density);
    fixture.presets().add(preset);
    RocketComponent&  device = fixture.make(kind);
    WarningSet        warnings;
    const std::string attributes = std::format(
        "type=BODY_TUBE|manufacturer=Estes|partno={}|digest={}", partNo, preset->getDigest());
    if (!applyKey(fixture, device, key, attributes, "", warnings))
    {
        return "no setter, or it failed";
    }
    return withWarnings(
        listInOrder({presetPartNoOf(device), device.getName(), num(device.getLength()),
                     as<QtRocket::RecoveryDevice>(device).getMaterial().toStorableString()}),
        warnings);
}

// The review's finding: the setter refused every preset whose material is no surface material
// for a parachute or streamer. OpenRocket's devices (and RecoveryDevice::loadFromPreset()) take
// a preset's material only when its text, "name (density)", is longer than 12 characters; a
// preset with a shorter one is loaded whatever the material's type, and the device keeps its
// default material. Pinned with OpenRocket (ShortMaterialProbe.out): texts of 11 and 12
// characters load, texts of 13 and 22 end in its ClassCastException.
TEST(ComponentPresetSetter, ARecoveryDeviceTakesAPresetWhoseShortMaterialItPassesOver)
{
    EXPECT_EQ(tubePresetFacts("BT-SHORT", "A", 0.0), "5f37a9028648c49d5ed3b959a1a787c3 11");
    EXPECT_EQ(tubePresetFacts("BT-TWELVE", "Ab", 0.0), "fb3eae768385e4feeeb2ff2cabcc044b 12");

    constexpr std::string_view kNylon = "SURFACE|Ripstop nylon|0.067|0.0|Fabrics";
    EXPECT_EQ(loadATubePresetIntoADevice("Parachute:preset", ComponentKind::PARACHUTE, "BT-SHORT",
                                         "A", 0.0),
              std::format("BT-SHORT, Parachute, 0.2, {}", kNylon));
    EXPECT_EQ(loadATubePresetIntoADevice("RocketComponent:preset", ComponentKind::STREAMER,
                                         "BT-SHORT", "A", 0.0),
              std::format("BT-SHORT, Streamer, 0.05, {}", kNylon));
    EXPECT_EQ(loadATubePresetIntoADevice("Parachute:preset", ComponentKind::PARACHUTE, "BT-TWELVE",
                                         "Ab", 0.0),
              std::format("BT-TWELVE, Parachute, 0.2, {}", kNylon));
    EXPECT_EQ(loadATubePresetIntoADevice("RocketComponent:preset", ComponentKind::STREAMER,
                                         "BT-TWELVE", "Ab", 0.0),
              std::format("BT-TWELVE, Streamer, 0.05, {}", kNylon));
}

// One character more, and the device would take the material: a bulk material, of which
// OpenRocket dies (with the preset's length of 0.2 set already) and which is refused here
// before anything is loaded, so the length stays the device's 0.025.
TEST(ComponentPresetSetter, ARecoveryDeviceIsNotGivenAPresetWhoseLongerMaterialDoesNotFit)
{
    EXPECT_EQ(tubePresetFacts("BT-THIRTEEN", "Abc", 0.0), "70cf22c9b062f0b346f760c5cbcd31e8 13");
    EXPECT_EQ(tubePresetFacts("BT-LONG", "Cardboard", 680.0),
              "0c6814453f6f6eeb0838d327a6426dfd 22");

    constexpr std::string_view kRefused =
        "0.025, SURFACE|Ripstop nylon|0.067|0.0|Fabrics [Invalid parameter encountered, ignoring.]";
    EXPECT_EQ(loadATubePresetIntoADevice("Parachute:preset", ComponentKind::PARACHUTE,
                                         "BT-THIRTEEN", "Abc", 0.0),
              std::format("null, Parachute, {}", kRefused));
    EXPECT_EQ(loadATubePresetIntoADevice("RocketComponent:preset", ComponentKind::STREAMER,
                                         "BT-THIRTEEN", "Abc", 0.0),
              std::format("null, Streamer, {}", kRefused));
    EXPECT_EQ(loadATubePresetIntoADevice("Parachute:preset", ComponentKind::PARACHUTE, "BT-LONG",
                                         "Cardboard", 680.0),
              std::format("null, Parachute, {}", kRefused));
    EXPECT_EQ(loadATubePresetIntoADevice("RocketComponent:preset", ComponentKind::STREAMER,
                                         "BT-LONG", "Cardboard", 680.0),
              std::format("null, Streamer, {}", kRefused));
}

/// What a setter of the test's own, whose function only notes the preset it is handed, does
/// with the body tube's <preset>: the part number it was handed, or "nothing".
[[nodiscard]] std::string presetHandedOver()
{
    std::string                 handed = "nothing";
    const ComponentPresetSetter setter(
        [&handed](RocketComponent& /*component*/,
                  const std::shared_ptr<const ComponentPreset>& preset) {
            handed = preset->getPartNo();
        });
    ApplicationSetterFixture fixture;
    WarningSet               warnings;
    if (!setter
             .set(fixture.setters().tube(), "", attributesOf(kBodyTubePreset), warnings,
                  fixture.context())
             .has_value())
    {
        return "the setter failed";
    }
    return withWarnings(std::move(handed), warnings);
}

TEST(ComponentPresetSetter, HandsThePresetItFoundToItsFunction)
{
    EXPECT_EQ(presetHandedOver(), "BT-50FE, 30359");
    EXPECT_THROW(ComponentPresetSetter(ComponentPresetSetter::LoadFunction{}), BugError);
}

}  // namespace
