#include "QtRocket/file/openrocket/FinTabPositionSetter.h"

#include <array>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/logging/WarningSet.h"
#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/EllipticalFinSet.h"
#include "QtRocket/rocket/FreeformFinSet.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "QtRocket/rocket/TrapezoidFinSet.h"
#include "QtRocket/rocket/position/AxialMethod.h"
#include "QtRocket/util/BugError.h"
#include "QtRocket/util/Error.h"
#include "file/openrocket/SetterTestSupport.h"

// What <tabposition> does to a fin set, as OpenRocket's FinTabPositionSetter does it. kJava
// holds OpenRocket's answers (the probe SpecialSetterProbe of tier 9b, part R2; see
// SetterTestSupport.h): the method, the offset and the front edge of the tab (getTabOffsetMethod,
// getTabOffset, getTabFrontEdge) after the elements of a row, and the warnings. Most rows give
// the fin set a tab of 0.02 m by 0.01 m first; its root chord is 0.05 m.

namespace
{

using QtRocket::BugError;
using QtRocket::ComponentKind;
using QtRocket::EllipticalFinSet;
using QtRocket::FinTabPositionSetter;
using QtRocket::FreeformFinSet;
using QtRocket::Result;
using QtRocket::RocketComponent;
using QtRocket::TrapezoidFinSet;
using QtRocket::WarningSet;
using QtRocket::Test::ApplicationSetterFixture;
using QtRocket::Test::applyByHand;
using QtRocket::Test::as;
using QtRocket::Test::asText;
using QtRocket::Test::attributesOf;
using QtRocket::Test::checkSetterScripts;
using QtRocket::Test::listInOrder;
using QtRocket::Test::num;
using QtRocket::Test::SetterScript;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_r2_tests.py of the probe: the readers
[[nodiscard]] std::string readTrapezoidFinSet(ApplicationSetterFixture& /*fixture*/,
                                              const RocketComponent& c)
{
    return listInOrder({asText(axialMethodName(as<TrapezoidFinSet>(c).getTabOffsetMethod())),
                        num(as<TrapezoidFinSet>(c).getTabOffset()),
                        num(as<TrapezoidFinSet>(c).getTabFrontEdge())});
}

[[nodiscard]] std::string readEllipticalFinSet(ApplicationSetterFixture& /*fixture*/,
                                               const RocketComponent& c)
{
    return listInOrder({asText(axialMethodName(as<EllipticalFinSet>(c).getTabOffsetMethod())),
                        num(as<EllipticalFinSet>(c).getTabOffset()),
                        num(as<EllipticalFinSet>(c).getTabFrontEdge())});
}

[[nodiscard]] std::string readFreeformFinSet(ApplicationSetterFixture& /*fixture*/,
                                             const RocketComponent& c)
{
    return listInOrder({asText(axialMethodName(as<FreeformFinSet>(c).getTabOffsetMethod())),
                        num(as<FreeformFinSet>(c).getTabOffset()),
                        num(as<FreeformFinSet>(c).getTabFrontEdge())});
}

// ---- generated: OpenRocket's answers, one row per case of the probe
// clang-format off
constexpr auto kJava = std::to_array<SetterScript>({
    {.id = "x492", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x493", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=middle", .text = "0.0"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001"},
    {.id = "x494", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=bottom", .text = "-0.01"}}}, .read = &readTrapezoidFinSet, .expected = "BOTTOM, -0.009999999999999998, 0.020000000000000004"},
    {.id = "x495", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=front", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x496", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=center", .text = "0.005"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.004999999999999999, 0.02"},
    {.id = "x497", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=end", .text = "-0.01"}}}, .read = &readTrapezoidFinSet, .expected = "BOTTOM, -0.009999999999999998, 0.020000000000000004"},
    {.id = "x498", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001", .warnings = "Required attribute 'relativeto' not found for fin tab position."},
    {.id = "x499", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=weird", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001", .warnings = "Illegal attribute value 'weird' encountered."},
    {.id = "x500", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=absolute", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "ABSOLUTE, 0.01, 0.01"},
    {.id = "x501", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=after", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "AFTER, 0.010000000000000002, 0.060000000000000005"},
    {.id = "x502", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto= top ", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x503", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=TOP", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001", .warnings = "Illegal attribute value 'TOP' encountered."},
    {.id = "x504", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=frontend", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x505", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=the end", .text = "-0.01"}}}, .read = &readTrapezoidFinSet, .expected = "BOTTOM, -0.009999999999999998, 0.020000000000000004"},
    {.id = "x506", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=centered", .text = "0.004"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.004000000000000002, 0.019000000000000003"},
    {.id = "x507", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=endcenter", .text = "0.003"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.003000000000000001, 0.018000000000000002"},
    {.id = "x508", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=FRONT", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001", .warnings = "Illegal attribute value 'FRONT' encountered."},
    {.id = "x509", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001", .warnings = "Illegal attribute value '' encountered."},
    {.id = "x510", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto= front ", .text = "0.012"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.012, 0.012"},
    {.id = "x511", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "method=top", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001", .warnings = "Required attribute 'relativeto' not found for fin tab position."},
    {.id = "x512", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "abc"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.015000000000000001, 0.015000000000000001", .warnings = "Invalid parameter encountered, ignoring. data: 'abc' - Trapezoidal Fin Set"},
    {.id = "x513", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=bottom", .text = "NaN"}}}, .read = &readTrapezoidFinSet, .expected = "BOTTOM, -0.015000000000000001, 0.015000000000000001", .warnings = "Invalid parameter encountered, ignoring. data: 'NaN' - Trapezoidal Fin Set"},
    {.id = "x514", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=middle", .text = "Infinity"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001", .warnings = "Invalid parameter encountered, ignoring. data: 'Infinity' - Trapezoidal Fin Set"},
    {.id = "x515", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = " 0.011 "}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.011, 0.011"},
    {.id = "x516", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.015000000000000001, 0.015000000000000001", .warnings = "Invalid parameter encountered, ignoring. data: '' - Trapezoidal Fin Set"},
    {.id = "x517", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=bottom", .text = "auto"}}}, .read = &readTrapezoidFinSet, .expected = "BOTTOM, -0.015000000000000001, 0.015000000000000001", .warnings = "Invalid parameter encountered, ignoring. data: 'auto' - Trapezoidal Fin Set"},
    {.id = "x518", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "1e-1d"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.1, 0.1"},
    {.id = "x519", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "0.2"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.2, 0.2"},
    {.id = "x520", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "-0.2"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, -0.2, -0.2"},
    {.id = "x521", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=end", .text = "-0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=bottom", .text = "-0.01"}}}, .read = &readTrapezoidFinSet, .expected = "BOTTOM, -0.009999999999999998, 0.020000000000000004"},
    {.id = "x522", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=front", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=weird", .text = "0.02"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.01, 0.01", .warnings = "Illegal attribute value 'weird' encountered."},
    {.id = "x523", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x524", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:tabposition", .attributes = "relativeto=middle", .text = "0.01"}}}, .read = &readTrapezoidFinSet, .expected = "MIDDLE, 0.01, 0.01"},
    {.id = "x525", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "0.01"}}}, .read = &readEllipticalFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x526", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=middle", .text = "0.0"}}}, .read = &readEllipticalFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001"},
    {.id = "x527", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=bottom", .text = "-0.01"}}}, .read = &readEllipticalFinSet, .expected = "BOTTOM, -0.009999999999999998, 0.020000000000000004"},
    {.id = "x528", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=front", .text = "0.01"}}}, .read = &readEllipticalFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x529", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=center", .text = "0.005"}}}, .read = &readEllipticalFinSet, .expected = "MIDDLE, 0.004999999999999999, 0.02"},
    {.id = "x558", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=top", .text = "0.01"}}}, .read = &readFreeformFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x559", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=middle", .text = "0.0"}}}, .read = &readFreeformFinSet, .expected = "MIDDLE, 0.0, 0.015000000000000001"},
    {.id = "x560", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=bottom", .text = "-0.01"}}}, .read = &readFreeformFinSet, .expected = "BOTTOM, -0.009999999999999998, 0.020000000000000004"},
    {.id = "x561", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=front", .text = "0.01"}}}, .read = &readFreeformFinSet, .expected = "TOP, 0.01, 0.01"},
    {.id = "x562", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:tablength", .text = "0.02"}, {.key = "FinSet:tabheight", .text = "0.01"}, {.key = "FinSet:tabposition", .attributes = "relativeto=center", .text = "0.005"}}}, .read = &readFreeformFinSet, .expected = "MIDDLE, 0.004999999999999999, 0.02"},
});
// clang-format on
// ---- end of the generated part

TEST(FinTabPositionSetter, DoesWithEveryElementWhatOpenRocketDoes)
{
    EXPECT_EQ(checkSetterScripts(kJava), Texts{});
}

// The cases x523 and x524 of the probe, through a setter of the test's own. A new fin set has no
// tab, and its tab is placed along a root of length 0 until something sets the fin's length.
TEST(FinTabPositionSetter, SetsTheMethodAndThenTheOffset)
{
    const FinTabPositionSetter setter;
    EXPECT_EQ(applyByHand(setter, ComponentKind::TRAPEZOID_FIN_SET, "relativeto=top", "0.01",
                          &readTrapezoidFinSet),
              "TOP, 0.01, 0.01");
    EXPECT_EQ(applyByHand(setter, ComponentKind::TRAPEZOID_FIN_SET, "relativeto=middle", "0.01",
                          &readTrapezoidFinSet),
              "MIDDLE, 0.01, 0.01");
}

/// What the setter does with a component of @p kind that is no fin set: the message of the
/// BugError, or "no BugError".
[[nodiscard]] std::string setTheTabOf(ComponentKind kind, std::string_view attributes)
{
    ApplicationSetterFixture   fixture;
    RocketComponent&           component = fixture.make(kind);
    WarningSet                 warnings;
    const FinTabPositionSetter setter;
    try
    {
        const Result<void> result =
            setter.set(component, "0.01", attributesOf(attributes), warnings, fixture.context());
        return result.has_value() ? "no BugError" : "failed";
    }
    catch (const BugError& error)
    {
        return error.what();
    }
}

// OpenRocket: an IllegalStateException "FinTabPositionSetter called for component Body Tube",
// before it looks at the attribute. The walk of the setter table cannot bring it about.
TEST(FinTabPositionSetter, AComponentThatIsNoFinSetIsAProgrammingError)
{
    EXPECT_NE(setTheTabOf(ComponentKind::BODY_TUBE, "relativeto=top")
                  .find("FinTabPositionSetter called for component Body Tube"),
              std::string::npos);
    EXPECT_NE(setTheTabOf(ComponentKind::BODY_TUBE, "")
                  .find("FinTabPositionSetter called for component Body Tube"),
              std::string::npos);
    // A tube fin set is no fin set.
    EXPECT_NE(setTheTabOf(ComponentKind::TUBE_FIN_SET, "relativeto=top")
                  .find("FinTabPositionSetter called for component Tube Fin Set"),
              std::string::npos);
}

}  // namespace
