#include "QtRocket/file/openrocket/MaterialSetter.h"

#include <array>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/file/openrocket/Setter.h"
#include "QtRocket/logging/WarningSet.h"
#include "QtRocket/material/Material.h"
#include "QtRocket/rocket/BodyTube.h"
#include "QtRocket/rocket/Bulkhead.h"
#include "QtRocket/rocket/CenteringRing.h"
#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/EllipticalFinSet.h"
#include "QtRocket/rocket/EngineBlock.h"
#include "QtRocket/rocket/FreeformFinSet.h"
#include "QtRocket/rocket/InnerTube.h"
#include "QtRocket/rocket/LaunchLug.h"
#include "QtRocket/rocket/NoseCone.h"
#include "QtRocket/rocket/Parachute.h"
#include "QtRocket/rocket/RailButton.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "QtRocket/rocket/ShockCord.h"
#include "QtRocket/rocket/Streamer.h"
#include "QtRocket/rocket/TrapezoidFinSet.h"
#include "QtRocket/rocket/TubeCoupler.h"
#include "QtRocket/rocket/TubeFinSet.h"
#include "QtRocket/util/BugError.h"
#include "file/openrocket/SetterTestSupport.h"

// What <material>, <filletmaterial> and <linematerial> do to a component, as OpenRocket's
// MaterialSetter does it. kJava holds OpenRocket's answers (the probe SpecialSetterProbe of
// tier 9b, part R2; see SetterTestSupport.h). A row applies its elements through the entries of
// the setter table to a new component in a document, and compares the component's material (its
// storable string "TYPE|name|density|shear modulus|group", whether it is user-defined and
// whether it is a material of the document), the materials the document holds afterwards, in
// the order a save writes them, and the warnings.
//
// The application's materials are OpenRocket's built-in ones, as in the probe. A new body tube
// is of "Cardboard", a shock cord and a parachute's lines of "Elastic cord (round 2 mm, 1/16
// in)" and a parachute or streamer of "Ripstop nylon".

namespace
{

using QtRocket::BodyTube;
using QtRocket::BugError;
using QtRocket::Bulkhead;
using QtRocket::CenteringRing;
using QtRocket::ComponentKind;
using QtRocket::EllipticalFinSet;
using QtRocket::EngineBlock;
using QtRocket::FreeformFinSet;
using QtRocket::InnerTube;
using QtRocket::LaunchLug;
using QtRocket::Material;
using QtRocket::MaterialSetter;
using QtRocket::NoseCone;
using QtRocket::Parachute;
using QtRocket::RailButton;
using QtRocket::RocketComponent;
using QtRocket::Setter;
using QtRocket::ShockCord;
using QtRocket::Streamer;
using QtRocket::TrapezoidFinSet;
using QtRocket::TubeCoupler;
using QtRocket::TubeFinSet;
using QtRocket::WarningSet;
using QtRocket::Test::ApplicationSetterFixture;
using QtRocket::Test::as;
using QtRocket::Test::attributesOf;
using QtRocket::Test::checkSetterScripts;
using QtRocket::Test::describeMaterial;
using QtRocket::Test::documentMaterialsOf;
using QtRocket::Test::flag;
using QtRocket::Test::listInOrder;
using QtRocket::Test::setterOfKey;
using QtRocket::Test::SetterScript;
using QtRocket::Test::withWarnings;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_r2_tests.py of the probe: the readers
[[nodiscard]] std::string readBodyTube(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<BodyTube>(c).getMaterial().toStorableString(),
                        flag(as<BodyTube>(c).getMaterial().isUserDefined()),
                        flag(as<BodyTube>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readLaunchLug(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<LaunchLug>(c).getMaterial().toStorableString(),
                        flag(as<LaunchLug>(c).getMaterial().isUserDefined()),
                        flag(as<LaunchLug>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readNoseCone(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<NoseCone>(c).getMaterial().toStorableString(),
                        flag(as<NoseCone>(c).getMaterial().isUserDefined()),
                        flag(as<NoseCone>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTrapezoidFinSet(ApplicationSetterFixture& fixture,
                                              const RocketComponent&    c)
{
    return listInOrder({as<TrapezoidFinSet>(c).getMaterial().toStorableString(),
                        flag(as<TrapezoidFinSet>(c).getMaterial().isUserDefined()),
                        flag(as<TrapezoidFinSet>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readRailButton(ApplicationSetterFixture& fixture,
                                         const RocketComponent&    c)
{
    return listInOrder({as<RailButton>(c).getMaterial().toStorableString(),
                        flag(as<RailButton>(c).getMaterial().isUserDefined()),
                        flag(as<RailButton>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTubeFinSet(ApplicationSetterFixture& fixture,
                                         const RocketComponent&    c)
{
    return listInOrder({as<TubeFinSet>(c).getMaterial().toStorableString(),
                        flag(as<TubeFinSet>(c).getMaterial().isUserDefined()),
                        flag(as<TubeFinSet>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTrapezoidFinSetB(ApplicationSetterFixture& fixture,
                                               const RocketComponent&    c)
{
    return listInOrder({as<TrapezoidFinSet>(c).getFilletMaterial().toStorableString(),
                        flag(as<TrapezoidFinSet>(c).getFilletMaterial().isUserDefined()),
                        flag(as<TrapezoidFinSet>(c).getFilletMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readEllipticalFinSet(ApplicationSetterFixture& fixture,
                                               const RocketComponent&    c)
{
    return listInOrder({as<EllipticalFinSet>(c).getFilletMaterial().toStorableString(),
                        flag(as<EllipticalFinSet>(c).getFilletMaterial().isUserDefined()),
                        flag(as<EllipticalFinSet>(c).getFilletMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readFreeformFinSet(ApplicationSetterFixture& fixture,
                                             const RocketComponent&    c)
{
    return listInOrder({as<FreeformFinSet>(c).getFilletMaterial().toStorableString(),
                        flag(as<FreeformFinSet>(c).getFilletMaterial().isUserDefined()),
                        flag(as<FreeformFinSet>(c).getFilletMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readCenteringRing(ApplicationSetterFixture& fixture,
                                            const RocketComponent&    c)
{
    return listInOrder({as<CenteringRing>(c).getMaterial().toStorableString(),
                        flag(as<CenteringRing>(c).getMaterial().isUserDefined()),
                        flag(as<CenteringRing>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readInnerTube(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<InnerTube>(c).getMaterial().toStorableString(),
                        flag(as<InnerTube>(c).getMaterial().isUserDefined()),
                        flag(as<InnerTube>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readBulkhead(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<Bulkhead>(c).getMaterial().toStorableString(),
                        flag(as<Bulkhead>(c).getMaterial().isUserDefined()),
                        flag(as<Bulkhead>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readTubeCoupler(ApplicationSetterFixture& fixture,
                                          const RocketComponent&    c)
{
    return listInOrder({as<TubeCoupler>(c).getMaterial().toStorableString(),
                        flag(as<TubeCoupler>(c).getMaterial().isUserDefined()),
                        flag(as<TubeCoupler>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readEngineBlock(ApplicationSetterFixture& fixture,
                                          const RocketComponent&    c)
{
    return listInOrder({as<EngineBlock>(c).getMaterial().toStorableString(),
                        flag(as<EngineBlock>(c).getMaterial().isUserDefined()),
                        flag(as<EngineBlock>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readShockCord(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<ShockCord>(c).getMaterial().toStorableString(),
                        flag(as<ShockCord>(c).getMaterial().isUserDefined()),
                        flag(as<ShockCord>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readParachute(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<Parachute>(c).getMaterial().toStorableString(),
                        flag(as<Parachute>(c).getMaterial().isUserDefined()),
                        flag(as<Parachute>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readStreamer(ApplicationSetterFixture& fixture, const RocketComponent& c)
{
    return listInOrder({as<Streamer>(c).getMaterial().toStorableString(),
                        flag(as<Streamer>(c).getMaterial().isUserDefined()),
                        flag(as<Streamer>(c).getMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

[[nodiscard]] std::string readParachuteB(ApplicationSetterFixture& fixture,
                                         const RocketComponent&    c)
{
    return listInOrder({as<Parachute>(c).getLineMaterial().toStorableString(),
                        flag(as<Parachute>(c).getLineMaterial().isUserDefined()),
                        flag(as<Parachute>(c).getLineMaterial().isDocumentMaterial()),
                        documentMaterialsOf(fixture.document())});
}

// ---- generated: OpenRocket's answers, one row per case of the probe
// clang-format off
constexpr auto kJava = std::to_array<SetterScript>({
    {.id = "m000", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=680.0|group=PaperProducts", .text = "Cardboard"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, "},
    {.id = "m001", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m002", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearModulus=2.3E8|group=Woods", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m003", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170", .text = " balsa "}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m004", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0", .text = "BALSA"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m005", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=171.0", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|171.0|0.0|Custom, true, true, BULK|Balsa|171.0|0.0|Custom"},
    {.id = "m006", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearModulus=1.0E8", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|1.0E8|Custom, true, true, BULK|Balsa|170.0|1.0E8|Custom"},
    {.id = "m007", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearModulus=xx", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|0.0|Custom, true, true, BULK|Balsa|170.0|0.0|Custom", .warnings = "Illegal shear modulus value, using 0.0."},
    {.id = "m008", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearModulus=", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|0.0|Custom, true, true, BULK|Balsa|170.0|0.0|Custom", .warnings = "Illegal shear modulus value, using 0.0."},
    {.id = "m011", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearModulus= 2.3E8 ", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m012", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearmodulus=1.0E8", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m013", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|0.0|Custom, true, true, BULK|MyMat|123.0|0.0|Custom"},
    {.id = "m014", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0|shearModulus=5.0E7", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|5.0E7|Custom, true, true, BULK|MyMat|123.0|5.0E7|Custom"},
    {.id = "m015", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0|group=Woods", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|0.0|Woods, true, true, BULK|MyMat|123.0|0.0|Woods"},
    {.id = "m016", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0|group=Custom", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|0.0|Custom, true, true, BULK|MyMat|123.0|0.0|Custom"},
    {.id = "m017", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0|group=Other", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|0.0|Other, true, true, BULK|MyMat|123.0|0.0|Other"},
    {.id = "m018", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0|group=Bogus", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|0.0|Custom, true, true, BULK|MyMat|123.0|0.0|Custom", .warnings = "Illegal material group specified, ignoring."},
    {.id = "m019", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0|group=", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|0.0|Custom, true, true, BULK|MyMat|123.0|0.0|Custom", .warnings = "Illegal material group specified, ignoring."},
    {.id = "m020", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=123.0|group=ThreadsLines", .text = "MyMat"}}}, .read = &readBodyTube, .expected = "BULK|MyMat|123.0|0.0|Other, true, true, BULK|MyMat|123.0|0.0|Other"},
    {.id = "m021", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|group=Bogus", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, ", .warnings = "Illegal material group specified, ignoring."},
    {.id = "m022", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|group=Metals", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m023", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=abc", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m024", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m025", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=line|density=100", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m026", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=surface|density=100", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m027", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=BULK|density=100", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m028", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type= bulk |density=100", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m029", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=|density=100", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m030", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=custom|density=100", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m031", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = " "}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m032", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m033", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m034", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m035", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Foo|100.0|0.0|Custom, true, true, BULK|Foo|100.0|0.0|Custom"},
    {.id = "m036", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density= 100 ", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Foo|100.0|0.0|Custom, true, true, BULK|Foo|100.0|0.0|Custom"},
    {.id = "m037", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=1e2d", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Foo|100.0|0.0|Custom, true, true, BULK|Foo|100.0|0.0|Custom"},
    {.id = "m041", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=-5", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Foo|-5.0|0.0|Custom, true, true, BULK|Foo|-5.0|0.0|Custom"},
    {.id = "m042", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=0", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Foo|0.0|0.0|Custom, true, true, BULK|Foo|0.0|0.0|Custom"},
    {.id = "m043", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=1250.0", .text = "PLA"}}}, .read = &readBodyTube, .expected = "BULK|PLA - 100% infill|1250.0|2.4E9|Plastics, false, false, "},
    {.id = "m044", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=1250.0", .text = "PLA - 100% infill"}}}, .read = &readBodyTube, .expected = "BULK|PLA - 100% infill|1250.0|2.4E9|Plastics, false, false, "},
    {.id = "m045", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=2700", .text = " aluminum"}}}, .read = &readBodyTube, .expected = "BULK|Aluminum|2700.0|2.6E10|Metals, false, false, "},
    {.id = "m046", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100|extra=1|thickness=x", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Foo|100.0|0.0|Custom, true, true, BULK|Foo|100.0|0.0|Custom"},
    {.id = "m047", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = "a|b"}}}, .read = &readBodyTube, .expected = "BULK|a b|100.0|0.0|Custom, true, true, BULK|a b|100.0|0.0|Custom"},
    {.id = "m048", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = "  Two  words  "}}}, .read = &readBodyTube, .expected = "BULK|Two  words|100.0|0.0|Custom, true, true, BULK|Two  words|100.0|0.0|Custom"},
    {.id = "m049", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=line|density=abc", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m050", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=line|density=100", .text = " "}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    {.id = "m051", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=line|density=100|shearModulus=xx", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal shear modulus value, using 0.0. | Illegal material type specified, ignoring."},
    {.id = "m052", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=100|shearModulus=xx|group=Bogus", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Foo|100.0|0.0|Custom, true, true, BULK|Foo|100.0|0.0|Custom", .warnings = "Illegal shear modulus value, using 0.0. | Illegal material group specified, ignoring."},
    {.id = "m053", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = "Zeta"}, {.key = "ExternalComponent:material", .attributes = "density=200", .text = "Alpha"}}}, .read = &readBodyTube, .expected = "BULK|Alpha|200.0|0.0|Custom, true, true, BULK|Alpha|200.0|0.0|Custom; BULK|Zeta|100.0|0.0|Custom"},
    {.id = "m054", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = "Same"}, {.key = "ExternalComponent:material", .attributes = "density=100|group=Woods", .text = "Same"}}}, .read = &readBodyTube, .expected = "BULK|Same|100.0|0.0|Woods, true, true, BULK|Same|100.0|0.0|Custom; BULK|Same|100.0|0.0|Woods"},
    {.id = "m055", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100|group=Woods", .text = "Same"}, {.key = "ExternalComponent:material", .attributes = "density=100", .text = "Same"}}}, .read = &readBodyTube, .expected = "BULK|Same|100.0|0.0|Custom, true, true, BULK|Same|100.0|0.0|Woods; BULK|Same|100.0|0.0|Custom"},
    {.id = "m056", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = "Same"}, {.key = "ExternalComponent:material", .attributes = "density=100|shearModulus=5", .text = "Same"}}}, .read = &readBodyTube, .expected = "BULK|Same|100.0|5.0|Custom, true, true, BULK|Same|100.0|0.0|Custom; BULK|Same|100.0|5.0|Custom"},
    {.id = "m057", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=100", .text = "Foo"}, {.key = "ExternalComponent:material", .attributes = "density=170.0", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, BULK|Foo|100.0|0.0|Custom"},
    {.id = "m058", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=1850.0", .text = "Fiberglass"}}}, .read = &readLaunchLug, .expected = "BULK|Fiberglass|1850.0|4.14E9|Composites, false, false, "},
    {.id = "m059", .kind = ComponentKind::NOSE_CONE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=55.5", .text = "Foam of mine"}}}, .read = &readNoseCone, .expected = "BULK|Foam of mine|55.5|0.0|Custom, true, true, BULK|Foam of mine|55.5|0.0|Custom"},
    {.id = "m060", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=630.0", .text = "Plywood (birch)"}}}, .read = &readTrapezoidFinSet, .expected = "BULK|Plywood (birch)|630.0|6.13E8|Woods, false, false, "},
    {.id = "m061", .kind = ComponentKind::RAIL_BUTTON, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=2700.0", .text = "Aluminum"}}}, .read = &readRailButton, .expected = "BULK|Aluminum|2700.0|2.6E10|Metals, false, false, "},
    {.id = "m062", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=950.0", .text = "Kraft phenolic"}}}, .read = &readTubeFinSet, .expected = "BULK|Kraft phenolic|950.0|1.78E9|Composites, false, false, "},
    {.id = "m063", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:filletmaterial", .attributes = "type=bulk|density=1250.0", .text = "Epoxy of mine"}}}, .read = &readTrapezoidFinSetB, .expected = "BULK|Epoxy of mine|1250.0|0.0|Custom, true, true, "},
    {.id = "m064", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:filletmaterial", .attributes = "type=bulk|density=170.0", .text = "Balsa"}}}, .read = &readEllipticalFinSet, .expected = "BULK|Balsa|170.0|2.3E8|Woods, false, false, "},
    {.id = "m065", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:filletmaterial", .attributes = "type=line|density=170.0", .text = "Balsa"}}}, .read = &readFreeformFinSet, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m066", .kind = ComponentKind::CENTERING_RING, .steps = {{{.key = "StructuralComponent:material", .attributes = "type=bulk|density=630.0", .text = "Plywood (birch)"}}}, .read = &readCenteringRing, .expected = "BULK|Plywood (birch)|630.0|6.13E8|Woods, false, false, "},
    {.id = "m067", .kind = ComponentKind::INNER_TUBE, .steps = {{{.key = "StructuralComponent:material", .attributes = "type=bulk|density=77.0", .text = "Tube stuff"}}}, .read = &readInnerTube, .expected = "BULK|Tube stuff|77.0|0.0|Custom, true, true, BULK|Tube stuff|77.0|0.0|Custom"},
    {.id = "m068", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "StructuralComponent:material", .attributes = "type=surface|density=77.0", .text = "Tube stuff"}}}, .read = &readBulkhead, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m069", .kind = ComponentKind::TUBE_COUPLER, .steps = {{{.key = "StructuralComponent:material", .attributes = "density=1300.0", .text = "Blue tube"}}}, .read = &readTubeCoupler, .expected = "BULK|Blue tube|1300.0|0.0|Composites, false, false, "},
    {.id = "m070", .kind = ComponentKind::ENGINE_BLOCK, .steps = {{{.key = "StructuralComponent:material", .attributes = "density=680.0", .text = "Cardboard"}}}, .read = &readEngineBlock, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, "},
    {.id = "m071", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "ShockCord:material", .attributes = "type=line|density=0.0018", .text = "Elastic cord (round 2mm, 1/16 in)"}}}, .read = &readShockCord, .expected = "LINE|Elastic cord (round 2mm, 1/16 in)|0.0018|0.0|Custom, true, true, "},
    {.id = "m072", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "ShockCord:material", .attributes = "type=line|density=0.0018|group=ThreadsLines", .text = "Elastic cord (round 2mm, 1/16 in)"}}}, .read = &readShockCord, .expected = "LINE|Elastic cord (round 2mm, 1/16 in)|0.0018|0.0|Other, true, true, "},
    {.id = "m073", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "ShockCord:material", .attributes = "type=line|density=0.005|group=ThreadsLines", .text = "Cord of mine"}}}, .read = &readShockCord, .expected = "LINE|Cord of mine|0.005|0.0|Other, true, true, "},
    {.id = "m074", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "ShockCord:material", .attributes = "type=line|density=0.005", .text = "Cord of mine"}}}, .read = &readShockCord, .expected = "LINE|Cord of mine|0.005|0.0|Custom, true, true, "},
    {.id = "m075", .kind = ComponentKind::SHOCK_CORD, .steps = {{{.key = "ShockCord:material", .attributes = "type=bulk|density=0.005", .text = "Cord of mine"}}}, .read = &readShockCord, .expected = "LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m076", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "RecoveryDevice:material", .attributes = "type=surface|density=0.021", .text = "Mylar"}}}, .read = &readParachute, .expected = "SURFACE|Mylar|0.021|0.0|Plastics, false, false, "},
    {.id = "m077", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RecoveryDevice:material", .attributes = "type=surface|density=0.5", .text = "Sail cloth"}}}, .read = &readStreamer, .expected = "SURFACE|Sail cloth|0.5|0.0|Custom, true, true, SURFACE|Sail cloth|0.5|0.0|Custom"},
    {.id = "m078", .kind = ComponentKind::STREAMER, .steps = {{{.key = "RecoveryDevice:material", .attributes = "type=bulk|density=0.5", .text = "Sail cloth"}}}, .read = &readStreamer, .expected = "SURFACE|Ripstop nylon|0.067|0.0|Fabrics, false, false, ", .warnings = "Illegal material type specified, ignoring."},
    {.id = "m079", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "Parachute:linematerial", .attributes = "type=line|density=0.0003", .text = "Thread (heavy-duty)"}}}, .read = &readParachuteB, .expected = "LINE|Thread (heavy-duty)|3.0E-4|0.0|Other, false, false, "},
    {.id = "m080", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "Parachute:linematerial", .attributes = "type=line|density=0.123", .text = "Rope"}}}, .read = &readParachuteB, .expected = "LINE|Rope|0.123|0.0|Custom, true, true, LINE|Rope|0.123|0.0|Custom"},
    {.id = "m081", .kind = ComponentKind::PARACHUTE, .steps = {{{.key = "Parachute:linematerial", .attributes = "type=surface|density=0.123", .text = "Rope"}}}, .read = &readParachuteB, .expected = "LINE|Elastic cord (round 2 mm, 1/16 in)|0.0018|0.0|Elastics, false, false, ", .warnings = "Illegal material type specified, ignoring."},
});

// What QtRocket answers otherwise than OpenRocket, on purpose: the row has QtRocket's
// answer, the comment above it the reason and OpenRocket's answer.
constexpr auto kOwn = std::to_array<SetterScript>({
    // decision L3: what is not finite is not applied
    // OpenRocket: BULK|Balsa|170.0|NaN|Custom, true, true, BULK|Balsa|170.0|NaN|Custom
    {.id = "m009", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearModulus=NaN", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|0.0|Custom, true, true, BULK|Balsa|170.0|0.0|Custom", .warnings = "Illegal shear modulus value, using 0.0."},
    // decision L3: what is not finite is not applied
    // OpenRocket: BULK|Balsa|170.0|Infinity|Custom, true, true, BULK|Balsa|170.0|Infinity|Custom
    {.id = "m010", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "type=bulk|density=170.0|shearModulus=Infinity", .text = "Balsa"}}}, .read = &readBodyTube, .expected = "BULK|Balsa|170.0|0.0|Custom, true, true, BULK|Balsa|170.0|0.0|Custom", .warnings = "Illegal shear modulus value, using 0.0."},
    // decision L3: what is not finite is not applied
    // OpenRocket: BULK|Foo|NaN|0.0|Custom, true, true, BULK|Foo|NaN|0.0|Custom
    {.id = "m038", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=NaN", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    // decision L3: what is not finite is not applied
    // OpenRocket: BULK|Foo|Infinity|0.0|Custom, true, true, BULK|Foo|Infinity|0.0|Custom
    {.id = "m039", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=Infinity", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
    // decision L3: what is not finite is not applied
    // OpenRocket: BULK|Foo|-Infinity|0.0|Custom, true, true, BULK|Foo|-Infinity|0.0|Custom
    {.id = "m040", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "ExternalComponent:material", .attributes = "density=-Infinity", .text = "Foo"}}}, .read = &readBodyTube, .expected = "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false, ", .warnings = "Illegal material specification, ignoring."},
});
// clang-format on
// ---- end of the generated part

TEST(MaterialSetter, DoesWithEveryElementWhatOpenRocketDoes)
{
    EXPECT_EQ(checkSetterScripts(kJava), Texts{});
}

// OpenRocket stores a density and a shear modulus of NaN or infinity.
TEST(MaterialSetter, ADensityOrShearModulusThatIsNotFiniteIsNotApplied)
{
    EXPECT_EQ(checkSetterScripts(kOwn), Texts{});
}

/// What <material> with @p attributes and the name @p text gives a body tube when the
/// application has no materials at all (a null pointer in the context): readBodyTube(), then the
/// warnings in brackets.
[[nodiscard]] std::string withoutApplicationMaterials(std::string_view attributes,
                                                      std::string_view text)
{
    ApplicationSetterFixture fixture;
    fixture.context().setApplicationMaterials(nullptr);
    RocketComponent&    tube   = fixture.make(ComponentKind::BODY_TUBE);
    const Setter* const setter = setterOfKey("ExternalComponent:material");
    WarningSet          warnings;
    if (setter == nullptr ||
        !setter->set(tube, text, attributesOf(attributes), warnings, fixture.context()).has_value())
    {
        return "no setter, or it failed";
    }
    return withWarnings(readBodyTube(fixture, tube), warnings);
}

// OpenRocket always has its material databases; QtRocket's context may have none. The lookups
// then find nothing: the material of the application's name becomes one of the document, with
// the name translated as ever and nothing but what the element says.
TEST(MaterialSetter, WithoutApplicationMaterialsEveryMaterialIsTheDocuments)
{
    EXPECT_EQ(withoutApplicationMaterials("type=bulk|density=170.0", "Balsa"),
              "BULK|Balsa|170.0|0.0|Custom, true, true, BULK|Balsa|170.0|0.0|Custom");
    EXPECT_EQ(
        withoutApplicationMaterials("density=1250.0|shearModulus=2.4E9|group=Plastics", "PLA"),
        "BULK|PLA - 100% infill|1250.0|2.4E9|Plastics, true, true, "
        "BULK|PLA - 100% infill|1250.0|2.4E9|Plastics");
    // The group of older files that is looked up in the application's materials: OTHER.
    EXPECT_EQ(withoutApplicationMaterials("density=5|group=ThreadsLines", "Cord"),
              "BULK|Cord|5.0|0.0|Other, true, true, BULK|Cord|5.0|0.0|Other");
    EXPECT_EQ(withoutApplicationMaterials("density=x", "Balsa"),
              "BULK|Cardboard|680.0|4.0E8|PaperProducts, false, false,  "
              "[Illegal material specification, ignoring.]");
}

/// What a setter of a material of @p type, made by the test, hands its function for the element:
/// the material (describeMaterial()) or "nothing", then the warnings in brackets.
[[nodiscard]] std::string materialHandedOver(Material::Type type, std::string_view attributes,
                                             std::string_view text)
{
    std::string          handed = "nothing";
    const MaterialSetter setter(
        [&handed](RocketComponent& /*component*/, const Material& material) {
            handed = describeMaterial(material);
        },
        type);
    ApplicationSetterFixture fixture;
    WarningSet               warnings;
    if (!setter
             .set(fixture.setters().tube(), text, attributesOf(attributes), warnings,
                  fixture.context())
             .has_value())
    {
        return "the setter failed";
    }
    return withWarnings(std::move(handed), warnings);
}

// The type is the setter's, not the element's: the lookup is among the materials of that type,
// and the element's type="" is only checked against it.
TEST(MaterialSetter, LooksTheMaterialUpAmongThoseOfItsType)
{
    EXPECT_EQ(materialHandedOver(Material::Type::SURFACE, "density=0.067", "Ripstop nylon"),
              "SURFACE|Ripstop nylon|0.067|0.0|Fabrics, false, false");
    EXPECT_EQ(
        materialHandedOver(Material::Type::SURFACE, "type=surface|density=0.067", "Ripstop nylon"),
        "SURFACE|Ripstop nylon|0.067|0.0|Fabrics, false, false");
    // No line material has that name: a line material of the document.
    EXPECT_EQ(materialHandedOver(Material::Type::LINE, "density=0.067", "Ripstop nylon"),
              "LINE|Ripstop nylon|0.067|0.0|Custom, true, true");
    EXPECT_EQ(
        materialHandedOver(Material::Type::LINE, "type=surface|density=0.067", "Ripstop nylon"),
        "nothing [Illegal material type specified, ignoring.]");
    EXPECT_EQ(materialHandedOver(Material::Type::BULK, "type=bulk", "Balsa"),
              "nothing [Illegal material specification, ignoring.]");
}

/// A function for a setter that is made and not applied.
void setNothing(RocketComponent& /*component*/, const Material& /*material*/) { }

TEST(MaterialSetter, ASetterNeedsAFunctionAndATypeAComponentTakes)
{
    EXPECT_THROW(MaterialSetter(MaterialSetter::SetFunction{}, Material::Type::BULK), BugError);
    EXPECT_THROW(MaterialSetter(&setNothing, Material::Type::CUSTOM), BugError);
    EXPECT_NO_THROW(MaterialSetter(&setNothing, Material::Type::LINE));
}

}  // namespace
