#include "QtRocket/file/openrocket/RadiusPositionSetter.h"

#include <array>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "QtRocket/rocket/position/RadiusMethod.h"
#include "file/openrocket/SetterTestSupport.h"

// What <radiusoffset> does to a component of each class that has the element, as OpenRocket's
// RadiusPositionSetter does it. kJava holds OpenRocket's answers (the probe SpecialSetterProbe of
// tier 9b, part R2; see SetterTestSupport.h): the method and the offset (getRadiusMethod,
// getRadiusOffset) after the elements of a row, and the warnings. The last rows apply the
// setter by hand to a component it is not for, which no file does.

namespace
{

using QtRocket::ComponentKind;
using QtRocket::RadiusPositionSetter;
using QtRocket::RocketComponent;
using QtRocket::Test::ApplicationSetterFixture;
using QtRocket::Test::applyByHand;
using QtRocket::Test::asText;
using QtRocket::Test::checkSetterScripts;
using QtRocket::Test::listInOrder;
using QtRocket::Test::num;
using QtRocket::Test::SetterScript;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_r2_tests.py of the probe: the readers
[[nodiscard]] std::string readRadius(ApplicationSetterFixture& /*fixture*/,
                                     const RocketComponent& c)
{
    return listInOrder({asText(radiusMethodName(c.getRadiusMethod())), num(c.getRadiusOffset())});
}

[[nodiscard]] std::string readName(ApplicationSetterFixture& /*fixture*/, const RocketComponent& c)
{
    return c.getName();
}

// ---- generated: OpenRocket's answers, one row per case of the probe
// clang-format off
constexpr auto kJava = std::to_array<SetterScript>({
    {.id = "x150", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readRadius, .expected = "FREE, 0.1"},
    {.id = "x151", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "RELATIVE, 0.02"},
    {.id = "x152", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=surface", .text = "0.5"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x153", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=coaxial", .text = "0.3"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x154", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .text = "0.2"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x155", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=bogus", .text = "0.25"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x156", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method= free ", .text = "0.11"}}}, .read = &readRadius, .expected = "FREE, 0.11"},
    {.id = "x157", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=FREE", .text = "0.12"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x158", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "type=free", .text = "0.13"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x159", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.PodSet"},
    {.id = "x160", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=    class: info.openrocket.core.rocketcomponent.PodSet"},
    {.id = "x164", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = " 0.14 "}}}, .read = &readRadius, .expected = "FREE, 0.14"},
    {.id = "x165", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "-0.05"}}}, .read = &readRadius, .expected = "FREE, -0.05"},
    {.id = "x166", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=relative", .text = "-0.5"}}}, .read = &readRadius, .expected = "RELATIVE, -0.5"},
    {.id = "x167", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "1e-1d"}}}, .read = &readRadius, .expected = "FREE, 0.1"},
    {.id = "x168", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "PodSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "RELATIVE, 0.02"},
    {.id = "x169", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "PodSet:radiusoffset", .attributes = "method=surface", .text = "abc"}}}, .read = &readRadius, .expected = "FREE, 0.1", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.PodSet"},
    {.id = "x170", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "PodSet:radiusoffset", .attributes = "method=coaxial", .text = "0.7"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x171", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readRadius, .expected = "FREE, 0.1"},
    {.id = "x172", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "RELATIVE, 0.02"},
    {.id = "x173", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=surface", .text = "0.5"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x174", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=coaxial", .text = "0.3"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x175", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .text = "0.2"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x176", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=bogus", .text = "0.25"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x177", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method= free ", .text = "0.11"}}}, .read = &readRadius, .expected = "FREE, 0.11"},
    {.id = "x178", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=FREE", .text = "0.12"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x179", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "type=free", .text = "0.13"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x180", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.ParallelStage"},
    {.id = "x181", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=    class: info.openrocket.core.rocketcomponent.ParallelStage"},
    {.id = "x185", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = " 0.14 "}}}, .read = &readRadius, .expected = "FREE, 0.14"},
    {.id = "x186", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "-0.05"}}}, .read = &readRadius, .expected = "FREE, -0.05"},
    {.id = "x187", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=relative", .text = "-0.5"}}}, .read = &readRadius, .expected = "RELATIVE, -0.5"},
    {.id = "x188", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "1e-1d"}}}, .read = &readRadius, .expected = "FREE, 0.1"},
    {.id = "x189", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "ParallelStage:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "RELATIVE, 0.02"},
    {.id = "x190", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "ParallelStage:radiusoffset", .attributes = "method=surface", .text = "abc"}}}, .read = &readRadius, .expected = "FREE, 0.1", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.ParallelStage"},
    {.id = "x191", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "ParallelStage:radiusoffset", .attributes = "method=coaxial", .text = "0.7"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x192", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x193", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x194", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=surface", .text = "0.5"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x195", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=coaxial", .text = "0.3"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x196", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .text = "0.2"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x197", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=bogus", .text = "0.25"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x198", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method= free ", .text = "0.11"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x199", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=FREE", .text = "0.12"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x200", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "type=free", .text = "0.13"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x201", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readRadius, .expected = "SURFACE, 0.0", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    {.id = "x202", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free"}}}, .read = &readRadius, .expected = "SURFACE, 0.0", .warnings = "Warning: invalid value radius position. value=    class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    {.id = "x206", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = " 0.14 "}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x207", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "-0.05"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x208", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=relative", .text = "-0.5"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x209", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "1e-1d"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x210", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "FinSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x211", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "FinSet:radiusoffset", .attributes = "method=surface", .text = "abc"}}}, .read = &readRadius, .expected = "SURFACE, 0.0", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    {.id = "x212", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "FinSet:radiusoffset", .attributes = "method=coaxial", .text = "0.7"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x213", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x214", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x215", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=surface", .text = "0.5"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x216", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=coaxial", .text = "0.3"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x217", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .text = "0.2"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x234", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x235", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x236", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=surface", .text = "0.5"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x237", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=coaxial", .text = "0.3"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x238", .kind = ComponentKind::FREEFORM_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .text = "0.2"}}}, .read = &readRadius, .expected = "SURFACE, 0.0"},
    {.id = "x255", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x256", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x257", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=surface", .text = "0.5"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x258", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=coaxial", .text = "0.3"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x259", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .text = "0.2"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x260", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=bogus", .text = "0.25"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x261", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method= free ", .text = "0.11"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x262", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=FREE", .text = "0.12"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x263", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "type=free", .text = "0.13"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x264", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    {.id = "x265", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0", .warnings = "Warning: invalid value radius position. value=    class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    {.id = "x269", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = " 0.14 "}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x270", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "-0.05"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x271", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=relative", .text = "-0.5"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x272", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "1e-1d"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x273", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "TubeFinSet:radiusoffset", .attributes = "method=relative", .text = "0.02"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x274", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "TubeFinSet:radiusoffset", .attributes = "method=surface", .text = "abc"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    {.id = "x275", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "0.1"}, {.key = "TubeFinSet:radiusoffset", .attributes = "method=coaxial", .text = "0.7"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0"},
    {.id = "x614", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readName, .expected = "Bulkhead", .warnings = "Warning: radiusPositionable is not valid for this class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x615", .kind = ComponentKind::BULKHEAD, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readName, .expected = "Bulkhead", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.Bulkhead"},
    {.id = "x616", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readName, .expected = "Body Tube", .warnings = "Warning: radiusPositionable is not valid for this class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x617", .kind = ComponentKind::BODY_TUBE, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readName, .expected = "Body Tube", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.BodyTube"},
    {.id = "x618", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readName, .expected = "Launch Lug", .warnings = "Warning: radiusPositionable is not valid for this class: info.openrocket.core.rocketcomponent.LaunchLug"},
    {.id = "x619", .kind = ComponentKind::LAUNCH_LUG, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readName, .expected = "Launch Lug", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.LaunchLug"},
    {.id = "x620", .kind = ComponentKind::ROCKET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "0.1"}}}, .read = &readName, .expected = "Rocket", .warnings = "Warning: radiusPositionable is not valid for this class: info.openrocket.core.rocketcomponent.Rocket"},
    {.id = "x621", .kind = ComponentKind::ROCKET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "abc"}}}, .read = &readName, .expected = "Rocket", .warnings = "Warning: invalid value radius position. value=abc    class: info.openrocket.core.rocketcomponent.Rocket"},
});

// What QtRocket answers otherwise than OpenRocket, on purpose: the row has QtRocket's
// answer, the comment above it the reason and OpenRocket's answer.
constexpr auto kOwn = std::to_array<SetterScript>({
    // decision L3: what is not finite is not applied
    // OpenRocket: FREE, NaN
    {.id = "x161", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "NaN"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: FREE, Infinity
    {.id = "x162", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "Infinity"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: FREE, -Infinity
    {.id = "x163", .kind = ComponentKind::POD_SET, .steps = {{{.key = "PodSet:radiusoffset", .attributes = "method=free", .text = "-Infinity"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=-Infinity    class: info.openrocket.core.rocketcomponent.PodSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: FREE, NaN
    {.id = "x182", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "NaN"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.ParallelStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: FREE, Infinity
    {.id = "x183", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "Infinity"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.ParallelStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: FREE, -Infinity
    {.id = "x184", .kind = ComponentKind::PARALLEL_STAGE, .steps = {{{.key = "ParallelStage:radiusoffset", .attributes = "method=free", .text = "-Infinity"}}}, .read = &readRadius, .expected = "RELATIVE, 0.0", .warnings = "Warning: invalid value radius position. value=-Infinity    class: info.openrocket.core.rocketcomponent.ParallelStage"},
    // decision L3: what is not finite is not applied
    // OpenRocket: SURFACE, 0.0
    {.id = "x203", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "NaN"}}}, .read = &readRadius, .expected = "SURFACE, 0.0", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: SURFACE, 0.0
    {.id = "x204", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "Infinity"}}}, .read = &readRadius, .expected = "SURFACE, 0.0", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: SURFACE, 0.0
    {.id = "x205", .kind = ComponentKind::TRAPEZOID_FIN_SET, .steps = {{{.key = "FinSet:radiusoffset", .attributes = "method=free", .text = "-Infinity"}}}, .read = &readRadius, .expected = "SURFACE, 0.0", .warnings = "Warning: invalid value radius position. value=-Infinity    class: info.openrocket.core.rocketcomponent.TrapezoidFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: COAXIAL, 0.0
    {.id = "x266", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "NaN"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0", .warnings = "Warning: invalid value radius position. value=NaN    class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: COAXIAL, 0.0
    {.id = "x267", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "Infinity"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0", .warnings = "Warning: invalid value radius position. value=Infinity    class: info.openrocket.core.rocketcomponent.TubeFinSet"},
    // decision L3: what is not finite is not applied
    // OpenRocket: COAXIAL, 0.0
    {.id = "x268", .kind = ComponentKind::TUBE_FIN_SET, .steps = {{{.key = "TubeFinSet:radiusoffset", .attributes = "method=free", .text = "-Infinity"}}}, .read = &readRadius, .expected = "COAXIAL, 0.0", .warnings = "Warning: invalid value radius position. value=-Infinity    class: info.openrocket.core.rocketcomponent.TubeFinSet"},
});
// clang-format on
// ---- end of the generated part

TEST(RadiusPositionSetter, DoesWithEveryElementWhatOpenRocketDoes)
{
    EXPECT_EQ(checkSetterScripts(kJava), Texts{});
}

// OpenRocket stores a NaN and an infinity (a fin set ignores every offset, without a warning).
TEST(RadiusPositionSetter, AnOffsetThatIsNotFiniteIsNotApplied)
{
    EXPECT_EQ(checkSetterScripts(kOwn), Texts{});
}

// The cases x150, x154 and x157 of the probe, through a setter of the test's own.
TEST(RadiusPositionSetter, SetsTheMethodAndThenTheOffset)
{
    const RadiusPositionSetter setter;
    EXPECT_EQ(applyByHand(setter, ComponentKind::POD_SET, "method=free", "0.1", &readRadius),
              "FREE, 0.1");
    // No method, and one the setter does not know: the surface, where the offset is 0.
    EXPECT_EQ(applyByHand(setter, ComponentKind::POD_SET, "", "0.2", &readRadius), "SURFACE, 0.0");
    EXPECT_EQ(applyByHand(setter, ComponentKind::POD_SET, "method=FREE", "0.12", &readRadius),
              "SURFACE, 0.0");
}

}  // namespace
