#include <algorithm>
#include <array>
#include <string>
#include <string_view>
#include <vector>

#include <gtest/gtest.h>

#include "QtRocket/file/openrocket/DocumentConfig.h"
#include "QtRocket/rocket/AxialStage.h"
#include "QtRocket/rocket/BodyTube.h"
#include "QtRocket/rocket/Bulkhead.h"
#include "QtRocket/rocket/CenteringRing.h"
#include "QtRocket/rocket/ComponentKind.h"
#include "QtRocket/rocket/DeploymentConfiguration.h"
#include "QtRocket/rocket/DesignType.h"
#include "QtRocket/rocket/EllipticalFinSet.h"
#include "QtRocket/rocket/EngineBlock.h"
#include "QtRocket/rocket/FinSet.h"
#include "QtRocket/rocket/Finish.h"
#include "QtRocket/rocket/FreeformFinSet.h"
#include "QtRocket/rocket/InnerTube.h"
#include "QtRocket/rocket/LaunchLug.h"
#include "QtRocket/rocket/MassComponent.h"
#include "QtRocket/rocket/NoseCone.h"
#include "QtRocket/rocket/Parachute.h"
#include "QtRocket/rocket/ParallelStage.h"
#include "QtRocket/rocket/PodSet.h"
#include "QtRocket/rocket/RailButton.h"
#include "QtRocket/rocket/ReferenceType.h"
#include "QtRocket/rocket/Rocket.h"
#include "QtRocket/rocket/RocketComponent.h"
#include "QtRocket/rocket/ShockCord.h"
#include "QtRocket/rocket/StageSeparationConfiguration.h"
#include "QtRocket/rocket/Streamer.h"
#include "QtRocket/rocket/Transition.h"
#include "QtRocket/rocket/TransitionShape.h"
#include "QtRocket/rocket/TrapezoidFinSet.h"
#include "QtRocket/rocket/TubeCoupler.h"
#include "QtRocket/rocket/TubeFinSet.h"
#include "file/openrocket/SetterTestSupport.h"

// One application of every setter of the .ork loader's setter table (DocumentConfig): the
// element's text goes through the entry that the walk for the component's kind finds, and the
// component then has to hold what OpenRocket's component holds after the same call. This is the
// test that an entry of the table is wired to the right property of the right class.
//
// kTable has one row per key that has a setter. The expectations are OpenRocket's answers (see
// SetterTestSupport.h for the probe); the rows are written by the probe's
// scripts/make_tests.py from them. A row can as well be written by hand: the key, the kind of
// the component to make, the element's attributes and text, a function that prints the
// properties the setter has to reach as the probe prints the getters (num(), flag(), count(),
// list() and as<>() of SetterTestSupport.h), and what OpenRocket gave. The test
// HasACaseForEverySetterOfTheTable fails for a key of the table that has no row here.

namespace
{

using QtRocket::AxialStage;
using QtRocket::BodyTube;
using QtRocket::Bulkhead;
using QtRocket::CenteringRing;
using QtRocket::ComponentKind;
using QtRocket::deployEventName;
using QtRocket::designTypeName;
using QtRocket::DocumentConfig;
using QtRocket::EllipticalFinSet;
using QtRocket::EngineBlock;
using QtRocket::finCrossSectionName;
using QtRocket::finishName;
using QtRocket::FreeformFinSet;
using QtRocket::InnerTube;
using QtRocket::LaunchLug;
using QtRocket::MassComponent;
using QtRocket::massComponentTypeName;
using QtRocket::NoseCone;
using QtRocket::Parachute;
using QtRocket::ParallelStage;
using QtRocket::PodSet;
using QtRocket::RailButton;
using QtRocket::referenceTypeName;
using QtRocket::Rocket;
using QtRocket::RocketComponent;
using QtRocket::separationEventName;
using QtRocket::ShockCord;
using QtRocket::Streamer;
using QtRocket::Transition;
using QtRocket::transitionShapeName;
using QtRocket::TrapezoidFinSet;
using QtRocket::TubeCoupler;
using QtRocket::TubeFinSet;
using QtRocket::Test::as;
using QtRocket::Test::asText;
using QtRocket::Test::checkSetterCases;
using QtRocket::Test::colorOf;
using QtRocket::Test::count;
using QtRocket::Test::flag;
using QtRocket::Test::list;
using QtRocket::Test::num;
using QtRocket::Test::SetterCase;
using QtRocket::Test::styleOf;

using Texts = std::vector<std::string>;

// ---- generated by scripts/make_tests.py of the probe: the readers
[[nodiscard]] std::string readAxialStageOverrideMassAndMassOverridden(const RocketComponent& c)
{
    return list(num(as<AxialStage>(c).getOverrideMass()),
                flag(as<AxialStage>(c).isMassOverridden()));
}

[[nodiscard]] std::string readAxialStageSeparationEventAndSeparationAltitudeAndSeparationDelay(
    const RocketComponent& c)
{
    return list(
        asText(separationEventName(
            as<AxialStage>(c).getSeparationConfigurations().getDefault().getSeparationEvent())),
        num(as<AxialStage>(c).getSeparationConfigurations().getDefault().getSeparationAltitude()),
        num(as<AxialStage>(c).getSeparationConfigurations().getDefault().getSeparationDelay()));
}

[[nodiscard]] std::string
readAxialStageSubcomponentsOverriddenMassAndSubcomponentsOverriddenCGAndSubcomponentsOverriddenCD(
    const RocketComponent& c)
{
    return list(flag(as<AxialStage>(c).isSubcomponentsOverriddenMass()),
                flag(as<AxialStage>(c).isSubcomponentsOverriddenCG()),
                flag(as<AxialStage>(c).isSubcomponentsOverriddenCD()));
}

[[nodiscard]] std::string readBodyTubeLength(const RocketComponent& c)
{
    return num(as<BodyTube>(c).getLength());
}

[[nodiscard]] std::string readBodyTubeName(const RocketComponent& c)
{
    return asText(as<BodyTube>(c).getName());
}

[[nodiscard]] std::string readBodyTubeOuterRadiusAndOuterRadiusAutomatic(const RocketComponent& c)
{
    return list(num(as<BodyTube>(c).getOuterRadius()),
                flag(as<BodyTube>(c).isOuterRadiusAutomatic()));
}

[[nodiscard]] std::string readBodyTubeOverrideCGXAndCGOverridden(const RocketComponent& c)
{
    return list(num(as<BodyTube>(c).getOverrideCGX()), flag(as<BodyTube>(c).isCGOverridden()));
}

[[nodiscard]] std::string
readBodyTubeSubcomponentsOverriddenMassAndSubcomponentsOverriddenCGAndSubcomponentsOverriddenCD(
    const RocketComponent& c)
{
    return list(flag(as<BodyTube>(c).isSubcomponentsOverriddenMass()),
                flag(as<BodyTube>(c).isSubcomponentsOverriddenCG()),
                flag(as<BodyTube>(c).isSubcomponentsOverriddenCD()));
}

[[nodiscard]] std::string readBulkheadInnerRadius(const RocketComponent& c)
{
    return num(as<Bulkhead>(c).getInnerRadius());
}

[[nodiscard]] std::string readBulkheadInstanceSeparation(const RocketComponent& c)
{
    return num(as<Bulkhead>(c).getInstanceSeparation());
}

[[nodiscard]] std::string readBulkheadOuterRadiusAndOuterRadiusAutomatic(const RocketComponent& c)
{
    return list(num(as<Bulkhead>(c).getOuterRadius()),
                flag(as<Bulkhead>(c).isOuterRadiusAutomatic()));
}

[[nodiscard]] std::string readCenteringRingInnerRadiusAndInnerRadiusAutomatic(
    const RocketComponent& c)
{
    return list(num(as<CenteringRing>(c).getInnerRadius()),
                flag(as<CenteringRing>(c).isInnerRadiusAutomatic()));
}

[[nodiscard]] std::string readCenteringRingInstanceCount(const RocketComponent& c)
{
    return count(as<CenteringRing>(c).getInstanceCount());
}

[[nodiscard]] std::string readCenteringRingLength(const RocketComponent& c)
{
    return num(as<CenteringRing>(c).getLength());
}

[[nodiscard]] std::string readCenteringRingOuterRadiusAndOuterRadiusAutomatic(
    const RocketComponent& c)
{
    return list(num(as<CenteringRing>(c).getOuterRadius()),
                flag(as<CenteringRing>(c).isOuterRadiusAutomatic()));
}

[[nodiscard]] std::string readEllipticalFinSetCrossSection(const RocketComponent& c)
{
    return asText(finCrossSectionName(as<EllipticalFinSet>(c).getCrossSection()));
}

[[nodiscard]] std::string readEllipticalFinSetFinCountAndInstanceCount(const RocketComponent& c)
{
    return list(count(as<EllipticalFinSet>(c).getFinCount()),
                count(as<EllipticalFinSet>(c).getInstanceCount()));
}

[[nodiscard]] std::string readEllipticalFinSetHeight(const RocketComponent& c)
{
    return num(as<EllipticalFinSet>(c).getHeight());
}

[[nodiscard]] std::string readEllipticalFinSetLength(const RocketComponent& c)
{
    return num(as<EllipticalFinSet>(c).getLength());
}

[[nodiscard]] std::string readEngineBlockOuterRadiusAndOuterRadiusAutomatic(
    const RocketComponent& c)
{
    return list(num(as<EngineBlock>(c).getOuterRadius()),
                flag(as<EngineBlock>(c).isOuterRadiusAutomatic()));
}

[[nodiscard]] std::string readEngineBlockThickness(const RocketComponent& c)
{
    return num(as<EngineBlock>(c).getThickness());
}

[[nodiscard]] std::string readFreeformFinSetBaseRotation(const RocketComponent& c)
{
    return num(as<FreeformFinSet>(c).getBaseRotation());
}

[[nodiscard]] std::string readFreeformFinSetFilletRadius(const RocketComponent& c)
{
    return num(as<FreeformFinSet>(c).getFilletRadius());
}

[[nodiscard]] std::string readInnerTubeClusterRotation(const RocketComponent& c)
{
    return num(as<InnerTube>(c).getClusterRotation());
}

[[nodiscard]] std::string readInnerTubeClusterScale(const RocketComponent& c)
{
    return num(as<InnerTube>(c).getClusterScale());
}

[[nodiscard]] std::string readInnerTubeOuterRadiusAndOuterRadiusAutomatic(const RocketComponent& c)
{
    return list(num(as<InnerTube>(c).getOuterRadius()),
                flag(as<InnerTube>(c).isOuterRadiusAutomatic()));
}

[[nodiscard]] std::string readInnerTubeRadialPosition(const RocketComponent& c)
{
    return num(as<InnerTube>(c).getRadialPosition());
}

[[nodiscard]] std::string readLaunchLugAngleOffset(const RocketComponent& c)
{
    return num(as<LaunchLug>(c).getAngleOffset());
}

[[nodiscard]] std::string readLaunchLugID(const RocketComponent& c)
{
    return c.getId().toString();
}

[[nodiscard]] std::string readLaunchLugInstanceCount(const RocketComponent& c)
{
    return count(as<LaunchLug>(c).getInstanceCount());
}

[[nodiscard]] std::string readLaunchLugInstanceSeparation(const RocketComponent& c)
{
    return num(as<LaunchLug>(c).getInstanceSeparation());
}

[[nodiscard]] std::string readLaunchLugLength(const RocketComponent& c)
{
    return num(as<LaunchLug>(c).getLength());
}

[[nodiscard]] std::string readLaunchLugOuterRadiusAndThickness(const RocketComponent& c)
{
    return list(num(as<LaunchLug>(c).getOuterRadius()), num(as<LaunchLug>(c).getThickness()));
}

[[nodiscard]] std::string readLaunchLugThicknessAndOuterRadius(const RocketComponent& c)
{
    return list(num(as<LaunchLug>(c).getThickness()), num(as<LaunchLug>(c).getOuterRadius()));
}

[[nodiscard]] std::string readMassComponentComponentMass(const RocketComponent& c)
{
    return num(as<MassComponent>(c).getComponentMass());
}

[[nodiscard]] std::string readMassComponentLength(const RocketComponent& c)
{
    return num(as<MassComponent>(c).getLength());
}

[[nodiscard]] std::string readMassComponentMassComponentType(const RocketComponent& c)
{
    return asText(massComponentTypeName(as<MassComponent>(c).getMassComponentType()));
}

[[nodiscard]] std::string readNoseConeAftShoulderCapped(const RocketComponent& c)
{
    return flag(as<NoseCone>(c).isAftShoulderCapped());
}

[[nodiscard]] std::string readNoseConeAftShoulderLength(const RocketComponent& c)
{
    return num(as<NoseCone>(c).getAftShoulderLength());
}

[[nodiscard]] std::string readNoseConeAftShoulderRadius(const RocketComponent& c)
{
    return num(as<NoseCone>(c).getAftShoulderRadius());
}

[[nodiscard]] std::string readNoseConeAftShoulderThickness(const RocketComponent& c)
{
    return num(as<NoseCone>(c).getAftShoulderThickness());
}

[[nodiscard]] std::string readNoseConeFlipped(const RocketComponent& c)
{
    return flag(as<NoseCone>(c).isFlipped());
}

[[nodiscard]] std::string readNoseConeRed(const RocketComponent& c)
{
    return colorOf(c);
}

[[nodiscard]] std::string readNoseConeShapeTypeAndClippedAndShapeParameter(const RocketComponent& c)
{
    return list(asText(transitionShapeName(as<NoseCone>(c).getShapeType())),
                flag(as<NoseCone>(c).isClipped()), num(as<NoseCone>(c).getShapeParameter()));
}

[[nodiscard]] std::string readParachuteDeployEventAndDeployAltitudeAndDeployDelay(
    const RocketComponent& c)
{
    return list(
        asText(deployEventName(
            as<Parachute>(c).getDeploymentConfigurations().getDefault().getDeployEvent())),
        num(as<Parachute>(c).getDeploymentConfigurations().getDefault().getDeployAltitude()),
        num(as<Parachute>(c).getDeploymentConfigurations().getDefault().getDeployDelay()));
}

[[nodiscard]] std::string readParachuteDiameter(const RocketComponent& c)
{
    return num(as<Parachute>(c).getDiameter());
}

[[nodiscard]] std::string readParachuteDrogue(const RocketComponent& c)
{
    return flag(as<Parachute>(c).isDrogue());
}

[[nodiscard]] std::string readParachuteLineCount(const RocketComponent& c)
{
    return count(as<Parachute>(c).getLineCount());
}

[[nodiscard]] std::string readParachuteLineLengthAndLineLengthAutomatic(const RocketComponent& c)
{
    return list(num(as<Parachute>(c).getLineLength()),
                flag(as<Parachute>(c).isLineLengthAutomatic()));
}

[[nodiscard]] std::string readParachuteOverrideCDAndCDOverridden(const RocketComponent& c)
{
    return list(num(as<Parachute>(c).getOverrideCD()), flag(as<Parachute>(c).isCDOverridden()));
}

[[nodiscard]] std::string readParachuteRadialPosition(const RocketComponent& c)
{
    return num(as<Parachute>(c).getRadialPosition());
}

[[nodiscard]] std::string readParallelStageInstanceCount(const RocketComponent& c)
{
    return count(as<ParallelStage>(c).getInstanceCount());
}

[[nodiscard]] std::string readParallelStageSeparationEventAndSeparationAltitudeAndSeparationDelay(
    const RocketComponent& c)
{
    return list(
        asText(separationEventName(
            as<ParallelStage>(c).getSeparationConfigurations().getDefault().getSeparationEvent())),
        num(as<ParallelStage>(c)
                .getSeparationConfigurations()
                .getDefault()
                .getSeparationAltitude()),
        num(as<ParallelStage>(c).getSeparationConfigurations().getDefault().getSeparationDelay()));
}

[[nodiscard]] std::string readPodSetInstanceCount(const RocketComponent& c)
{
    return count(as<PodSet>(c).getInstanceCount());
}

[[nodiscard]] std::string readRailButtonBaseHeight(const RocketComponent& c)
{
    return num(as<RailButton>(c).getBaseHeight());
}

[[nodiscard]] std::string readRailButtonFinish(const RocketComponent& c)
{
    return asText(finishName(as<RailButton>(c).getFinish()));
}

[[nodiscard]] std::string readRailButtonFlangeHeight(const RocketComponent& c)
{
    return num(as<RailButton>(c).getFlangeHeight());
}

[[nodiscard]] std::string readRailButtonInnerDiameterAndOuterDiameter(const RocketComponent& c)
{
    return list(num(as<RailButton>(c).getInnerDiameter()),
                num(as<RailButton>(c).getOuterDiameter()));
}

[[nodiscard]] std::string readRailButtonInstanceCount(const RocketComponent& c)
{
    return count(as<RailButton>(c).getInstanceCount());
}

[[nodiscard]] std::string readRailButtonInstanceSeparation(const RocketComponent& c)
{
    return num(as<RailButton>(c).getInstanceSeparation());
}

[[nodiscard]] std::string readRailButtonOuterDiameterAndInnerDiameter(const RocketComponent& c)
{
    return list(num(as<RailButton>(c).getOuterDiameter()),
                num(as<RailButton>(c).getInnerDiameter()));
}

[[nodiscard]] std::string readRailButtonScrewHeight(const RocketComponent& c)
{
    return num(as<RailButton>(c).getScrewHeight());
}

[[nodiscard]] std::string readRailButtonTotalHeight(const RocketComponent& c)
{
    return num(as<RailButton>(c).getTotalHeight());
}

[[nodiscard]] std::string readRocketCustomReferenceLength(const RocketComponent& c)
{
    return num(as<Rocket>(c).getCustomReferenceLength());
}

[[nodiscard]] std::string readRocketDesignType(const RocketComponent& c)
{
    return asText(designTypeName(as<Rocket>(c).getDesignType()));
}

[[nodiscard]] std::string readRocketDesigner(const RocketComponent& c)
{
    return asText(as<Rocket>(c).getDesigner());
}

[[nodiscard]] std::string readRocketKitName(const RocketComponent& c)
{
    return asText(as<Rocket>(c).getKitName());
}

[[nodiscard]] std::string readRocketReferenceType(const RocketComponent& c)
{
    return asText(referenceTypeName(as<Rocket>(c).getReferenceType()));
}

[[nodiscard]] std::string readRocketRevision(const RocketComponent& c)
{
    return asText(as<Rocket>(c).getRevision());
}

[[nodiscard]] std::string readShockCordCordLengthAndCordLengthAutomatic(const RocketComponent& c)
{
    return list(num(as<ShockCord>(c).getCordLength()),
                flag(as<ShockCord>(c).isCordLengthAutomatic()));
}

[[nodiscard]] std::string readShockCordRadiusAndRadiusAutomatic(const RocketComponent& c)
{
    return list(num(as<ShockCord>(c).getRadius()), flag(as<ShockCord>(c).isRadiusAutomatic()));
}

[[nodiscard]] std::string readStreamerCDAndCDAutomatic(const RocketComponent& c)
{
    return list(num(as<Streamer>(c).getCD()), flag(as<Streamer>(c).isCDAutomatic()));
}

[[nodiscard]] std::string readStreamerComment(const RocketComponent& c)
{
    return asText(as<Streamer>(c).getComment());
}

[[nodiscard]] std::string readStreamerDeployEventAndDeployAltitudeAndDeployDelay(
    const RocketComponent& c)
{
    return list(asText(deployEventName(
                    as<Streamer>(c).getDeploymentConfigurations().getDefault().getDeployEvent())),
                num(as<Streamer>(c).getDeploymentConfigurations().getDefault().getDeployAltitude()),
                num(as<Streamer>(c).getDeploymentConfigurations().getDefault().getDeployDelay()));
}

[[nodiscard]] std::string readStreamerRadialDirection(const RocketComponent& c)
{
    return num(as<Streamer>(c).getRadialDirection());
}

[[nodiscard]] std::string readStreamerStripLength(const RocketComponent& c)
{
    return num(as<Streamer>(c).getStripLength());
}

[[nodiscard]] std::string readStreamerStripWidth(const RocketComponent& c)
{
    return num(as<Streamer>(c).getStripWidth());
}

[[nodiscard]] std::string readTransitionAftRadiusAndAftRadiusAutomatic(const RocketComponent& c)
{
    return list(num(as<Transition>(c).getAftRadius()),
                flag(as<Transition>(c).isAftRadiusAutomatic()));
}

[[nodiscard]] std::string readTransitionForeRadiusAndForeRadiusAutomatic(const RocketComponent& c)
{
    return list(num(as<Transition>(c).getForeRadius()),
                flag(as<Transition>(c).isForeRadiusAutomatic()));
}

[[nodiscard]] std::string readTransitionForeShoulderCapped(const RocketComponent& c)
{
    return flag(as<Transition>(c).isForeShoulderCapped());
}

[[nodiscard]] std::string readTransitionForeShoulderLength(const RocketComponent& c)
{
    return num(as<Transition>(c).getForeShoulderLength());
}

[[nodiscard]] std::string readTransitionForeShoulderRadius(const RocketComponent& c)
{
    return num(as<Transition>(c).getForeShoulderRadius());
}

[[nodiscard]] std::string readTransitionForeShoulderThickness(const RocketComponent& c)
{
    return num(as<Transition>(c).getForeShoulderThickness());
}

[[nodiscard]] std::string readTransitionShapeTypeAndClippedAndShapeParameter(
    const RocketComponent& c)
{
    return list(asText(transitionShapeName(as<Transition>(c).getShapeType())),
                flag(as<Transition>(c).isClipped()), num(as<Transition>(c).getShapeParameter()));
}

[[nodiscard]] std::string readTransitionThicknessAndFilled(const RocketComponent& c)
{
    return list(num(as<Transition>(c).getThickness()), flag(as<Transition>(c).isFilled()));
}

[[nodiscard]] std::string readTrapezoidFinSetCantAngle(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getCantAngle());
}

[[nodiscard]] std::string readTrapezoidFinSetFinCount(const RocketComponent& c)
{
    return count(as<TrapezoidFinSet>(c).getFinCount());
}

[[nodiscard]] std::string readTrapezoidFinSetHeight(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getHeight());
}

[[nodiscard]] std::string readTrapezoidFinSetLineStyle(const RocketComponent& c)
{
    return styleOf(c);
}

[[nodiscard]] std::string readTrapezoidFinSetRootChord(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getRootChord());
}

[[nodiscard]] std::string readTrapezoidFinSetSweep(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getSweep());
}

[[nodiscard]] std::string readTrapezoidFinSetTabHeight(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getTabHeight());
}

[[nodiscard]] std::string readTrapezoidFinSetTabLength(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getTabLength());
}

[[nodiscard]] std::string readTrapezoidFinSetThickness(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getThickness());
}

[[nodiscard]] std::string readTrapezoidFinSetTipChord(const RocketComponent& c)
{
    return num(as<TrapezoidFinSet>(c).getTipChord());
}

[[nodiscard]] std::string readTubeCouplerOuterRadiusAndOuterRadiusAutomatic(
    const RocketComponent& c)
{
    return list(num(as<TubeCoupler>(c).getOuterRadius()),
                flag(as<TubeCoupler>(c).isOuterRadiusAutomatic()));
}

[[nodiscard]] std::string readTubeCouplerRadialDirection(const RocketComponent& c)
{
    return num(as<TubeCoupler>(c).getRadialDirection());
}

[[nodiscard]] std::string readTubeFinSetBaseRotation(const RocketComponent& c)
{
    return num(as<TubeFinSet>(c).getBaseRotation());
}

[[nodiscard]] std::string readTubeFinSetFinCount(const RocketComponent& c)
{
    return count(as<TubeFinSet>(c).getFinCount());
}

[[nodiscard]] std::string readTubeFinSetFinCountAndInstanceCount(const RocketComponent& c)
{
    return list(count(as<TubeFinSet>(c).getFinCount()),
                count(as<TubeFinSet>(c).getInstanceCount()));
}

[[nodiscard]] std::string readTubeFinSetLength(const RocketComponent& c)
{
    return num(as<TubeFinSet>(c).getLength());
}

[[nodiscard]] std::string readTubeFinSetOuterRadiusAndOuterRadiusAutomatic(const RocketComponent& c)
{
    return list(num(as<TubeFinSet>(c).getOuterRadius()),
                flag(as<TubeFinSet>(c).isOuterRadiusAutomatic()));
}

[[nodiscard]] std::string readTubeFinSetThickness(const RocketComponent& c)
{
    return num(as<TubeFinSet>(c).getThickness());
}
// ---- generated: one row per key and line, in the order of OpenRocket's DocumentConfig.java
// clang-format off
constexpr auto kTable = std::to_array<SetterCase>({
    {.key = "RocketComponent:name", .kind = ComponentKind::BODY_TUBE, .text = " padded name ", .read = &readBodyTubeName, .expected = " padded name "},
    {.key = "RocketComponent:id", .kind = ComponentKind::LAUNCH_LUG, .text = "1-2-3-4-5", .read = &readLaunchLugID, .expected = "00000001-0002-0003-0004-000000000005"},
    {.key = "RocketComponent:color", .kind = ComponentKind::NOSE_CONE, .attributes = "red=1|green=2|blue=3", .text = "", .read = &readNoseConeRed, .expected = "1, 2, 3, 255"},
    {.key = "RocketComponent:linestyle", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "dashdot", .read = &readTrapezoidFinSetLineStyle, .expected = "DASHDOT"},
    {.key = "RocketComponent:overridemass", .kind = ComponentKind::AXIAL_STAGE, .text = "0.25", .read = &readAxialStageOverrideMassAndMassOverridden, .expected = "0.25, true"},
    {.key = "RocketComponent:overridecg", .kind = ComponentKind::BODY_TUBE, .text = " 0.5 ", .read = &readBodyTubeOverrideCGXAndCGOverridden, .expected = "0.5, true"},
    {.key = "RocketComponent:overridecd", .kind = ComponentKind::PARACHUTE, .text = "0.75", .read = &readParachuteOverrideCDAndCDOverridden, .expected = "0.75, true"},
    {.key = "RocketComponent:overridesubcomponents", .kind = ComponentKind::AXIAL_STAGE, .text = "true", .read = &readAxialStageSubcomponentsOverriddenMassAndSubcomponentsOverriddenCGAndSubcomponentsOverriddenCD, .expected = "true, true, true"},
    {.key = "RocketComponent:overridesubcomponentsmass", .kind = ComponentKind::BODY_TUBE, .text = "true", .read = &readBodyTubeSubcomponentsOverriddenMassAndSubcomponentsOverriddenCGAndSubcomponentsOverriddenCD, .expected = "true, false, false"},
    {.key = "RocketComponent:overridesubcomponentscg", .kind = ComponentKind::BODY_TUBE, .text = "true", .read = &readBodyTubeSubcomponentsOverriddenMassAndSubcomponentsOverriddenCGAndSubcomponentsOverriddenCD, .expected = "false, true, false"},
    {.key = "RocketComponent:overridesubcomponentscd", .kind = ComponentKind::BODY_TUBE, .text = "true", .read = &readBodyTubeSubcomponentsOverriddenMassAndSubcomponentsOverriddenCGAndSubcomponentsOverriddenCD, .expected = "false, false, true"},
    {.key = "RocketComponent:comment", .kind = ComponentKind::STREAMER, .text = "line 1\nline 2 ", .read = &readStreamerComment, .expected = "line 1\nline 2 "},
    {.key = "ExternalComponent:finish", .kind = ComponentKind::RAIL_BUTTON, .text = "smooth", .read = &readRailButtonFinish, .expected = "SMOOTH"},
    {.key = "BodyComponent:length", .kind = ComponentKind::BODY_TUBE, .text = "0.35", .read = &readBodyTubeLength, .expected = "0.35"},
    {.key = "BodyTube:radius", .kind = ComponentKind::BODY_TUBE, .text = "auto 0.0125", .read = &readBodyTubeOuterRadiusAndOuterRadiusAutomatic, .expected = "0.025, true"},
    {.key = "ParallelStage:instancecount", .kind = ComponentKind::PARALLEL_STAGE, .text = "3", .read = &readParallelStageInstanceCount, .expected = "3"},
    {.key = "SymmetricComponent:thickness", .kind = ComponentKind::TRANSITION, .text = "0.003", .read = &readTransitionThicknessAndFilled, .expected = "0.003, false"},
    {.key = "LaunchLug:instancecount", .kind = ComponentKind::LAUNCH_LUG, .text = "2", .read = &readLaunchLugInstanceCount, .expected = "2"},
    {.key = "LaunchLug:instanceseparation", .kind = ComponentKind::LAUNCH_LUG, .text = "0.07", .read = &readLaunchLugInstanceSeparation, .expected = "0.07"},
    {.key = "LaunchLug:radialdirection", .kind = ComponentKind::LAUNCH_LUG, .text = "30", .read = &readLaunchLugAngleOffset, .expected = "0.5235987755982988"},
    {.key = "LaunchLug:radius", .kind = ComponentKind::LAUNCH_LUG, .text = "0.007", .read = &readLaunchLugOuterRadiusAndThickness, .expected = "0.007, 0.001"},
    {.key = "LaunchLug:length", .kind = ComponentKind::LAUNCH_LUG, .text = "0.04", .read = &readLaunchLugLength, .expected = "0.04"},
    {.key = "LaunchLug:thickness", .kind = ComponentKind::LAUNCH_LUG, .text = "0.0015", .read = &readLaunchLugThicknessAndOuterRadius, .expected = "0.0015, 0.005"},
    {.key = "RailButton:instancecount", .kind = ComponentKind::RAIL_BUTTON, .text = "2", .read = &readRailButtonInstanceCount, .expected = "2"},
    {.key = "RailButton:instanceseparation", .kind = ComponentKind::RAIL_BUTTON, .text = "0.08", .read = &readRailButtonInstanceSeparation, .expected = "0.08"},
    {.key = "RailButton:height", .kind = ComponentKind::RAIL_BUTTON, .text = "0.012", .read = &readRailButtonTotalHeight, .expected = "0.012"},
    {.key = "RailButton:baseheight", .kind = ComponentKind::RAIL_BUTTON, .text = "0.003", .read = &readRailButtonBaseHeight, .expected = "0.003"},
    {.key = "RailButton:flangeheight", .kind = ComponentKind::RAIL_BUTTON, .text = "0.0025", .read = &readRailButtonFlangeHeight, .expected = "0.0025"},
    {.key = "RailButton:screwheight", .kind = ComponentKind::RAIL_BUTTON, .text = "0.004", .read = &readRailButtonScrewHeight, .expected = "0.004"},
    {.key = "RailButton:outerdiameter", .kind = ComponentKind::RAIL_BUTTON, .text = "0.011", .read = &readRailButtonOuterDiameterAndInnerDiameter, .expected = "0.011, 0.008"},
    {.key = "RailButton:innerdiameter", .kind = ComponentKind::RAIL_BUTTON, .text = "0.005", .read = &readRailButtonInnerDiameterAndOuterDiameter, .expected = "0.005, 0.0097"},
    {.key = "Transition:shape", .kind = ComponentKind::TRANSITION, .text = "ellipsoid", .read = &readTransitionShapeTypeAndClippedAndShapeParameter, .expected = "ELLIPSOID, true, 0.0"},
    {.key = "Transition:shapeclipped", .kind = ComponentKind::NOSE_CONE, .text = "false", .read = &readNoseConeShapeTypeAndClippedAndShapeParameter, .expected = "OGIVE, false, 1.0"},
    {.key = "Transition:shapeparameter", .kind = ComponentKind::TRANSITION, .text = "0.4", .read = &readTransitionShapeTypeAndClippedAndShapeParameter, .expected = "POWER, true, 0.4", .beforeKey = "Transition:shape", .beforeText = "power"},
    {.key = "Transition:foreradius", .kind = ComponentKind::TRANSITION, .text = "auto 0.02", .read = &readTransitionForeRadiusAndForeRadiusAutomatic, .expected = "-1.0, true"},
    {.key = "Transition:aftradius", .kind = ComponentKind::TRANSITION, .text = "0.03", .read = &readTransitionAftRadiusAndAftRadiusAutomatic, .expected = "0.03, false"},
    {.key = "Transition:foreshoulderradius", .kind = ComponentKind::TRANSITION, .text = "0.01", .read = &readTransitionForeShoulderRadius, .expected = "0.01"},
    {.key = "Transition:foreshoulderlength", .kind = ComponentKind::TRANSITION, .text = "0.015", .read = &readTransitionForeShoulderLength, .expected = "0.015"},
    {.key = "Transition:foreshoulderthickness", .kind = ComponentKind::TRANSITION, .text = "0.001", .read = &readTransitionForeShoulderThickness, .expected = "0.001"},
    {.key = "Transition:foreshouldercapped", .kind = ComponentKind::TRANSITION, .text = "true", .read = &readTransitionForeShoulderCapped, .expected = "true"},
    {.key = "Transition:aftshoulderradius", .kind = ComponentKind::NOSE_CONE, .text = "0.011", .read = &readNoseConeAftShoulderRadius, .expected = "0.011"},
    {.key = "Transition:aftshoulderlength", .kind = ComponentKind::NOSE_CONE, .text = "0.016", .read = &readNoseConeAftShoulderLength, .expected = "0.016"},
    {.key = "Transition:aftshoulderthickness", .kind = ComponentKind::NOSE_CONE, .text = "0.0011", .read = &readNoseConeAftShoulderThickness, .expected = "0.0011"},
    {.key = "Transition:aftshouldercapped", .kind = ComponentKind::NOSE_CONE, .text = "true", .read = &readNoseConeAftShoulderCapped, .expected = "true"},
    {.key = "NoseCone:isflipped", .kind = ComponentKind::NOSE_CONE, .text = "true", .read = &readNoseConeFlipped, .expected = "true"},
    {.key = "FinSet:fincount", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "4", .read = &readTrapezoidFinSetFinCount, .expected = "4"},
    {.key = "FinSet:instancecount", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .text = "5", .read = &readEllipticalFinSetFinCountAndInstanceCount, .expected = "5, 5"},
    {.key = "FinSet:rotation", .kind = ComponentKind::FREEFORM_FIN_SET, .text = "45", .read = &readFreeformFinSetBaseRotation, .expected = "0.7853981633974483"},
    {.key = "FinSet:thickness", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "0.004", .read = &readTrapezoidFinSetThickness, .expected = "0.004"},
    {.key = "FinSet:crosssection", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .text = "airfoil", .read = &readEllipticalFinSetCrossSection, .expected = "AIRFOIL"},
    {.key = "FinSet:cant", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "5", .read = &readTrapezoidFinSetCantAngle, .expected = "0.08726646259971647"},
    {.key = "FinSet:tabheight", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "0.01", .read = &readTrapezoidFinSetTabHeight, .expected = "0.01"},
    {.key = "FinSet:tablength", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "0.02", .read = &readTrapezoidFinSetTabLength, .expected = "0.02"},
    {.key = "FinSet:filletradius", .kind = ComponentKind::FREEFORM_FIN_SET, .text = "0.003", .read = &readFreeformFinSetFilletRadius, .expected = "0.003"},
    {.key = "TrapezoidFinSet:rootchord", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "0.08", .read = &readTrapezoidFinSetRootChord, .expected = "0.08"},
    {.key = "TrapezoidFinSet:tipchord", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "0.04", .read = &readTrapezoidFinSetTipChord, .expected = "0.04"},
    {.key = "TrapezoidFinSet:sweeplength", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "0.02", .read = &readTrapezoidFinSetSweep, .expected = "0.02"},
    {.key = "TrapezoidFinSet:height", .kind = ComponentKind::TRAPEZOID_FIN_SET, .text = "0.05", .read = &readTrapezoidFinSetHeight, .expected = "0.05"},
    {.key = "EllipticalFinSet:rootchord", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .text = "0.09", .read = &readEllipticalFinSetLength, .expected = "0.09"},
    {.key = "EllipticalFinSet:height", .kind = ComponentKind::ELLIPTICAL_FIN_SET, .text = "0.06", .read = &readEllipticalFinSetHeight, .expected = "0.06"},
    {.key = "TubeFinSet:fincount", .kind = ComponentKind::TUBE_FIN_SET, .text = "5", .read = &readTubeFinSetFinCount, .expected = "5"},
    {.key = "TubeFinSet:rotation", .kind = ComponentKind::TUBE_FIN_SET, .text = "30", .read = &readTubeFinSetBaseRotation, .expected = "0.5235987755982988"},
    {.key = "TubeFinSet:thickness", .kind = ComponentKind::TUBE_FIN_SET, .text = "0.0005", .read = &readTubeFinSetThickness, .expected = "5.0E-4"},
    {.key = "TubeFinSet:length", .kind = ComponentKind::TUBE_FIN_SET, .text = "0.11", .read = &readTubeFinSetLength, .expected = "0.11"},
    {.key = "TubeFinSet:radius", .kind = ComponentKind::TUBE_FIN_SET, .text = "0.02", .read = &readTubeFinSetOuterRadiusAndOuterRadiusAutomatic, .expected = "0.02, false"},
    {.key = "TubeFinSet:instancecount", .kind = ComponentKind::TUBE_FIN_SET, .text = "4", .read = &readTubeFinSetFinCountAndInstanceCount, .expected = "4, 4"},
    {.key = "RingComponent:length", .kind = ComponentKind::CENTERING_RING, .text = "0.021", .read = &readCenteringRingLength, .expected = "0.021"},
    {.key = "RingComponent:radialposition", .kind = ComponentKind::INNER_TUBE, .text = "0.003", .read = &readInnerTubeRadialPosition, .expected = "0.003"},
    {.key = "RingComponent:radialdirection", .kind = ComponentKind::TUBE_COUPLER, .text = "90", .read = &readTubeCouplerRadialDirection, .expected = "1.5707963267948966"},
    {.key = "ThicknessRingComponent:thickness", .kind = ComponentKind::ENGINE_BLOCK, .text = "0.0012", .read = &readEngineBlockThickness, .expected = "0.0012"},
    {.key = "EngineBlock:outerradius", .kind = ComponentKind::ENGINE_BLOCK, .text = "0.011", .read = &readEngineBlockOuterRadiusAndOuterRadiusAutomatic, .expected = "0.011, false"},
    {.key = "TubeCoupler:outerradius", .kind = ComponentKind::TUBE_COUPLER, .text = "auto", .read = &readTubeCouplerOuterRadiusAndOuterRadiusAutomatic, .expected = "0.023, true"},
    {.key = "InnerTube:outerradius", .kind = ComponentKind::INNER_TUBE, .text = "0.009", .read = &readInnerTubeOuterRadiusAndOuterRadiusAutomatic, .expected = "0.009, false"},
    {.key = "InnerTube:clusterscale", .kind = ComponentKind::INNER_TUBE, .text = "1.5", .read = &readInnerTubeClusterScale, .expected = "1.5"},
    {.key = "InnerTube:clusterrotation", .kind = ComponentKind::INNER_TUBE, .text = "45", .read = &readInnerTubeClusterRotation, .expected = "0.7853981633974483"},
    {.key = "RadiusRingComponent:instancecount", .kind = ComponentKind::CENTERING_RING, .text = "3", .read = &readCenteringRingInstanceCount, .expected = "3"},
    {.key = "RadiusRingComponent:instanceseparation", .kind = ComponentKind::BULKHEAD, .text = "0.05", .read = &readBulkheadInstanceSeparation, .expected = "0.05"},
    {.key = "RadiusRingComponent:innerradius", .kind = ComponentKind::BULKHEAD, .text = "0.004", .read = &readBulkheadInnerRadius, .expected = "0.0"},
    {.key = "Bulkhead:outerradius", .kind = ComponentKind::BULKHEAD, .text = "0.012", .read = &readBulkheadOuterRadiusAndOuterRadiusAutomatic, .expected = "0.012, false"},
    {.key = "CenteringRing:innerradius", .kind = ComponentKind::CENTERING_RING, .text = "0.006", .read = &readCenteringRingInnerRadiusAndInnerRadiusAutomatic, .expected = "0.006, false"},
    {.key = "CenteringRing:outerradius", .kind = ComponentKind::CENTERING_RING, .text = "0.013", .read = &readCenteringRingOuterRadiusAndOuterRadiusAutomatic, .expected = "0.013, false"},
    {.key = "MassObject:packedlength", .kind = ComponentKind::MASS_COMPONENT, .text = "0.06", .read = &readMassComponentLength, .expected = "0.06"},
    {.key = "MassObject:packedradius", .kind = ComponentKind::SHOCK_CORD, .text = "auto 0.011", .read = &readShockCordRadiusAndRadiusAutomatic, .expected = "0.023, true"},
    {.key = "MassObject:radialposition", .kind = ComponentKind::PARACHUTE, .text = "0.002", .read = &readParachuteRadialPosition, .expected = "0.002"},
    {.key = "MassObject:radialdirection", .kind = ComponentKind::STREAMER, .text = "60", .read = &readStreamerRadialDirection, .expected = "1.0471975511965976"},
    {.key = "MassComponent:mass", .kind = ComponentKind::MASS_COMPONENT, .text = "0.123", .read = &readMassComponentComponentMass, .expected = "0.123"},
    {.key = "MassComponent:masscomponenttype", .kind = ComponentKind::MASS_COMPONENT, .text = "battery", .read = &readMassComponentMassComponentType, .expected = "BATTERY"},
    {.key = "ShockCord:cordlength", .kind = ComponentKind::SHOCK_CORD, .text = "0.9", .read = &readShockCordCordLengthAndCordLengthAutomatic, .expected = "0.9, false"},
    {.key = "RecoveryDevice:cd", .kind = ComponentKind::STREAMER, .text = "0.9", .read = &readStreamerCDAndCDAutomatic, .expected = "0.9, false"},
    {.key = "RecoveryDevice:deployevent", .kind = ComponentKind::PARACHUTE, .text = "altitude", .read = &readParachuteDeployEventAndDeployAltitudeAndDeployDelay, .expected = "ALTITUDE, 200.0, 0.0"},
    {.key = "RecoveryDevice:deployaltitude", .kind = ComponentKind::STREAMER, .text = "150", .read = &readStreamerDeployEventAndDeployAltitudeAndDeployDelay, .expected = "EJECTION, 150.0, 0.0"},
    {.key = "RecoveryDevice:deploydelay", .kind = ComponentKind::PARACHUTE, .text = "1.5", .read = &readParachuteDeployEventAndDeployAltitudeAndDeployDelay, .expected = "EJECTION, 200.0, 1.5"},
    {.key = "RecoveryDevice:isdrogue", .kind = ComponentKind::PARACHUTE, .text = "true", .read = &readParachuteDrogue, .expected = "true"},
    {.key = "Parachute:diameter", .kind = ComponentKind::PARACHUTE, .text = "0.4", .read = &readParachuteDiameter, .expected = "0.4"},
    {.key = "Parachute:linecount", .kind = ComponentKind::PARACHUTE, .text = "8", .read = &readParachuteLineCount, .expected = "8"},
    {.key = "Parachute:linelength", .kind = ComponentKind::PARACHUTE, .text = "0.5", .read = &readParachuteLineLengthAndLineLengthAutomatic, .expected = "0.5, false"},
    {.key = "PodSet:instancecount", .kind = ComponentKind::POD_SET, .text = "3", .read = &readPodSetInstanceCount, .expected = "3"},
    {.key = "Streamer:striplength", .kind = ComponentKind::STREAMER, .text = "0.7", .read = &readStreamerStripLength, .expected = "0.7"},
    {.key = "Streamer:stripwidth", .kind = ComponentKind::STREAMER, .text = "0.06", .read = &readStreamerStripWidth, .expected = "0.06"},
    {.key = "Rocket:referencetype", .kind = ComponentKind::ROCKET, .text = "custom", .read = &readRocketReferenceType, .expected = "CUSTOM"},
    {.key = "Rocket:customreference", .kind = ComponentKind::ROCKET, .text = "0.5", .read = &readRocketCustomReferenceLength, .expected = "0.5"},
    {.key = "Rocket:designer", .kind = ComponentKind::ROCKET, .text = " A. Designer", .read = &readRocketDesigner, .expected = " A. Designer"},
    {.key = "Rocket:revision", .kind = ComponentKind::ROCKET, .text = "rev\n2", .read = &readRocketRevision, .expected = "rev\n2"},
    {.key = "Rocket:designtype", .kind = ComponentKind::ROCKET, .text = "commercialkit", .read = &readRocketDesignType, .expected = "COMMERCIAL_KIT"},
    {.key = "Rocket:kitname", .kind = ComponentKind::ROCKET, .text = "K ", .read = &readRocketKitName, .expected = "K "},
    {.key = "AxialStage:separationevent", .kind = ComponentKind::AXIAL_STAGE, .text = "upperignition", .read = &readAxialStageSeparationEventAndSeparationAltitudeAndSeparationDelay, .expected = "UPPER_IGNITION, 200.0, 0.0"},
    {.key = "AxialStage:separationaltitude", .kind = ComponentKind::PARALLEL_STAGE, .text = "120", .read = &readParallelStageSeparationEventAndSeparationAltitudeAndSeparationDelay, .expected = "EJECTION, 120.0, 0.0"},
    {.key = "AxialStage:separationdelay", .kind = ComponentKind::AXIAL_STAGE, .text = "2.5", .read = &readAxialStageSeparationEventAndSeparationAltitudeAndSeparationDelay, .expected = "EJECTION, 200.0, 2.5"},
});
// clang-format on
// ---- end of the generated part

/// The keys of the setter table that have a setter and no row in kTable.
[[nodiscard]] Texts keysWithoutACase()
{
    Texts missing;
    for (const std::string_view key : DocumentConfig::setterKeys())
    {
        if (std::ranges::none_of(kTable, [key](const SetterCase& row) { return row.key == key; }))
        {
            missing.emplace_back(key);
        }
    }
    return missing;
}

TEST(SetterTable, EverySetterReachesThePropertyOfItsClassAsInOpenRocket)
{
    EXPECT_EQ(checkSetterCases(kTable), Texts{});
}

TEST(SetterTable, HasACaseForEverySetterOfTheTable)
{
    EXPECT_EQ(keysWithoutACase(), Texts{});
}

}  // namespace
