#pragma once

// Generated by probes/tier8b-steppers/gen_table_pins.py from the output of
// StepperTableProbe.java: what OpenRocket's steppers answer for plain values. Do not edit:
// change the probe, run it and the generator again. Test-only.

#include <array>
#include <limits>
#include <string_view>

namespace QtRocket::Test::StepperPins
{

inline constexpr double kNaN = std::numeric_limits<double>::quiet_NaN();
inline constexpr double kInf = std::numeric_limits<double>::infinity();
/// A cell of a table that the row does not use.
inline constexpr double kUnused = 0.0;

/// AbstractRKSimulationStepper.computeTimeStep(): the time step of the conditions, their
/// maximum angle step and launch rod length, whether the status has cleared the rod, the
/// lateral pitch rate of the store, the roll rate of its flight conditions, its rotational
/// acceleration in rocket coordinates, the velocity k1.v, the previous time step of the store
/// and maxTimeStep; then the result.
struct TimeStepPin
{
    double conditionsTimeStep;
    double maxAngleStep;
    double rodLength;
    bool   rodCleared;
    double lateralPitchRate;
    double rollRate;
    double raX;
    double raY;
    double raZ;
    double vx;
    double vy;
    double vz;
    double previousTimeStep;
    double maxTimeStep;
    double expected;

    constexpr TimeStepPin(double conditionsStep, double angleStep, double rod, bool cleared,
                          double pitchRate, double roll, double accelerationX, double accelerationY,
                          double accelerationZ, double velocityX, double velocityY,
                          double velocityZ, double previous, double maximum, double result) noexcept
      : conditionsTimeStep(conditionsStep),
        maxAngleStep(angleStep),
        rodLength(rod),
        rodCleared(cleared),
        lateralPitchRate(pitchRate),
        rollRate(roll),
        raX(accelerationX),
        raY(accelerationY),
        raZ(accelerationZ),
        vx(velocityX),
        vy(velocityY),
        vz(velocityZ),
        previousTimeStep(previous),
        maxTimeStep(maximum),
        expected(result)
    {
    }
};

/// DataStore.computeDampingRatio() and computeNaturalFrequency() for a store whose rocket mass
/// (when it has one) has the longitudinal inertia `inertia`.
struct DampingPin
{
    bool   rodCleared;
    bool   hasMass;
    double inertia;
    double dampingMomentCoefficient;
    double correctiveMomentCoefficient;
    double dampingRatio;
    double naturalFrequency;

    constexpr DampingPin(bool cleared, bool mass, double longitudinalInertia, double cdm,
                         double ccm, double zeta, double omega) noexcept
      : rodCleared(cleared),
        hasMass(mass),
        inertia(longitudinalInertia),
        dampingMomentCoefficient(cdm),
        correctiveMomentCoefficient(ccm),
        dampingRatio(zeta),
        naturalFrequency(omega)
    {
    }
};

/// DataStore.computeMotorMassDerivative() for a branch with `rowCount` rows of (time, motor
/// mass), the motor mass column only when `withMotorMass`.
struct MotorMassDerivativePin
{
    std::string_view      label;
    bool                  withMotorMass;
    std::array<double, 8> rows;
    int                   rowCount;
    double                derivative;

    constexpr MotorMassDerivativePin(std::string_view text, bool motorMass,
                                     const std::array<double, 8>& values, int count,
                                     double result) noexcept
      : label(text), withMotorMass(motorMass), rows(values), rowCount(count), derivative(result)
    {
    }
};

/// DataStore.getWindDirection() of the wind vector (x, y, z).
struct WindDirectionPin
{
    double x;
    double y;
    double z;
    double direction;

    constexpr WindDirectionPin(double windX, double windY, double windZ, double result) noexcept
      : x(windX), y(windY), z(windZ), direction(result)
    {
    }
};

/// DataStore.computeCorrectiveMomentCoefficient() for a store with flight conditions (angle of
/// attack, temperature, pressure, Mach number, reference length), a rocket mass at `cg` and
/// forces with the CP at `cpX` and the weight `cna`, each only when its flag says so.
struct CorrectivePin
{
    bool   rodCleared;
    bool   hasConditions;
    bool   hasMass;
    bool   hasForces;
    double aoa;
    double temperature;
    double pressure;
    double mach;
    double refLength;
    double cpX;
    double cna;
    double cg;
    double expected;

    constexpr CorrectivePin(bool cleared, bool conditions, bool mass, bool forces, double angle,
                            double kelvin, double pascal, double machNumber, double length,
                            double cp, double normalForceSlope, double centreOfGravity,
                            double result) noexcept
      : rodCleared(cleared),
        hasConditions(conditions),
        hasMass(mass),
        hasForces(forces),
        aoa(angle),
        temperature(kelvin),
        pressure(pascal),
        mach(machNumber),
        refLength(length),
        cpX(cp),
        cna(normalForceSlope),
        cg(centreOfGravity),
        expected(result)
    {
    }
};

/// computeCD() of the tumble and of the landing stepper for the rocket of `maker` (a method of
/// TestRockets.java) in the configuration the step scenarios use, with only the stage
/// `onlyStage` active (-1: every stage) and every recovery device of the active stages
/// deployed, and the reference area of the configuration.
struct DragCoefficientPin
{
    std::string_view maker;
    int              onlyStage;
    double           tumble;
    double           landing;
    double           referenceArea;

    constexpr DragCoefficientPin(std::string_view method, int stage, double tumbleCd,
                                 double landingCd, double area) noexcept
      : maker(method), onlyStage(stage), tumble(tumbleCd), landing(landingCd), referenceArea(area)
    {
    }
};

/// The launch rod direction AbstractRKSimulationStepper.initialize() puts into the store for
/// the conditions' launch rod angle and direction.
struct RodDirectionPin
{
    double rodAngle;
    double rodDirection;
    double x;
    double y;
    double z;

    constexpr RodDirectionPin(double angle, double direction, double rodX, double rodY,
                              double rodZ) noexcept
      : rodAngle(angle), rodDirection(direction), x(rodX), y(rodY), z(rodZ)
    {
    }
};

/// BasicTumbleStepper.computeCD() for the Estes Alpha III with `finCount` fins.
struct FinCountPin
{
    int    finCount;
    double tumble;

    constexpr FinCountPin(int count, double tumbleCd) noexcept : finCount(count), tumble(tumbleCd)
    {
    }
};

// Java's values, pasted digit for digit: one near pi or ln 2 is not that constant.
// NOLINTBEGIN(modernize-use-std-numbers)
// clang-format off
inline constexpr std::array<TimeStepPin, 46> kTimeStepPins{{
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.05},
    {0.02, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.02},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.03,
     0.03},
    {0.05, 0.05235987755982988, 1.0, true, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.02617993877991494},
    {0.05, 0.02, 1.0, true, 0.9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.022222222222222223},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 40.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.024713862208239703},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, -40.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.024713862208239703},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.03490658503988659},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, -3.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.011635528346628864},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 3.0, -5.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.013962634015954637},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, -7.0, 2.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.00997331001139617},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, kNaN, 2.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.03490658503988659},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 4.0, kNaN, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.017453292519943295},
    {0.05, 0.05235987755982988, 1.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, kNaN, 1.0,
     0.01},
    {0.1, 0.05235987755982988, 3.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.0, kNaN, 1.0,
     0.015},
    {0.1, 0.05235987755982988, 3.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 16.0, kNaN, 1.0,
     0.015},
    {0.05, 0.05235987755982988, 1.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 50.0, kNaN, 1.0,
     0.0025},
    {0.05, 0.05235987755982988, 1.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, kNaN, 1.0,
     0.01},
    {0.05, 0.05235987755982988, 0.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, kNaN, 1.0,
     0.0025},
    {0.1, 0.05235987755982988, 3.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.0, kNaN, 1.0, 0.1},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, 0.01, 1.0,
     0.015},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, 0.04, 1.0,
     0.05},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, 0.0, 1.0,
     0.0025},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.051,
     0.051},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.0524,
     0.0524},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.0526,
     0.05},
    {0.05, 0.05235987755982988, 1.0, true, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.028,
     0.028},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, 0.02, 0.0325,
     0.03},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, 0.02, 0.0326,
     0.03},
    {0.05, 0.05235987755982988, 1.0, true, 100.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.0025},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.001,
     0.0025},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.0,
     0.0025},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, -0.5,
     0.0025},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.0025,
     0.0025},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 0.0024,
     0.0025},
    {5.0E-4, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.001},
    {0.0, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.001},
    {5.0E-4, 0.05235987755982988, 1.0, false, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, kNaN, 1.0,
     2.0E-4},
    {0.001, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.001},
    {0.05, 0.05235987755982988, 1.0, true, kNaN, kNaN, kNaN, kNaN, kNaN, 0.0, 0.0, 30.0, kNaN, kNaN,
     0.05},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, kInf,
     0.05},
    {0.05, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 1.0E-300, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.05},
    {kNaN, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, kNaN, 1.0,
     0.001},
    {kNaN, 0.05235987755982988, 1.0, true, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.0, 0.02, kNaN,
     0.001},
    {0.05, 0.05235987755982988, 1.0, true, 1.5, 25.0, 2.0, 1.0, 1.5, 0.0, 0.0, 30.0, 0.03, 0.04,
     0.023271056693257727},
    {0.05, 0.05235987755982988, 2.0, false, 1.5, 25.0, 2.0, 1.0, 1.5, 3.0, 4.0, 12.0, 0.03, 0.04,
     0.01},
}};

inline constexpr std::array<DampingPin, 17> kDampingPins{{
    {true, true, 2.0E-4, 0.003, 0.9, 0.11180339887498948, 67.08203932499369},
    {true, true, 2.0E-4, 0.0, 0.9, 0.0, 67.08203932499369},
    {true, true, 0.5, 0.25, 8.0, 0.0625, 4.0},
    {true, true, 2.0E-4, -0.003, 0.9, -0.11180339887498948, 67.08203932499369},
    {false, true, 2.0E-4, 0.003, 0.9, 0.0, 0.0},
    {false, false, 2.0E-4, 0.003, 0.9, kNaN, 0.0},
    {true, false, 2.0E-4, 0.003, 0.9, kNaN, kNaN},
    {true, true, 2.0E-4, kNaN, 0.9, kNaN, 67.08203932499369},
    {true, true, 2.0E-4, 0.003, kNaN, kNaN, kNaN},
    {true, true, 0.0, 0.003, 0.9, kNaN, kNaN},
    {true, true, 2.0E-4, 0.003, 0.0, kNaN, 0.0},
    {true, true, 2.0E-4, 0.003, -0.9, kNaN, kNaN},
    {true, true, 2.0E-4, 0.003, kInf, 0.0, kInf},
    {true, true, 2.0E-4, kInf, 0.9, kInf, 67.08203932499369},
    {true, true, 1.0E-200, 0.003, 1.0E-200, kNaN, 1.0},
    {true, true, kNaN, 0.003, 0.9, kNaN, kNaN},
    {false, true, kNaN, kNaN, kNaN, 0.0, 0.0},
}};

inline constexpr std::array<MotorMassDerivativePin, 11> kMotorMassDerivativePins{{
    {"no rows", true, {kUnused, kUnused, kUnused, kUnused, kUnused, kUnused, kUnused, kUnused}, 0,
     kNaN},
    {"one row", true, {0.0, 0.0125, kUnused, kUnused, kUnused, kUnused, kUnused, kUnused}, 1,
     kNaN},
    {"two rows", true, {0.0, 0.0125, 0.05, 0.0121, kUnused, kUnused, kUnused, kUnused}, 2,
     -0.008000000000000021},
    {"the last two of four", true, {0.0, 0.0125, 0.05, 0.0121, 0.1, 0.0112, 0.13, 0.0109}, 4,
     -0.009999999999999998},
    {"no motor mass column", false, {0.0, 0.0, 0.05, 0.0, kUnused, kUnused, kUnused, kUnused}, 2,
     kNaN},
    {"no time between", true, {0.2, 0.0125, 0.2, 0.0121, kUnused, kUnused, kUnused, kUnused}, 2,
     kNaN},
    {"time runs backwards", true, {0.2, 0.0125, 0.1, 0.0121, kUnused, kUnused, kUnused, kUnused}, 2,
     kNaN},
    {"a NaN time", true, {0.2, 0.0125, kNaN, 0.0121, kUnused, kUnused, kUnused, kUnused}, 2, kNaN},
    {"a NaN mass", true, {0.2, 0.0125, 0.3, kNaN, kUnused, kUnused, kUnused, kUnused}, 2, kNaN},
    {"growing", true, {0.2, 0.0121, 0.3, 0.0125, kUnused, kUnused, kUnused, kUnused}, 2,
     0.004000000000000011},
    {"constant", true, {0.2, 0.0121, 0.3, 0.0121, kUnused, kUnused, kUnused, kUnused}, 2, 0.0},
}};

inline constexpr std::array<WindDirectionPin, 16> kWindDirectionPins{{
    {0.0, 0.0, 0.0, 0.0},
    {0.0, 1.0, 0.0, 0.0},
    {1.0, 0.0, 0.0, 1.5707963267948966},
    {0.0, -1.0, 0.0, 3.141592653589793},
    {-1.0, 0.0, 0.0, 4.71238898038469},
    {1.0, 1.0, 0.0, 0.7853981633974483},
    {-1.0, -1.0, 5.0, 3.9269908169872414},
    {3.0, -4.0, 0.0, 2.498091544796509},
    {-2.5, 0.5, 1.0, 4.90978454023457},
    {1.0E-300, 1.0E-300, 0.0, 0.7853981633974483},
    {kNaN, 1.0, 0.0, kNaN},
    {1.0, kNaN, 0.0, kNaN},
    {0.0, 0.0, 7.0, 0.0},
    {-0.0, 1.0, 0.0, 0.0},
    {-1.0E-20, 1.0, 0.0, 6.283185307179586},
    {4.456036800307177, 2.2679806071278867, 0.0, 1.1},
}};

inline constexpr std::array<CorrectivePin, 12> kCorrectivePins{{
    {true, true, true, true, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2,
     0.5489909139922923},
    {true, true, true, true, 0.0, 250.0, 60000.0, 1.4, 0.1, 1.1, 14.0, 0.8, 2720.648377870446},
    {true, true, true, true, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.18, 9.5, 0.2,
     -0.5489909139922937},
    {true, true, true, true, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.22, 0.0, 0.2, -0.0},
    {true, true, true, true, 0.05, 288.15, 101325.0, 0.0, 0.024, 0.22, 9.5, 0.2, 0.0},
    {true, true, true, true, kNaN, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2, kNaN},
    {false, true, true, true, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2, 0.0},
    {false, true, true, true, kNaN, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2, 0.0},
    {true, false, true, true, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2, kNaN},
    {true, true, false, true, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2, kNaN},
    {true, true, true, false, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2, kNaN},
    {false, false, false, false, 0.05, 288.15, 101325.0, 0.3, 0.024, 0.22, 9.5, 0.2, kNaN},
}};

inline constexpr std::array<DragCoefficientPin, 25> kDragCoefficientPins{{
    {"makeEstesAlphaIII", -1, 16.1879614113765, 125.00000000000001, 4.523893421169302E-4},
    {"makeBeta", -1, 26.958330088056375, 125.00000000000001, 4.523893421169302E-4},
    {"makeBeta", 0, 16.1879614113765, 125.00000000000001, 4.523893421169302E-4},
    {"makeBeta", 1, 10.770368676679873, 0.0, 4.523893421169302E-4},
    {"makeSimple2Stage", -1, 7.130141450516912, 0.0, 3.141592653589793E-4},
    {"makeSimple2Stage", 0, 3.565070725258456, 0.0, 3.141592653589793E-4},
    {"makeSimple2Stage", 1, 3.565070725258456, 0.0, 3.141592653589793E-4},
    {"makeBigBlue", -1, 17.568488954913583, 0.0, 0.003421194399759285},
    {"makeIsoHaisu", -1, 20.50262496299539, 0.0, 0.015393804002589988},
    {"makeFalcon9Heavy", -1, 26.144857073019942, 6.656804733727811, 0.0084948665353068},
    {"makeFalcon9Heavy", 0, 3.0505220414529117, 6.656804733727811, 0.0084948665353068},
    {"makeFalcon9Heavy", 1, 7.40793916936822, 0.0, 0.004656625710783471},
    {"makeFalcon9Heavy", 2, 34.721986231446245, 0.0, 0.004656625710783471},
    {"makeMultiStageEventTestRocket", -1, 26.245376025041054, 540.0000000000001,
     3.141592653589793E-4},
    {"makeMultiStageEventTestRocket", 0, 9.511565294820688, 180.00000000000003,
     3.141592653589793E-4},
    {"makeMultiStageEventTestRocket", 1, 10.571644277958821, 0.0, 3.141592653589793E-4},
    {"makeMultiStageEventTestRocket", 2, 12.575849902574573, 734.6938775510204,
     1.539380400258999E-4},
    {"makeEndPlateRocket", -1, 43.079573691401514, 0.0, 3.141592653589793E-4},
    {"makeEstesAlphaIIIWithPods", -1, 16.75296145935273, 125.00000000000001, 4.523893421169302E-4},
    {"makeEstesAlphaIIIWithMotorPods", -1, 18.416130614663036, 125.00000000000001,
     4.523893421169302E-4},
    {"makeEstesAlphaIIIWithSecondMotor", -1, 16.1879614113765, 125.00000000000001,
     4.523893421169302E-4},
    {"makeEstesAlphaIIIwithInlinePod", -1, 16.1879614113765, 125.00000000000001,
     4.523893421169302E-4},
    {"makeClusterPods", -1, 11.40822632082706, 0.0, 0.001963495408493621},
    {"makeClusterPods", 0, 2.852056580206765, 0.0, 0.001963495408493621},
    {"makeClusterPods", 1, 8.556169740620296, 0.0, 0.001963495408493621},
}};

inline constexpr std::array<RodDirectionPin, 9> kRodDirectionPins{{
    {0.0, 0.0, 0.0, 0.0, 1.0},
    {0.1, 0.0, 6.11303370722411E-18, 0.09983341664682815, 0.9950041652780258},
    {0.1, 0.5, 0.0478626895466034, 0.08761206554319242, 0.9950041652780258},
    {0.2, 1.5707963267948966, 0.19866933079506122, 0.0, 0.9800665778412416},
    {-0.3, 2.5, -0.17686061170665618, 0.2367541268318426, 0.955336489125606},
    {1.0471975511965976, 4.0, -0.6554101865841193, -0.5660719806895319, 0.5000000000000001},
    {0.05, 6.0, -0.013964954481335029, 0.04798851328517438, 0.9987502603949663},
    {0.0, 1.0, 0.0, 0.0, 1.0},
    {1.5707963267948966, 3.141592653589793, 6.123233995736766E-17, -1.0, 6.123233995736766E-17},
}};

inline constexpr std::array<FinCountPin, 8> kFinCountPins{{
    {1, 10.475183148505746},
    {2, 13.614072303929236},
    {3, 16.1879614113765},
    {4, 18.699072735715294},
    {5, 18.196850470847536},
    {6, 19.264072783691518},
    {7, 18.95018386814917},
    {8, 18.950183868149175},
}};
// clang-format on
// NOLINTEND(modernize-use-std-numbers)

}  // namespace QtRocket::Test::StepperPins
