#pragma once

#include <memory>

namespace QtRocket
{

class FlightData;
class SimulationConditions;

/// A simulation engine that controls the flow of a simulation (OpenRocket's
/// simulation/SimulationEngine). This typically maintains flight events and related actions,
/// while continuously calling a SimulationStepper to move the rocket forward step by step.
///
/// Deviations from OpenRocket:
/// - simulate() takes the conditions by std::shared_ptr: the simulation statuses of the run hold
///   them (Java: a reference).
/// - getFlightData() gives the data by std::shared_ptr, null before simulate() (Java: null).
class SimulationEngine
{
public:
    virtual ~SimulationEngine() = default;

    SimulationEngine& operator=(const SimulationEngine&) = delete;
    SimulationEngine& operator=(SimulationEngine&&)      = delete;

    /// Simulates the flight of a rocket under @p simulation, the simulation conditions, which
    /// must belong to a Simulation (SimulationConditions::setSimulation()).
    /// @throws SimulationException if an error occurs during simulation
    virtual void simulate(const std::shared_ptr<SimulationConditions>& simulation) = 0;

    /// The data generated by the simulation; null until simulate() has been called.
    [[nodiscard]] virtual const std::shared_ptr<FlightData>& getFlightData() const noexcept = 0;

protected:
    SimulationEngine()                        = default;
    SimulationEngine(const SimulationEngine&) = default;
    SimulationEngine(SimulationEngine&&)      = default;
};

}  // namespace QtRocket
